(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.make_lisp_string('IIIIKA/WEB');
var l2=internals.intern('CL','KEYWORD');
l2.value=l2;
var l3=internals.intern('NIL','COMMON-LISP');
var l4=internals.QIList(l2,l3);
var l5=internals.intern('%DEFPACKAGE');
var l6=internals.make_lisp_string('name');
var l7=internals.intern('INTERN','COMMON-LISP');
var l8=new internals.Symbol('*DEFAULT-LANGUAGE*');
var l9=new internals.Symbol('*LANGUAGE*');
var l10=new internals.Symbol('DEFTRANSLATION');
var l11=new internals.Symbol('DEFINE-BYNAME-ADJ');
var l12=new internals.Symbol('DEFINE-BYNAME-NOUN');
var l13=new internals.Symbol('GET-BYNAME');
var l14=new internals.Symbol('GET-BYNAME-ADJ');
var l15=new internals.Symbol('GET-BYNAME-NOUN');
var l16=internals.QIList(l8,l9,l10,l11,l12,l13,l14,l15,l3);
var l17=internals.intern('MAPCAR','COMMON-LISP');
var l18=internals.intern('EXPORT','COMMON-LISP');
var l19=internals.intern('IIIIKA/WEB','KEYWORD');
l19.value=l19;
var l20=internals.intern('FIND-PACKAGE','COMMON-LISP');
(function(v1){l18.fvalue(internals.pv,l17.fvalue(internals.pv,(function JSCL_USER_NIL(values,v2){internals.checkArgs(arguments.length-1,1);
var v3=this;
return l7.fvalue(values,internals.js_to_lisp((function(){var TMP=v2[internals.xstring(l6)];
return TMP===undefined?l3.value:TMP;
})()),v1);
}),l16),v1);
return v1;
})(l5.fvalue(internals.pv,l1,l4));
l20.fvalue(internals.pv,l19.value);
var l21=internals.intern('*PACKAGE*','COMMON-LISP');
var l22=internals.intern('FIND-PACKAGE-OR-FAIL');
l21.value=l22.fvalue(internals.pv,l19);
l21.value=l22.fvalue(internals.pv,l19);
var l23=internals.intern('JS-LIKE-CASE','IIIIKA/WEB');
var l24=internals.intern('MAKE-STRING-OUTPUT-STREAM','COMMON-LISP');
var l25=internals.intern('CHAR=','COMMON-LISP');
var l26=internals.intern('T','COMMON-LISP');
var l27=internals.intern('WRITE-CHAR','COMMON-LISP');
var l28=internals.intern('MAP','COMMON-LISP');
var l29=internals.intern('GET-OUTPUT-STREAM-STRING','COMMON-LISP');
l23.fvalue=(function(){var FUNC=(function JSCL_USER_JSLIKECASE(values,v4){internals.checkArgs(arguments.length-1,1);
var v5=this;
return (function(){return (function(v7){(function(v8){return l28.fvalue(internals.pv,l3.value,(function JSCL_USER_NIL(values,v9){internals.checkArgs(arguments.length-1,1);
var v10=this;
return l25.fvalue(internals.pv,'-',v9)!==l3.value?(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v13){switch(arguments.length-1){case 0:v13=l3.value;
;
default:break;
}var v12=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v12=new internals.Cons(arguments[I+1],v12);
var v14=this;
return v8=v13;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l26.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})():v8!==l3.value?(l27.fvalue(internals.pv,internals.safe_char_upcase(v9),v7),(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v17){switch(arguments.length-1){case 0:v17=l3.value;
;
default:break;
}var v16=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v16=new internals.Cons(arguments[I+1],v16);
var v18=this;
return v8=v17;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l3.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})()):l27.fvalue(values,internals.safe_char_downcase(v9),v7);
}),v4);
})(l3.value);
return l29.fvalue(values,v7);
})(l24.fvalue(internals.pv));
})();
});
FUNC.fname='JS-LIKE-CASE';
FUNC.docstring='Trun a-like-string to aLikeString. ';
return FUNC;
})();
l23;
var l30=internals.intern('GETHASH*','IIIIKA/WEB');
var l31=internals.intern('ENDP','COMMON-LISP');
var l32=internals.intern('HASH-TABLE-P','COMMON-LISP');
var l33=internals.intern('FIRST','COMMON-LISP');
var l34=internals.intern('GETHASH','COMMON-LISP');
var l35=internals.intern('REST','COMMON-LISP');
l30.fvalue=(function(){var FUNC=(function JSCL_USER_GETHASH(values,v20){internals.checkArgsAtLeast(arguments.length-1,1);
var v19=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v19=new internals.Cons(arguments[I+1],v19);
var v21=this;
return (function(){return l31.fvalue(internals.pv,v19)!==l3.value?v20:l32.fvalue(internals.pv,v20)!==l3.value?(function(){var F=internals.symbolFunction(l30);
var ARGS=[values,l34.fvalue(internals.pv,l33.fvalue(internals.pv,v19),v20)];
var TAIL=l35.fvalue(internals.pv,v19);
while (TAIL!=l3.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})():l3.value;
})();
});
FUNC.fname='GETHASH*';
FUNC.docstring="Get nested `hash-table' value by unpacking the `keys'. ";
return FUNC;
})();
l30;
var l36=internals.intern('LIST->ARRAY','IIIIKA/WEB');
var l37=internals.intern('VECTOR','COMMON-LISP');
var l38=internals.intern('IDENTITY','COMMON-LISP');
l36.fvalue=(function(){var FUNC=(function JSCL_USER_LISTARRAY(values,v23){internals.checkArgs(arguments.length-1,1);
var v24=this;
return (function(){return l28.fvalue(values,l37,internals.symbolFunction(l38),v23);
})();
});
FUNC.fname='LIST->ARRAY';
return FUNC;
})();
l36;
var l39=internals.intern('ARRAY->LIST','IIIIKA/WEB');
var l40=internals.intern('LIST','COMMON-LISP');
l39.fvalue=(function(){var FUNC=(function JSCL_USER_ARRAYLIST(values,v26){internals.checkArgs(arguments.length-1,1);
var v27=this;
return (function(){return l28.fvalue(values,l40,internals.symbolFunction(l38),v26);
})();
});
FUNC.fname='ARRAY->LIST';
return FUNC;
})();
l39;
l21.value=l22.fvalue(internals.pv,l19);
var l41=internals.intern('*DEFAULT-LANGUAGE*','IIIIKA/WEB');
var l42=internals.intern('CN-ZH','KEYWORD');
l42.value=l42;
var l43=internals.make_lisp_string('vardoc');
var l44=internals.make_lisp_string('Default UI language. ');
l41.value=l42.value;
(function(){var OBJ=l41;
var TMP=OBJ[internals.xstring(l43)]=internals.lisp_to_js(l44);
return TMP===undefined?l3.value:TMP;
})();
l41;
var l45=internals.intern('*LANGUAGE*','IIIIKA/WEB');
var l46=internals.make_lisp_string("The UI language.\n\nBy default, the language is `*default-language*'.\nPossible options:\n+ `:en'\n+ `:cn-zh'\n+ ... (translation contribute is wanted)\n\nTo contribute translations, use `deftranslation'\nmacro for defining the translations. ");
l45.value=l42.value;
(function(){var OBJ=l45;
var TMP=OBJ[internals.xstring(l43)]=internals.lisp_to_js(l46);
return TMP===undefined?l3.value:TMP;
})();
l45;
var l47=internals.intern('*COMMON-MESSAGE*','IIIIKA/WEB');
var l48=internals.intern('MAKE-HASH-TABLE','COMMON-LISP');
var l49=internals.make_lisp_string("The common message goes here.\n\nUse `deftranslation'. ");
l47.value=l48.fvalue(internals.pv);
(function(){var OBJ=l47;
var TMP=OBJ[internals.xstring(l43)]=internals.lisp_to_js(l49);
return TMP===undefined?l3.value:TMP;
})();
l47;
var l50=internals.intern('*BYNAME*','IIIIKA/WEB');
var l51=internals.make_lisp_string("The general CommonMsg/Byname Table.\n\nThe hash table is like:\n\n    language -> [adj, noun]\n\nwhere `adj' and `noun' is an array.\n\nUse `define-byname-adj' and `define-byname-noun' to\nsets the byname tags.\n\nNote: please refer to `scripts/splat3-gen.lisp' and\n`scripts/splat3_CNzh_unicode.json'.\n\nCredit: Jeanny's repo*.\n*: https://github.com/Leanny/splat3");
l50.value=l48.fvalue(internals.pv);
(function(){var OBJ=l50;
var TMP=OBJ[internals.xstring(l43)]=internals.lisp_to_js(l51);
return TMP===undefined?l3.value:TMP;
})();
l50;
var l52=internals.intern('GETUI','IIIIKA/WEB');
var l53=internals.make_lisp_string('~C');
var l54=internals.intern('FORMAT','COMMON-LISP');
var l55=internals.make_lisp_string('ロロロ');
var l56=internals.intern('LISTP','COMMON-LISP');
var l57=internals.intern('WRITE-STRING','COMMON-LISP');
l52.fvalue=(function(){var FUNC=(function JSCL_USER_GETUI(values,v29,v30){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v30=internals.symbolValue(l45);
;
default:break;
}var v31=this;
return (function(){return (function(v38){return l56.fvalue(internals.pv,v29)!==l3.value?(function(v39){(function(v40,v41){return (function(){return (function(){var v43=1;
var v44=[];
TBLOOP:while (true){try{switch(v43){case 1:if (l31.fvalue(internals.pv,v41)!==l3.value) (function(){throw new internals.TagNLX(v44,2);
})();
 else l3.value;
v40=internals.car(v41);
v41=internals.cdr(v41);
l57.fvalue(internals.pv,v38(internals.pv,v40),v39);
l27.fvalue(internals.pv,' ',v39);
(function(){throw new internals.TagNLX(v44,1);
})();
case 2:default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v44) v43=JUMP.label;
 else throw JUMP;
}}return l3.value;
})();
})();
})(l3.value,v29);
return l29.fvalue(values,v39);
})(l24.fvalue(internals.pv)):v38(values,v29);
})((function JSCL_USER_NIL(values,v33){internals.checkArgs(arguments.length-1,1);
var v34=this;
return (function(){return (function(){var X=v33;
return typeof X==='object'&&X!==null&&'length' in X&&X.stringp==1?l26.value:l3.value;
})()!==l3.value?v33:(function(){var X=v33;
return typeof X=='string'&&(X.length==1||X.length==2)?l26.value:l3.value;
})()!==l3.value?l54.fvalue(values,l3.value,l53,v33):(function(v36){return v36!==l3.value?v36:(function(v37){return v37!==l3.value?v37:l55;
})(l30.fvalue(internals.pv,internals.symbolValue(l47),internals.symbolValue(l41),v33));
})(l30.fvalue(internals.pv,internals.symbolValue(l47),v30,v33));
})();
}));
})();
});
FUNC.fname='GETUI';
FUNC.docstring="Get UI message for `language'.\n\nIf `ui' is not known to `language',\nwill fallback to `*default-language*'.\nIf `*default-language*' fails to render `ui',\nwill render `ui' as `ロロロ'. (Katakana RO, RO, RO)\n\nNote: why `ロロロ'?\nNormally if computer fails to render the character,\nit will render white square `□'. So in chinese,\nwe are calling it `口' (kǒu, mouse, 嘴). To render it\nusing Splatoon fonts, using Katakana RO character. ";
return FUNC;
})();
l52;
var l58=internals.intern('ENSURE-BYNAME-SLOT','IIIIKA/WEB');
var l59=internals.intern('MAKE-ARRAY','COMMON-LISP');
var l60=internals.intern('ASET');
var l61=internals.intern('ADJUSTABLE','KEYWORD');
l61.value=l61;
var l62=internals.intern('FILL-POINTER','KEYWORD');
l62.value=l62;
var l63=internals.intern('SETHASH');
l58.fvalue=(function(){var FUNC=(function JSCL_USER_ENSUREBYNAMESLOT(values,v45){internals.checkArgs(arguments.length-1,1);
var v46=this;
return (function(){return l34.fvalue(internals.pv,v45,internals.symbolValue(l50))!==l3.value?l3.value:(function(v48){(function(){var v50=v48;
var v51=0;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v53){switch(arguments.length-1){case 0:v53=l3.value;
;
default:break;
}var v52=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v52=new internals.Cons(arguments[I+1],v52);
var v54=this;
return l60.fvalue(values,v50,v51,v53);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l59.fvalue(values,0,l61.value,l26.value,l62.value,0);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v56=v48;
var v57=1;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v59){switch(arguments.length-1){case 0:v59=l3.value;
;
default:break;
}var v58=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v58=new internals.Cons(arguments[I+1],v58);
var v60=this;
return l60.fvalue(values,v56,v57,v59);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l59.fvalue(values,0,l61.value,l26.value,l62.value,0);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return (function(){var v62=v45;
var v63=internals.symbolValue(l50);
var v64=l3.value;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v66){switch(arguments.length-1){case 0:v66=l3.value;
;
default:break;
}var v65=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v65=new internals.Cons(arguments[I+1],v65);
var v67=this;
return l63.fvalue(internals.pv,v66,v62,v63),v66;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v48;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})(l59.fvalue(internals.pv,2));
})();
});
FUNC.fname='ENSURE-BYNAME-SLOT';
FUNC.docstring='Ensure the existance of byname [adj, noun] structure. ';
return FUNC;
})();
l58;
var l64=internals.intern('GET-BYNAME--AREF','IIIIKA/WEB');
var l65=internals.intern('AREF','COMMON-LISP');
var l66=internals.intern('LENGTH','COMMON-LISP');
var l67=internals.intern('MOD','COMMON-LISP');
var l68=internals.intern('RANDOM','COMMON-LISP');
l64.fvalue=(function(){var FUNC=(function JSCL_USER_GETBYNAMEAREF(values,v68,v69,v70){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v69=l3.value;
;
case 2:v70=internals.symbolValue(l45);
;
default:break;
}var v71=this;
return (function(){return (function(){var v74=l65.fvalue(internals.pv,(function(v75){return v75!==l3.value?v75:l34.fvalue(internals.pv,internals.symbolValue(l41),internals.symbolValue(l50));
})(l34.fvalue(internals.pv,v70,internals.symbolValue(l50))),v68);
var v76=v69!==l3.value?l67.fvalue(internals.pv,v69,l66.fvalue(internals.pv,v74)):l68.fvalue(internals.pv,l66.fvalue(internals.pv,v74));
return values(l65.fvalue(internals.pv,v74,v76),v76);
})();
})();
});
FUNC.fname='GET-BYNAME--AREF';
FUNC.docstring="Get tag of `id' for byname with `aref'.\nReturn values are tag, id of tag.\n\nIf `id' is `NIL', will return random `id'. ";
return FUNC;
})();
l64;
var l69=internals.intern('GET-BYNAME','IIIIKA/WEB');
var l70=internals.intern('CONS','COMMON-LISP');
var l71=internals.intern('VALUES-LIST','COMMON-LISP');
l69.fvalue=(function(){var FUNC=(function JSCL_USER_GETBYNAME(values,v77,v78,v79){internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 0:v77=l3.value;
;
case 1:v78=l3.value;
;
case 2:v79=internals.symbolValue(l45);
;
default:break;
}var v80=this;
return (function(){return l71.fvalue(values,l17.fvalue(internals.pv,internals.symbolFunction(l70),(function(){var FUNC=internals.symbolFunction(l40);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l64.fvalue(values,0,v77,v79);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})(),(function(){var FUNC=internals.symbolFunction(l40);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l64.fvalue(values,1,v78,v79);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})()));
})();
});
FUNC.fname='GET-BYNAME';
FUNC.docstring="Get Byname as cons.\nReturn values are (adj . noun), (adj-id . noun-id).\n\nIf `adj' or `noun' is `NIL', return a random `adj' or `noun';\nor `adj' or `noun' should be the index. ";
return FUNC;
})();
l69;
l21.value=l22.fvalue(internals.pv,l19);
var l72=internals.intern('*SELF*','IIIIKA/WEB');
var l73=internals.make_lisp_string('vardoc');
var l74=internals.make_lisp_string('Used for self reference. ');
if ((l72.value!==undefined?l26.value:l3.value)!==l3.value) l3.value;
 else l72.value=l3.value;
(function(){var OBJ=l72;
var TMP=OBJ[internals.xstring(l73)]=internals.lisp_to_js(l74);
return TMP===undefined?l3.value:TMP;
})();
l72;
var l75=internals.intern('SET-TIME-OUT','IIIIKA/WEB');
var l76=internals.intern('*ROOT*');
var l77=internals.make_lisp_string('setTimeout');
l75.fvalue=(function(){var FUNC=(function JSCL_USER_SETTIMEOUT(values,v82,v83){internals.checkArgs(arguments.length-1,2);
var v84=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l76)[internals.xstring(l77)](internals.lisp_to_js(v83),internals.lisp_to_js(v82)));
})();
});
FUNC.fname='SET-TIME-OUT';
FUNC.docstring="setTimeout(fn, delay)\n\nArgument:\n`delay' seconds;\n`fn'    function;";
return FUNC;
})();
l75;
var l78=internals.intern('ADD-EVENT-LISTENER','IIIIKA/WEB');
var l79=internals.intern('KEYWORDP','COMMON-LISP');
var l80=internals.make_lisp_string('addEventListener');
l78.fvalue=(function(){var FUNC=(function JSCL_USER_ADDEVENTLISTENER(values,v86,v87,v88){internals.checkArgs(arguments.length-1,3);
var v89=this;
return (function(){return internals.js_to_lisp(v86[internals.xstring(l80)](internals.lisp_to_js(l79.fvalue(internals.pv,v87)!==l3.value?l23.fvalue(internals.pv,internals.js_to_lisp((function(){var TMP=v87[internals.xstring(l6)];
return TMP===undefined?l3.value:TMP;
})())):v87),internals.lisp_to_js(v88)));
})();
});
FUNC.fname='ADD-EVENT-LISTENER';
FUNC.docstring="elem.addEventListener(type, fn)\n\nArgument:\n`type' could be\n    {string | keyword}\nif is `keyword', turn it into js-like string first.\n`fn' should be function";
return FUNC;
})();
l78;
var l81=internals.intern('GET-ELEM-BY-ID','IIIIKA/WEB');
var l82=internals.make_lisp_string('document');
var l83=internals.make_lisp_string('getElementById');
var l84=internals.make_lisp_string("Cannot found elem with id `~A'. ");
var l85=internals.intern('ERROR','COMMON-LISP');
l81.fvalue=(function(){var FUNC=(function JSCL_USER_GETELEMBYID(values,v91){internals.checkArgs(arguments.length-1,1);
var v92=this;
return (function(){return (function(v94){if (v94!==l3.value) l3.value;
 else l85.fvalue(internals.pv,l54.fvalue(internals.pv,l3.value,l84,v91));
return v94;
})(internals.js_to_lisp(internals.symbolValue(l76)[internals.xstring(l82)][internals.xstring(l83)](internals.lisp_to_js(v91))));
})();
});
FUNC.fname='GET-ELEM-BY-ID';
FUNC.docstring="Get element by `id'.\nReturn HTML element or `NIL' if could not get. ";
return FUNC;
})();
l81;
var l86=internals.intern('TEXT','IIIIKA/WEB');
var l87=internals.make_lisp_string('innerText');
l86.fvalue=(function(){var FUNC=(function JSCL_USER_TEXT(values,v95){internals.checkArgs(arguments.length-1,1);
var v96=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v95[internals.xstring(l87)];
return TMP===undefined?l3.value:TMP;
})());
})();
});
FUNC.fname='TEXT';
FUNC.docstring="Get/Set `elem' text by setting innerText. ";
return FUNC;
})();
l86;
var l88=internals.intern('(SETF_TEXT)','IIIIKA/WEB');
var l89=internals.make_lisp_string('innerText');
var l90=internals.intern('VALIDATE-REQVARS');
var l91=internals.intern('GENSYM','COMMON-LISP');
var l92=internals.intern('LIST*','COMMON-LISP');
var l93=internals.intern('*SETF-EXPANDERS*');
l88.fvalue=(function(){var FUNC=(function JSCL_USER_SETFTEXT(values,v98,v99){internals.checkArgs(arguments.length-1,2);
var v100=this;
return (function(){return (function(){var v103=v99;
var v104=l89;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v106){switch(arguments.length-1){case 0:v106=l3.value;
;
default:break;
}var v105=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v105=new internals.Cons(arguments[I+1],v105);
var v107=this;
return (function(){var OBJ=v103;
var TMP=OBJ[internals.xstring(v104)]=internals.lisp_to_js(v106);
return TMP===undefined?l3.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v98;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='(SETF_TEXT)';
return FUNC;
})();
l88;
(function(){var v109=new internals.Cons(l86,(function JSCL_USER_NIL(values){var v110=l3.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v110=new internals.Cons(arguments[I+1],v110);
var v111=this;
return (function(){var v113=l90.fvalue(internals.pv,v110,0);
var v114=v113;
return (function(v117,v118,v119,v120){return values(l40.fvalue(internals.pv,v117),v114,l40.fvalue(internals.pv,v118),l92.fvalue(internals.pv,v119,v118,v114),new internals.Cons(v120,v114));
})(l17.fvalue(internals.pv,(function JSCL_USER_NIL(values,v115){internals.checkArgs(arguments.length-1,1);
var v116=this;
return l91.fvalue(values);
}),v114),l91.fvalue(internals.pv),l88,l86);
})();
}));
var v121=new internals.Cons(v109,internals.symbolValue(l93));
return l93.value=v121;
})();
l86;
var l94=internals.intern('INNER-HTML','IIIIKA/WEB');
var l95=internals.make_lisp_string('innerHTML');
l94.fvalue=(function(){var FUNC=(function JSCL_USER_INNERHTML(values,v122){internals.checkArgs(arguments.length-1,1);
var v123=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v122[internals.xstring(l95)];
return TMP===undefined?l3.value:TMP;
})());
})();
});
FUNC.fname='INNER-HTML';
FUNC.docstring="Get/Set `elem' inner HTML by setting innerHTML. ";
return FUNC;
})();
l94;
var l96=internals.intern('(SETF_INNER-HTML)','IIIIKA/WEB');
var l97=internals.make_lisp_string('innerHTML');
l96.fvalue=(function(){var FUNC=(function JSCL_USER_SETFINNERHTML(values,v125,v126){internals.checkArgs(arguments.length-1,2);
var v127=this;
return (function(){return (function(){var v130=v126;
var v131=l97;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v133){switch(arguments.length-1){case 0:v133=l3.value;
;
default:break;
}var v132=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v132=new internals.Cons(arguments[I+1],v132);
var v134=this;
return (function(){var OBJ=v130;
var TMP=OBJ[internals.xstring(v131)]=internals.lisp_to_js(v133);
return TMP===undefined?l3.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v125;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='(SETF_INNER-HTML)';
return FUNC;
})();
l96;
(function(){var v136=new internals.Cons(l94,(function JSCL_USER_NIL(values){var v137=l3.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v137=new internals.Cons(arguments[I+1],v137);
var v138=this;
return (function(){var v140=l90.fvalue(internals.pv,v137,0);
var v141=v140;
return (function(v144,v145,v146,v147){return values(l40.fvalue(internals.pv,v144),v141,l40.fvalue(internals.pv,v145),l92.fvalue(internals.pv,v146,v145,v141),new internals.Cons(v147,v141));
})(l17.fvalue(internals.pv,(function JSCL_USER_NIL(values,v142){internals.checkArgs(arguments.length-1,1);
var v143=this;
return l91.fvalue(values);
}),v141),l91.fvalue(internals.pv),l96,l94);
})();
}));
var v148=new internals.Cons(v136,internals.symbolValue(l93));
return l93.value=v148;
})();
l94;
var l98=internals.intern('CREATE-ELEM','IIIIKA/WEB');
var l99=internals.make_lisp_string('document');
var l100=internals.make_lisp_string('createElement');
l98.fvalue=(function(){var FUNC=(function JSCL_USER_CREATEELEM(values,v149,v150){internals.checkArgs(arguments.length-1,2);
var v151=this;
return (function(){return (function(v153){(function(){var v155=v153;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v157){switch(arguments.length-1){case 0:v157=l3.value;
;
default:break;
}var v156=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v156=new internals.Cons(arguments[I+1],v156);
var v158=this;
return l96.fvalue(values,v157,v153);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v150;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return v153;
})(internals.js_to_lisp(internals.symbolValue(l76)[internals.xstring(l99)][internals.xstring(l100)](internals.lisp_to_js(v149))));
})();
});
FUNC.fname='CREATE-ELEM';
FUNC.docstring='Create <tag>inner-html</tag> like HTML object. ';
return FUNC;
})();
l98;
var l101=internals.intern('APPEND-CHILDREN','IIIIKA/WEB');
var l102=internals.make_lisp_string('appendChild');
l101.fvalue=(function(){var FUNC=(function JSCL_USER_APPENDCHILDREN(values,v159,v160){internals.checkArgs(arguments.length-1,2);
var v161=this;
return (function(){return internals.js_to_lisp(v159[internals.xstring(l102)](internals.lisp_to_js(v160)));
})();
});
FUNC.fname='APPEND-CHILDREN';
return FUNC;
})();
l101;
var l103=internals.intern('ADD-CSS-CLASS','IIIIKA/WEB');
var l104=internals.make_lisp_string('classList');
var l105=internals.make_lisp_string('add');
l103.fvalue=(function(){var FUNC=(function JSCL_USER_ADDCSSCLASS(values,v163,v164){internals.checkArgs(arguments.length-1,2);
var v165=this;
return (function(){return internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v163[internals.xstring(l104)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l105)](internals.lisp_to_js(v164)));
})();
});
FUNC.fname='ADD-CSS-CLASS';
return FUNC;
})();
l103;
var l106=internals.intern('REMOVE-CSS-CLASS','IIIIKA/WEB');
var l107=internals.make_lisp_string('classList');
var l108=internals.make_lisp_string('remove');
l106.fvalue=(function(){var FUNC=(function JSCL_USER_REMOVECSSCLASS(values,v167,v168){internals.checkArgs(arguments.length-1,2);
var v169=this;
return (function(){return internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v167[internals.xstring(l107)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l108)](internals.lisp_to_js(v168)));
})();
});
FUNC.fname='REMOVE-CSS-CLASS';
return FUNC;
})();
l106;
var l109=internals.intern('HAS-CSS-CLASS-P','IIIIKA/WEB');
var l110=internals.make_lisp_string('classList');
var l111=internals.make_lisp_string('contains');
l109.fvalue=(function(){var FUNC=(function JSCL_USER_HASCSSCLASSP(values,v171,v172){internals.checkArgs(arguments.length-1,2);
var v173=this;
return (function(){return internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v171[internals.xstring(l110)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l111)](internals.lisp_to_js(v172)));
})();
});
FUNC.fname='HAS-CSS-CLASS-P';
return FUNC;
})();
l109;
var l112=internals.intern('ATTACH-TOOLTIP','IIIIKA/WEB');
var l113=internals.make_lisp_string('span');
var l114=internals.make_lisp_string('tooltiptext');
var l115=internals.make_lisp_string('classList');
var l116=internals.make_lisp_string('add');
var l117=internals.make_lisp_string('tooltip');
var l118=internals.make_lisp_string('classList');
var l119=internals.make_lisp_string('add');
l112.fvalue=(function(){var FUNC=(function JSCL_USER_ATTACHTOOLTIP(values,v175,v176){internals.checkArgs(arguments.length-1,2);
var v177=this;
return (function(){return (function(v179){internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v179[internals.xstring(l115)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l116)](internals.lisp_to_js(l114)));
internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v175[internals.xstring(l118)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l119)](internals.lisp_to_js(l117)));
return l101.fvalue(values,v175,v179);
})(l98.fvalue(internals.pv,l113,v176));
})();
});
FUNC.fname='ATTACH-TOOLTIP';
return FUNC;
})();
l112;
var l120=internals.intern('HIDE-ELEM','IIIIKA/WEB');
var l121=internals.make_lisp_string('fade-in');
var l122=internals.make_lisp_string('classList');
var l123=internals.make_lisp_string('remove');
var l124=internals.make_lisp_string('fade-out');
var l125=internals.make_lisp_string('classList');
var l126=internals.make_lisp_string('add');
l120.fvalue=(function(){var FUNC=(function JSCL_USER_HIDEELEM(values,v180){internals.checkArgs(arguments.length-1,1);
var v181=this;
return (function(){internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v180[internals.xstring(l122)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l123)](internals.lisp_to_js(l121)));
return internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v180[internals.xstring(l125)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l126)](internals.lisp_to_js(l124)));
})();
});
FUNC.fname='HIDE-ELEM';
return FUNC;
})();
l120;
var l127=internals.intern('SHOW-ELEM','IIIIKA/WEB');
var l128=internals.make_lisp_string('fade-out');
var l129=internals.make_lisp_string('classList');
var l130=internals.make_lisp_string('remove');
var l131=internals.make_lisp_string('fade-in');
var l132=internals.make_lisp_string('classList');
var l133=internals.make_lisp_string('add');
l127.fvalue=(function(){var FUNC=(function JSCL_USER_SHOWELEM(values,v183){internals.checkArgs(arguments.length-1,1);
var v184=this;
return (function(){internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v183[internals.xstring(l129)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l130)](internals.lisp_to_js(l128)));
return internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v183[internals.xstring(l132)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l133)](internals.lisp_to_js(l131)));
})();
});
FUNC.fname='SHOW-ELEM';
return FUNC;
})();
l127;
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
