(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.intern('*PACKAGE*','COMMON-LISP');
var l2=internals.intern('IIIIKA','KEYWORD');
l2.value=l2;
var l3=internals.intern('FIND-PACKAGE-OR-FAIL');
l1.value=l3.fvalue(internals.pv,l2);
var l4=internals.intern('LIST','COMMON-LISP');
var l5=internals.intern('DEFINE-RULE','IIIIKA');
var l6=internals.intern('KATAKANA','KEYWORD');
l6.value=l6;
var l7=internals.intern('NI','KEYWORD');
l7.value=l7;
var l8=internals.intern('NIL','COMMON-LISP');
var l9=internals.QIList(l6,l7,l8);
var l10=internals.intern('MI','KEYWORD');
l10.value=l10;
var l11=internals.QIList(l6,l10,l8);
var l12=internals.intern('HIRAGANA','KEYWORD');
l12.value=l12;
var l13=internals.intern('E','KEYWORD');
l13.value=l13;
var l14=internals.QIList(l12,l13,l8);
var l15=internals.intern('YU','KEYWORD');
l15.value=l15;
var l16=internals.QIList(l12,l15,l8);
var l17=internals.intern('SU','KEYWORD');
l17.value=l17;
var l18=internals.QIList(l12,l17,l8);
var l19=internals.intern('SE','KEYWORD');
l19.value=l19;
var l20=internals.QIList(l12,l19,l8);
var l21=internals.intern('NU','KEYWORD');
l21.value=l21;
var l22=internals.QIList(l12,l21,l8);
var l23=internals.intern('NO','KEYWORD');
l23.value=l23;
var l24=internals.QIList(l12,l23,l8);
var l25=internals.intern('FU','KEYWORD');
l25.value=l25;
var l26=internals.QIList(l12,l25,l8);
var l27=internals.intern('RA','KEYWORD');
l27.value=l27;
var l28=internals.QIList(l12,l27,l8);
var l29=internals.QIList(l12,l17,l8);
var l30=internals.intern('RO','KEYWORD');
l30.value=l30;
var l31=internals.QIList(l12,l30,l8);
var l32=internals.intern('A','KEYWORD');
l32.value=l32;
var l33=internals.QIList(l6,l32,l8);
var l34=internals.QIList(l6,l13,l8);
var l35=internals.intern('O','KEYWORD');
l35.value=l35;
var l36=internals.QIList(l6,l35,l8);
var l37=internals.intern('KA','KEYWORD');
l37.value=l37;
var l38=internals.QIList(l6,l37,l8);
var l39=internals.QIList(l6,l21,l8);
var l40=internals.intern('TI','KEYWORD');
l40.value=l40;
var l41=internals.QIList(l6,l40,l8);
var l42=internals.intern('TO','KEYWORD');
l42.value=l42;
var l43=internals.QIList(l6,l42,l8);
var l44=internals.intern('TA','KEYWORD');
l44.value=l44;
var l45=internals.QIList(l6,l44,l8);
var l46=internals.intern('HA','KEYWORD');
l46.value=l46;
var l47=internals.QIList(l6,l46,l8);
var l48=internals.QIList(l6,l19,l8);
var l49=internals.QIList(l6,l30,l8);
var l50=internals.intern('口字旁','KEYWORD');
l50.value=l50;
var l51=internals.intern('ENGLISH','KEYWORD');
l51.value=l51;
var l52=internals.intern('LOWER-O','KEYWORD');
l52.value=l52;
var l53=internals.QIList(l51,l52,l8);
var l54=internals.intern('女字旁','KEYWORD');
l54.value=l54;
var l55=internals.intern('双耳旁','KEYWORD');
l55.value=l55;
var l56=internals.intern('日字旁','KEYWORD');
l56.value=l56;
var l57=internals.intern('绞丝旁','KEYWORD');
l57.value=l57;
var l58=internals.intern('双点水','KEYWORD');
l58.value=l58;
var l59=internals.intern('三点水','KEYWORD');
l59.value=l59;
var l60=internals.intern('单人旁','KEYWORD');
l60.value=l60;
var l61=internals.intern('I','KEYWORD');
l61.value=l61;
var l62=internals.QIList(l6,l61,l8);
var l63=internals.intern('双人旁','KEYWORD');
l63.value=l63;
var l64=internals.QIList(l6,l40,l8);
var l65=internals.intern('提手旁','KEYWORD');
l65.value=l65;
var l66=internals.intern('KI','KEYWORD');
l66.value=l66;
var l67=internals.QIList(l6,l66,l8);
var l68=internals.intern('王字旁','KEYWORD');
l68.value=l68;
var l69=internals.intern('MO','KEYWORD');
l69.value=l69;
var l70=internals.QIList(l6,l69,l8);
var l71=internals.intern('立刀旁','KEYWORD');
l71.value=l71;
var l72=internals.intern('RI','KEYWORD');
l72.value=l72;
var l73=internals.QIList(l6,l72,l8);
var l74=internals.intern('示字旁','KEYWORD');
l74.value=l74;
var l75=internals.intern('NE','KEYWORD');
l75.value=l75;
var l76=internals.QIList(l6,l75,l8);
var l77=internals.intern('木字旁','KEYWORD');
l77.value=l77;
var l78=internals.intern('HO','KEYWORD');
l78.value=l78;
var l79=internals.QIList(l6,l78,l8);
l5.fvalue(internals.pv,'，',l4.fvalue(internals.pv,','));
l5.fvalue(internals.pv,'、',l4.fvalue(internals.pv,'、'));
l5.fvalue(internals.pv,'。',l4.fvalue(internals.pv,'.'));
l5.fvalue(internals.pv,'？',l4.fvalue(internals.pv,'！'));
l5.fvalue(internals.pv,'（',l4.fvalue(internals.pv,'('));
l5.fvalue(internals.pv,'）',l4.fvalue(internals.pv,')'));
l5.fvalue(internals.pv,'【',l4.fvalue(internals.pv,'['));
l5.fvalue(internals.pv,'】',l4.fvalue(internals.pv,']'));
l5.fvalue(internals.pv,'｛',l4.fvalue(internals.pv,'{'));
l5.fvalue(internals.pv,'｝',l4.fvalue(internals.pv,'}'));
l5.fvalue(internals.pv,'《',l4.fvalue(internals.pv,'》'));
l5.fvalue(internals.pv,'零',l4.fvalue(internals.pv,'0'));
l5.fvalue(internals.pv,'一',l4.fvalue(internals.pv,'-'));
l5.fvalue(internals.pv,'二',l4.fvalue(internals.pv,l9));
l5.fvalue(internals.pv,'三',l4.fvalue(internals.pv,l11));
l5.fvalue(internals.pv,'羊',l4.fvalue(internals.pv,'¥'));
l5.fvalue(internals.pv,'申',l4.fvalue(internals.pv,'φ'));
l5.fvalue(internals.pv,'十',l4.fvalue(internals.pv,'+'));
l5.fvalue(internals.pv,'丫',l4.fvalue(internals.pv,'Y'));
l5.fvalue(internals.pv,'元',l4.fvalue(internals.pv,l14));
l5.fvalue(internals.pv,'中',l4.fvalue(internals.pv,l16));
l5.fvalue(internals.pv,'可',l4.fvalue(internals.pv,l18));
l5.fvalue(internals.pv,'世',l4.fvalue(internals.pv,l20));
l5.fvalue(internals.pv,'奴',l4.fvalue(internals.pv,l22));
l5.fvalue(internals.pv,'的',l4.fvalue(internals.pv,l24));
l5.fvalue(internals.pv,'尔',l4.fvalue(internals.pv,l26));
l5.fvalue(internals.pv,'马',l4.fvalue(internals.pv,l28));
l5.fvalue(internals.pv,'寸',l4.fvalue(internals.pv,l29));
l5.fvalue(internals.pv,'子',l4.fvalue(internals.pv,l31));
l5.fvalue(internals.pv,'乃',l4.fvalue(internals.pv,l31));
l5.fvalue(internals.pv,'丁',l4.fvalue(internals.pv,l33));
l5.fvalue(internals.pv,'工',l4.fvalue(internals.pv,l34));
l5.fvalue(internals.pv,'才',l4.fvalue(internals.pv,l36));
l5.fvalue(internals.pv,'力',l4.fvalue(internals.pv,l38));
l5.fvalue(internals.pv,'刀',l4.fvalue(internals.pv,l38));
l5.fvalue(internals.pv,'又',l4.fvalue(internals.pv,l39));
l5.fvalue(internals.pv,'千',l4.fvalue(internals.pv,l41));
l5.fvalue(internals.pv,'卜',l4.fvalue(internals.pv,l43));
l5.fvalue(internals.pv,'不',l4.fvalue(internals.pv,l43));
l5.fvalue(internals.pv,'夕',l4.fvalue(internals.pv,l45));
l5.fvalue(internals.pv,'八',l4.fvalue(internals.pv,l47));
l5.fvalue(internals.pv,'也',l4.fvalue(internals.pv,l48));
l5.fvalue(internals.pv,'巴',l4.fvalue(internals.pv,l48));
l5.fvalue(internals.pv,'口',l4.fvalue(internals.pv,l49));
l5.fvalue(internals.pv,l50.value,l4.fvalue(internals.pv,l53));
l5.fvalue(internals.pv,l54.value,l4.fvalue(internals.pv,'δ'));
l5.fvalue(internals.pv,'女',l4.fvalue(internals.pv,'δ'));
l5.fvalue(internals.pv,l55.value,l4.fvalue(internals.pv,'β'));
l5.fvalue(internals.pv,'阝',l4.fvalue(internals.pv,'β'));
l5.fvalue(internals.pv,l56.value,l4.fvalue(internals.pv,'θ'));
l5.fvalue(internals.pv,'日',l4.fvalue(internals.pv,'θ'));
l5.fvalue(internals.pv,l57.value,l4.fvalue(internals.pv,'ξ'));
l5.fvalue(internals.pv,'纟',l4.fvalue(internals.pv,'ξ'));
l5.fvalue(internals.pv,l58.value,l4.fvalue(internals.pv,':'));
l5.fvalue(internals.pv,'冫',l4.fvalue(internals.pv,':'));
l5.fvalue(internals.pv,l59.value,l4.fvalue(internals.pv,'Ξ'));
l5.fvalue(internals.pv,'氵',l4.fvalue(internals.pv,'Ξ'));
l5.fvalue(internals.pv,l60.value,l4.fvalue(internals.pv,l62));
l5.fvalue(internals.pv,'亻',l4.fvalue(internals.pv,l62));
l5.fvalue(internals.pv,l63.value,l4.fvalue(internals.pv,l64));
l5.fvalue(internals.pv,'彳',l4.fvalue(internals.pv,l64));
l5.fvalue(internals.pv,l65.value,l4.fvalue(internals.pv,l67));
l5.fvalue(internals.pv,'扌',l4.fvalue(internals.pv,l67));
l5.fvalue(internals.pv,l68.value,l4.fvalue(internals.pv,l70));
l5.fvalue(internals.pv,'𤣩',l4.fvalue(internals.pv,l70));
l5.fvalue(internals.pv,l71.value,l4.fvalue(internals.pv,l73));
l5.fvalue(internals.pv,'刂',l4.fvalue(internals.pv,l73));
l5.fvalue(internals.pv,l74.value,l4.fvalue(internals.pv,l76));
l5.fvalue(internals.pv,'礻',l4.fvalue(internals.pv,l76));
l5.fvalue(internals.pv,l77.value,l4.fvalue(internals.pv,l79));
l5.fvalue(internals.pv,'木',l4.fvalue(internals.pv,l79));
l5.fvalue(internals.pv,'我',l4.fvalue(internals.pv,'チ','ギ'));
l5.fvalue(internals.pv,'儿',l4.fvalue(internals.pv,'ノ','し'));
l5.fvalue(internals.pv,'久',l4.fvalue(internals.pv,'ク','、'));
l5.fvalue(internals.pv,'人',l4.fvalue(internals.pv,'ノ','、'));
l5.fvalue(internals.pv,'大',l4.fvalue(internals.pv,'ナ','、'));
l5.fvalue(internals.pv,'么',l4.fvalue(internals.pv,'ノ','ム'));
l5.fvalue(internals.pv,'山',l4.fvalue(internals.pv,'ι','υ'));
l5.fvalue(internals.pv,'小',l4.fvalue(internals.pv,'·','」','·'));
l5.fvalue(internals.pv,'水',l4.fvalue(internals.pv,'フ','」','く'));
l5.fvalue(internals.pv,'从',l4.fvalue(internals.pv,'人','人'));
l5.fvalue(internals.pv,'对',l4.fvalue(internals.pv,'又','寸'));
l5.fvalue(internals.pv,'云',l4.fvalue(internals.pv,'テ','.'));
l5.fvalue(internals.pv,'天',l4.fvalue(internals.pv,'.','モ'));
l5.fvalue(internals.pv,'无',l4.fvalue(internals.pv,'.','モ'));
l5.fvalue(internals.pv,'好',l4.fvalue(internals.pv,l54.value,'子'));
l5.fvalue(internals.pv,'奶',l4.fvalue(internals.pv,l54.value,'乃'));
l5.fvalue(internals.pv,'材',l4.fvalue(internals.pv,l77.value,'才'));
l5.fvalue(internals.pv,'冰',l4.fvalue(internals.pv,l58.value,'水'));
l5.fvalue(internals.pv,'队',l4.fvalue(internals.pv,l55.value,'人'));
l5.fvalue(internals.pv,'阿',l4.fvalue(internals.pv,l55.value,'可'));
l5.fvalue(internals.pv,'神',l4.fvalue(internals.pv,l74.value,'申'));
l5.fvalue(internals.pv,'阳',l4.fvalue(internals.pv,l55.value,'日'));
l5.fvalue(internals.pv,'红',l4.fvalue(internals.pv,l57.value,'工'));
l5.fvalue(internals.pv,'他',l4.fvalue(internals.pv,l60.value,'也'));
l5.fvalue(internals.pv,'你',l4.fvalue(internals.pv,l60.value,'尔'));
l5.fvalue(internals.pv,'什',l4.fvalue(internals.pv,l60.value,'十'));
l5.fvalue(internals.pv,'仙',l4.fvalue(internals.pv,l60.value,'山'));
l5.fvalue(internals.pv,'行',l4.fvalue(internals.pv,l63.value,'丁'));
l5.fvalue(internals.pv,'打',l4.fvalue(internals.pv,l65.value,'丁'));
l5.fvalue(internals.pv,'咩',l4.fvalue(internals.pv,l50.value,'羊'));
l5.fvalue(internals.pv,'吖',l4.fvalue(internals.pv,l50.value,'丫'));
l5.fvalue(internals.pv,'啊',l4.fvalue(internals.pv,l50.value,'阿'));
l5.fvalue(internals.pv,'吗',l4.fvalue(internals.pv,l50.value,'马'));
l5.fvalue(internals.pv,'加',l4.fvalue(internals.pv,'力',l50.value));
l5.fvalue(internals.pv,'班',l4.fvalue(internals.pv,l68.value,l71.value,l68.value));
l5.fvalue(internals.pv,'为',l4.fvalue(internals.pv,'ゐ'));
l5.fvalue(internals.pv,'什',l4.fvalue(internals.pv,'イ','+'));
l5.fvalue(internals.pv,'别',l4.fvalue(internals.pv,'Я','l','l'));
l5.fvalue(internals.pv,'门',l4.fvalue(internals.pv,'i','コ'));
l5.fvalue(internals.pv,'外',l4.fvalue(internals.pv,'タ','卜'));
l5.fvalue(internals.pv,'汉',l4.fvalue(internals.pv,'シ','マ'));
l5.fvalue(internals.pv,'月',l4.fvalue(internals.pv,'Π'));
l5.fvalue(internals.pv,'湖',l4.fvalue(internals.pv,l59.value,'中','月'));
l5.fvalue(internals.pv,'北',l4.fvalue(internals.pv,'オ','ヒ'));
l5.fvalue(internals.pv,'京',l4.fvalue(internals.pv,',','す',','));
l5.fvalue(internals.pv,'浙',l4.fvalue(internals.pv,l59.value,l65.value,'F'));
l5.fvalue(internals.pv,'江',l4.fvalue(internals.pv,l59.value,'工'));
l5.fvalue(internals.pv,'川',l4.fvalue(internals.pv,'l','l','l'));
l5.fvalue(internals.pv,'南',l4.fvalue(internals.pv,'N','α','η'));
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
