(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.make_lisp_string('IIIIKA');
var l2=internals.intern('CL','KEYWORD');
l2.value=l2;
var l3=internals.intern('NIL','COMMON-LISP');
var l4=internals.QIList(l2,l3);
var l5=internals.intern('%DEFPACKAGE');
var l6=internals.make_lisp_string('name');
var l7=internals.intern('INTERN','COMMON-LISP');
var l8=new internals.Symbol('DEFCHARACTERS');
var l9=new internals.Symbol('DEFRULE');
var l10=new internals.Symbol('IKASU-CHAR');
var l11=new internals.Symbol('IKASU');
var l12=internals.QIList(l8,l9,l10,l11,l3);
var l13=internals.intern('MAPCAR','COMMON-LISP');
var l14=internals.intern('EXPORT','COMMON-LISP');
var l15=internals.intern('IIIIKA','KEYWORD');
l15.value=l15;
var l16=internals.intern('FIND-PACKAGE','COMMON-LISP');
(function(v1){l14.fvalue(internals.pv,l13.fvalue(internals.pv,(function JSCL_USER_NIL(values,v2){internals.checkArgs(arguments.length-1,1);
var v3=this;
return l7.fvalue(values,internals.js_to_lisp((function(){var TMP=v2[internals.xstring(l6)];
return TMP===undefined?l3.value:TMP;
})()),v1);
}),l12),v1);
return v1;
})(l5.fvalue(internals.pv,l1,l4));
l16.fvalue(internals.pv,l15.value);
var l17=internals.intern('*PACKAGE*','COMMON-LISP');
var l18=internals.intern('FIND-PACKAGE-OR-FAIL');
l17.value=l18.fvalue(internals.pv,l15);
l17.value=l18.fvalue(internals.pv,l15);
var l19=internals.intern('MAKE-KEYWORD','IIIIKA');
var l20=internals.intern('T','COMMON-LISP');
var l21=internals.intern('KEYWORD','KEYWORD');
l21.value=l21;
var l22=internals.make_lisp_string('~S fell through etypecase expression.');
var l23=internals.intern('ERROR','COMMON-LISP');
l19.fvalue=(function(){var FUNC=(function JSCL_USER_MAKEKEYWORD(values,v4){internals.checkArgs(arguments.length-1,1);
var v5=this;
return (function(){return (function(v7){return (function(){var X=v7;
return typeof X==='object'&&X!==null&&'length' in X&&X.stringp==1?l20.value:l3.value;
})()!==l3.value?l7.fvalue(values,v4,l21.value):(v7 instanceof internals.Symbol?l20.value:l3.value)!==l3.value?l7.fvalue(values,internals.js_to_lisp((function(){var TMP=v4[internals.xstring(l6)];
return TMP===undefined?l3.value:TMP;
})()),l21.value):l23.fvalue(values,l22,v4);
})(v4);
})();
});
FUNC.fname='MAKE-KEYWORD';
FUNC.docstring='Make keyword (copied from alexandria:make-keyword). ';
return FUNC;
})();
l19;
var l24=internals.intern('PARAM-CASE','IIIIKA');
var l25=internals.intern('STRING','COMMON-LISP');
var l26=internals.intern('CHAR=','COMMON-LISP');
var l27=internals.intern('STRING-UPCASE','COMMON-LISP');
var l28=internals.intern('MAP','COMMON-LISP');
l24.fvalue=(function(){var FUNC=(function JSCL_USER_PARAMCASE(values,v8){internals.checkArgs(arguments.length-1,1);
var v9=this;
return (function(){return l28.fvalue(values,l25,(function JSCL_USER_NIL(values,v11){internals.checkArgs(arguments.length-1,1);
var v12=this;
return l26.fvalue(internals.pv,v11,'_')!==l3.value?'-':v11;
}),l27.fvalue(internals.pv,v8));
})();
});
FUNC.fname='PARAM-CASE';
FUNC.docstring="Make string like `param-case'. (like `str:param-case'). ";
return FUNC;
})();
l24;
var l29=internals.intern('GETHASH+','IIIIKA');
var l30=internals.intern('GETHASH','COMMON-LISP');
l29.fvalue=(function(){var FUNC=(function JSCL_USER_GETHASH(values,v13,v14,v15){internals.checkArgsAtLeast(arguments.length-1,2);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 2:v15=l3.value;
;
default:break;
}var v16=this;
return (function(){return (function(){var X=v13;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})()!==l3.value?l30.fvalue(values,internals.char_to_codepoint(v13),v14,v15):l30.fvalue(values,v13,v14,v15);
})();
});
FUNC.fname='GETHASH+';
FUNC.docstring="For JSCL:\nIf `key' is character, use `char-code' as hash key.\nFor other situation, `gethash*' is equal to `gethash'. ";
return FUNC;
})();
l29;
var l31=internals.intern('(SETF_GETHASH+)','IIIIKA');
var l32=internals.intern('SETHASH');
var l33=internals.intern('VALIDATE-REQVARS');
var l34=internals.intern('GENSYM','COMMON-LISP');
var l35=internals.intern('LIST','COMMON-LISP');
var l36=internals.intern('LIST*','COMMON-LISP');
var l37=internals.intern('*SETF-EXPANDERS*');
l31.fvalue=(function(){var FUNC=(function JSCL_USER_SETFGETHASH(values,v18,v19,v20,v21){internals.checkArgsAtLeast(arguments.length-1,3);
internals.checkArgsAtMost(arguments.length-1,4);
switch(arguments.length-1){case 3:v21=l3.value;
;
default:break;
}var v22=this;
return (function(){return (function(){var X=v19;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})()!==l3.value?(function(){var v25=internals.char_to_codepoint(v19);
var v26=v20;
var v27=l3.value;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v29){switch(arguments.length-1){case 0:v29=l3.value;
;
default:break;
}var v28=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v28=new internals.Cons(arguments[I+1],v28);
var v30=this;
return l32.fvalue(internals.pv,v29,v25,v26),v29;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})():(function(){var v32=v19;
var v33=v20;
var v34=l3.value;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v36){switch(arguments.length-1){case 0:v36=l3.value;
;
default:break;
}var v35=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v35=new internals.Cons(arguments[I+1],v35);
var v37=this;
return l32.fvalue(internals.pv,v36,v32,v33),v36;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='(SETF_GETHASH+)';
return FUNC;
})();
l31;
(function(){var v39=new internals.Cons(l29,(function JSCL_USER_NIL(values){var v40=l3.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v40=new internals.Cons(arguments[I+1],v40);
var v41=this;
return (function(){var v43=l33.fvalue(internals.pv,v40,0);
var v44=v43;
return (function(v47,v48,v49,v50){return values(l35.fvalue(internals.pv,v47),v44,l35.fvalue(internals.pv,v48),l36.fvalue(internals.pv,v49,v48,v44),new internals.Cons(v50,v44));
})(l13.fvalue(internals.pv,(function JSCL_USER_NIL(values,v45){internals.checkArgs(arguments.length-1,1);
var v46=this;
return l34.fvalue(values);
}),v44),l34.fvalue(internals.pv),l31,l29);
})();
}));
var v51=new internals.Cons(v39,internals.symbolValue(l37));
return l37.value=v51;
})();
l29;
l17.value=l18.fvalue(internals.pv,l15);
var l38=internals.intern('*CHARACTER-SETS*','IIIIKA');
var l39=internals.intern('MAKE-HASH-TABLE','COMMON-LISP');
var l40=internals.make_lisp_string('vardoc');
var l41=internals.make_lisp_string('An hashtable for all characters sets. ');
l38.value=l39.fvalue(internals.pv);
(function(){var OBJ=l38;
var TMP=OBJ[internals.xstring(l40)]=internals.lisp_to_js(l41);
return TMP===undefined?l3.value:TMP;
})();
l38;
var l42=internals.intern('MAKE-CHARACTER-SET','IIIIKA');
var l43=internals.intern('FWD','KEYWORD');
l43.value=l43;
var l44=internals.intern('GETF','COMMON-LISP');
var l45=internals.intern('BWD','KEYWORD');
l45.value=l45;
var l46=internals.intern('ENDP','COMMON-LISP');
l42.fvalue=(function(){var FUNC=(function JSCL_USER_MAKECHARACTERSET(values,v52,v53){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v53=l3.value;
;
default:break;
}var v54=this;
return (function(){return (function(v57){return (function(v59){return (function(v60,v61,v62){return (function(){try{var v63=[];
return (function(){var v64=1;
var v65=[];
TBLOOP:while (true){try{switch(v64){case 1:if (l46.fvalue(internals.pv,v62)!==l3.value) (function(){throw new internals.TagNLX(v65,2);
})();
 else l3.value;
(function(v66){v60=internals.car(v66);
v66=internals.cdr(v66);
return v61=v66;
})(internals.car(v62));
v62=internals.cdr(v62);
(function(){var v68=v60;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v70){switch(arguments.length-1){case 0:v70=l3.value;
;
default:break;
}var v69=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v69=new internals.Cons(arguments[I+1],v69);
var v71=this;
return l31.fvalue(values,v70,v60,v57);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v61;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v73=v61;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v75){switch(arguments.length-1){case 0:v75=l3.value;
;
default:break;
}var v74=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v74=new internals.Cons(arguments[I+1],v74);
var v76=this;
return l31.fvalue(values,v75,v61,v59);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v60;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){throw new internals.TagNLX(v65,1);
})();
case 2:(function(){var values=internals.mv;
throw new internals.BlockNLX(v63,l35.fvalue(values,l43.value,v57,l45.value,v59),'NIL');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v65) v64=JUMP.label;
 else throw JUMP;
}}return l3.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v63) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})(l3.value,l3.value,v52);
})((function(v58){return v58!==l3.value?v58:l39.fvalue(internals.pv);
})(l44.fvalue(internals.pv,v53,l45.value)));
})((function(v56){return v56!==l3.value?v56:l39.fvalue(internals.pv);
})(l44.fvalue(internals.pv,v53,l43.value)));
})();
});
FUNC.fname='MAKE-CHARACTER-SET';
FUNC.docstring="Character set with name.\n\nThe `character-alist' should be like\n\n    (:name . char)\n\nExample:\n\n    (:question-mark . #?)\n";
return FUNC;
})();
l42;
var l47=internals.intern('FIND-CHARACTER','IIIIKA');
var l48=internals.intern('NULL','COMMON-LISP');
var l49=internals.intern('LISTP','COMMON-LISP');
var l50=internals.intern('VALIDATE-MAX-ARGS');
var l51=internals.intern('MAPHASH','COMMON-LISP');
l47.fvalue=(function(){var FUNC=(function JSCL_USER_FINDCHARACTER(values,v77){internals.checkArgs(arguments.length-1,1);
var v78=this;
return (function(){return l48.fvalue(internals.pv,v77)!==l3.value?l3.value:l49.fvalue(internals.pv,v77)!==l3.value?(function(){var v81=l33.fvalue(internals.pv,v77,2);
var v82=internals.car(v81);
var v83=internals.car(internals.cdr(v81));
var v84=l50.fvalue(internals.pv,internals.cdr(internals.cdr(v81)));
return (function(v85){return v85!==l3.value?(function(){var X=v83;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})()!==l3.value?(function(v86){return v86!==l3.value?values(v86,l35.fvalue(internals.pv,v82,v86)):l3.value;
})(l29.fvalue(internals.pv,v83,l44.fvalue(internals.pv,v85,l45.value))):(function(v87){return v87!==l3.value?values(v87,l35.fvalue(internals.pv,v82,v83)):l3.value;
})(l29.fvalue(internals.pv,v83,l44.fvalue(internals.pv,v85,l43.value))):l3.value;
})(l29.fvalue(internals.pv,v82,internals.symbolValue(l38)));
})():(function(){var X=v77;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})()!==l3.value?(function(){try{var v88=[];
return l51.fvalue(values,(function JSCL_USER_NIL(values,v89,v90){internals.checkArgs(arguments.length-1,2);
var v91=this;
return (function(v92){return v92!==l3.value?(function(){var values=internals.mv;
throw new internals.BlockNLX(v88,values(v92,l35.fvalue(internals.pv,v89,v92)),'SEARCH');
})():l3.value;
})(l29.fvalue(internals.pv,v77,l44.fvalue(internals.pv,v90,l45.value)));
}),internals.symbolValue(l38));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v88) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})():(function(){try{var v93=[];
return l51.fvalue(values,(function JSCL_USER_NIL(values,v94,v95){internals.checkArgs(arguments.length-1,2);
var v96=this;
return (function(v97){return v97!==l3.value?(function(){var values=internals.mv;
throw new internals.BlockNLX(v93,values(v97,l35.fvalue(internals.pv,v94,v77)),'SEARCH');
})():l3.value;
})(l29.fvalue(internals.pv,v77,l44.fvalue(internals.pv,v95,l43.value)));
}),internals.symbolValue(l38));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v93) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})();
});
FUNC.fname='FIND-CHARACTER';
FUNC.docstring="Find characters in `*character-sets*'.\nReturn values are search-result, (character-setname character-name);\nor `NIL' if could not found.\n\nArguments:\n`search':\n+ explicitly: (:character-set-name :character-name)\n+ explicitly but no character-name: (:character-set-name char)\n+ ambigiously: char or character-name\n\nNote this will only find the EXACTLY the character.\n";
return FUNC;
})();
l47;
l17.value=l18.fvalue(internals.pv,l15);
var l52=internals.intern('ENGLISH','KEYWORD');
l52.value=l52;
var l53=internals.intern('UPPER-Z','KEYWORD');
l53.value=l53;
var l54=internals.intern('UPPER-Y','KEYWORD');
l54.value=l54;
var l55=internals.intern('UPPER-X','KEYWORD');
l55.value=l55;
var l56=internals.intern('UPPER-W','KEYWORD');
l56.value=l56;
var l57=internals.intern('UPPER-V','KEYWORD');
l57.value=l57;
var l58=internals.intern('UPPER-U','KEYWORD');
l58.value=l58;
var l59=internals.intern('UPPER-T','KEYWORD');
l59.value=l59;
var l60=internals.intern('UPPER-S','KEYWORD');
l60.value=l60;
var l61=internals.intern('UPPER-R','KEYWORD');
l61.value=l61;
var l62=internals.intern('UPPER-Q','KEYWORD');
l62.value=l62;
var l63=internals.intern('UPPER-P','KEYWORD');
l63.value=l63;
var l64=internals.intern('UPPER-O','KEYWORD');
l64.value=l64;
var l65=internals.intern('UPPER-N','KEYWORD');
l65.value=l65;
var l66=internals.intern('UPPER-M','KEYWORD');
l66.value=l66;
var l67=internals.intern('UPPER-L','KEYWORD');
l67.value=l67;
var l68=internals.intern('UPPER-K','KEYWORD');
l68.value=l68;
var l69=internals.intern('UPPER-J','KEYWORD');
l69.value=l69;
var l70=internals.intern('UPPER-I','KEYWORD');
l70.value=l70;
var l71=internals.intern('UPPER-H','KEYWORD');
l71.value=l71;
var l72=internals.intern('UPPER-G','KEYWORD');
l72.value=l72;
var l73=internals.intern('UPPER-F','KEYWORD');
l73.value=l73;
var l74=internals.intern('UPPER-E','KEYWORD');
l74.value=l74;
var l75=internals.intern('UPPER-D','KEYWORD');
l75.value=l75;
var l76=internals.intern('UPPER-C','KEYWORD');
l76.value=l76;
var l77=internals.intern('UPPER-B','KEYWORD');
l77.value=l77;
var l78=internals.intern('UPPER-A','KEYWORD');
l78.value=l78;
var l79=internals.intern('LOWER-Z','KEYWORD');
l79.value=l79;
var l80=internals.intern('LOWER-Y','KEYWORD');
l80.value=l80;
var l81=internals.intern('LOWER-X','KEYWORD');
l81.value=l81;
var l82=internals.intern('LOWER-W','KEYWORD');
l82.value=l82;
var l83=internals.intern('LOWER-V','KEYWORD');
l83.value=l83;
var l84=internals.intern('LOWER-U','KEYWORD');
l84.value=l84;
var l85=internals.intern('LOWER-T','KEYWORD');
l85.value=l85;
var l86=internals.intern('LOWER-S','KEYWORD');
l86.value=l86;
var l87=internals.intern('LOWER-R','KEYWORD');
l87.value=l87;
var l88=internals.intern('LOWER-Q','KEYWORD');
l88.value=l88;
var l89=internals.intern('LOWER-P','KEYWORD');
l89.value=l89;
var l90=internals.intern('LOWER-O','KEYWORD');
l90.value=l90;
var l91=internals.intern('LOWER-N','KEYWORD');
l91.value=l91;
var l92=internals.intern('LOWER-M','KEYWORD');
l92.value=l92;
var l93=internals.intern('LOWER-L','KEYWORD');
l93.value=l93;
var l94=internals.intern('LOWER-K','KEYWORD');
l94.value=l94;
var l95=internals.intern('LOWER-J','KEYWORD');
l95.value=l95;
var l96=internals.intern('LOWER-I','KEYWORD');
l96.value=l96;
var l97=internals.intern('LOWER-H','KEYWORD');
l97.value=l97;
var l98=internals.intern('LOWER-G','KEYWORD');
l98.value=l98;
var l99=internals.intern('LOWER-F','KEYWORD');
l99.value=l99;
var l100=internals.intern('LOWER-E','KEYWORD');
l100.value=l100;
var l101=internals.intern('LOWER-D','KEYWORD');
l101.value=l101;
var l102=internals.intern('LOWER-C','KEYWORD');
l102.value=l102;
var l103=internals.intern('LOWER-B','KEYWORD');
l103.value=l103;
var l104=internals.intern('LOWER-A','KEYWORD');
l104.value=l104;
var l105=internals.QIList(internals.QIList(l53,'Z'),internals.QIList(l54,'Y'),internals.QIList(l55,'X'),internals.QIList(l56,'W'),internals.QIList(l57,'V'),internals.QIList(l58,'U'),internals.QIList(l59,'T'),internals.QIList(l60,'S'),internals.QIList(l61,'R'),internals.QIList(l62,'Q'),internals.QIList(l63,'P'),internals.QIList(l64,'O'),internals.QIList(l65,'N'),internals.QIList(l66,'M'),internals.QIList(l67,'L'),internals.QIList(l68,'K'),internals.QIList(l69,'J'),internals.QIList(l70,'I'),internals.QIList(l71,'H'),internals.QIList(l72,'G'),internals.QIList(l73,'F'),internals.QIList(l74,'E'),internals.QIList(l75,'D'),internals.QIList(l76,'C'),internals.QIList(l77,'B'),internals.QIList(l78,'A'),internals.QIList(l79,'z'),internals.QIList(l80,'y'),internals.QIList(l81,'x'),internals.QIList(l82,'w'),internals.QIList(l83,'v'),internals.QIList(l84,'u'),internals.QIList(l85,'t'),internals.QIList(l86,'s'),internals.QIList(l87,'r'),internals.QIList(l88,'q'),internals.QIList(l89,'p'),internals.QIList(l90,'o'),internals.QIList(l91,'n'),internals.QIList(l92,'m'),internals.QIList(l93,'l'),internals.QIList(l94,'k'),internals.QIList(l95,'j'),internals.QIList(l96,'i'),internals.QIList(l97,'h'),internals.QIList(l98,'g'),internals.QIList(l99,'f'),internals.QIList(l100,'e'),internals.QIList(l101,'d'),internals.QIList(l102,'c'),internals.QIList(l103,'b'),internals.QIList(l104,'a'),l3);
(function(){var v99=l52;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v101){switch(arguments.length-1){case 0:v101=l3.value;
;
default:break;
}var v100=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v100=new internals.Cons(arguments[I+1],v100);
var v102=this;
return l31.fvalue(values,v101,l52,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l105,l29.fvalue(internals.pv,l52,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l52;
var l106=internals.intern('NUMBER','KEYWORD');
l106.value=l106;
var l107=internals.intern('NUM-9','KEYWORD');
l107.value=l107;
var l108=internals.intern('NUM-8','KEYWORD');
l108.value=l108;
var l109=internals.intern('NUM-7','KEYWORD');
l109.value=l109;
var l110=internals.intern('NUM-6','KEYWORD');
l110.value=l110;
var l111=internals.intern('NUM-5','KEYWORD');
l111.value=l111;
var l112=internals.intern('NUM-4','KEYWORD');
l112.value=l112;
var l113=internals.intern('NUM-3','KEYWORD');
l113.value=l113;
var l114=internals.intern('NUM-2','KEYWORD');
l114.value=l114;
var l115=internals.intern('NUM-1','KEYWORD');
l115.value=l115;
var l116=internals.QIList(internals.QIList(l107,'9'),internals.QIList(l108,'8'),internals.QIList(l109,'7'),internals.QIList(l110,'6'),internals.QIList(l111,'5'),internals.QIList(l112,'4'),internals.QIList(l113,'3'),internals.QIList(l114,'2'),internals.QIList(l115,'1'),l3);
(function(){var v104=l106;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v106){switch(arguments.length-1){case 0:v106=l3.value;
;
default:break;
}var v105=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v105=new internals.Cons(arguments[I+1],v105);
var v107=this;
return l31.fvalue(values,v106,l106,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l116,l29.fvalue(internals.pv,l106,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l106;
var l117=internals.intern('JAPANESE-SYMBOL','KEYWORD');
l117.value=l117;
var l118=internals.intern('RIGHT-CORNER-BRACKET','KEYWORD');
l118.value=l118;
var l119=internals.intern('LEFT-CORNER-BRACKET','KEYWORD');
l119.value=l119;
var l120=internals.intern('IDEOGRAPHIC-COMMA','KEYWORD');
l120.value=l120;
var l121=internals.QIList(internals.QIList(l118,'」'),internals.QIList(l119,'「'),internals.QIList(l120,'、'),l3);
(function(){var v109=l117;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v111){switch(arguments.length-1){case 0:v111=l3.value;
;
default:break;
}var v110=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v110=new internals.Cons(arguments[I+1],v110);
var v112=this;
return l31.fvalue(values,v111,l117,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l121,l29.fvalue(internals.pv,l117,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l117;
var l122=internals.intern('HIRAGANA','KEYWORD');
l122.value=l122;
var l123=internals.intern('YU','KEYWORD');
l123.value=l123;
var l124=internals.intern('N','KEYWORD');
l124.value=l124;
var l125=internals.intern('WO','KEYWORD');
l125.value=l125;
var l126=internals.intern('WA','KEYWORD');
l126.value=l126;
var l127=internals.intern('RO','KEYWORD');
l127.value=l127;
var l128=internals.intern('RE','KEYWORD');
l128.value=l128;
var l129=internals.intern('RU','KEYWORD');
l129.value=l129;
var l130=internals.intern('RI','KEYWORD');
l130.value=l130;
var l131=internals.intern('RA','KEYWORD');
l131.value=l131;
var l132=internals.intern('MO','KEYWORD');
l132.value=l132;
var l133=internals.intern('ME','KEYWORD');
l133.value=l133;
var l134=internals.intern('MU','KEYWORD');
l134.value=l134;
var l135=internals.intern('MI','KEYWORD');
l135.value=l135;
var l136=internals.intern('MA','KEYWORD');
l136.value=l136;
var l137=internals.intern('PO','KEYWORD');
l137.value=l137;
var l138=internals.intern('PE','KEYWORD');
l138.value=l138;
var l139=internals.intern('PU','KEYWORD');
l139.value=l139;
var l140=internals.intern('PI','KEYWORD');
l140.value=l140;
var l141=internals.intern('PA','KEYWORD');
l141.value=l141;
var l142=internals.intern('BO','KEYWORD');
l142.value=l142;
var l143=internals.intern('BE','KEYWORD');
l143.value=l143;
var l144=internals.intern('BU','KEYWORD');
l144.value=l144;
var l145=internals.intern('BI','KEYWORD');
l145.value=l145;
var l146=internals.intern('BA','KEYWORD');
l146.value=l146;
var l147=internals.intern('HO','KEYWORD');
l147.value=l147;
var l148=internals.intern('HE','KEYWORD');
l148.value=l148;
var l149=internals.intern('FU','KEYWORD');
l149.value=l149;
var l150=internals.intern('HI','KEYWORD');
l150.value=l150;
var l151=internals.intern('HA','KEYWORD');
l151.value=l151;
var l152=internals.intern('NO','KEYWORD');
l152.value=l152;
var l153=internals.intern('NE','KEYWORD');
l153.value=l153;
var l154=internals.intern('NU','KEYWORD');
l154.value=l154;
var l155=internals.intern('NI','KEYWORD');
l155.value=l155;
var l156=internals.intern('NA','KEYWORD');
l156.value=l156;
var l157=internals.intern('DO','KEYWORD');
l157.value=l157;
var l158=internals.intern('DE','KEYWORD');
l158.value=l158;
var l159=internals.intern('DU','KEYWORD');
l159.value=l159;
var l160=internals.intern('DI','KEYWORD');
l160.value=l160;
var l161=internals.intern('DA','KEYWORD');
l161.value=l161;
var l162=internals.intern('TO','KEYWORD');
l162.value=l162;
var l163=internals.intern('TE','KEYWORD');
l163.value=l163;
var l164=internals.intern('TU','KEYWORD');
l164.value=l164;
var l165=internals.intern('TI','KEYWORD');
l165.value=l165;
var l166=internals.intern('TA','KEYWORD');
l166.value=l166;
var l167=internals.intern('ZO','KEYWORD');
l167.value=l167;
var l168=internals.intern('ZE','KEYWORD');
l168.value=l168;
var l169=internals.intern('ZU','KEYWORD');
l169.value=l169;
var l170=internals.intern('JI','KEYWORD');
l170.value=l170;
var l171=internals.intern('ZA','KEYWORD');
l171.value=l171;
var l172=internals.intern('SO','KEYWORD');
l172.value=l172;
var l173=internals.intern('SE','KEYWORD');
l173.value=l173;
var l174=internals.intern('SU','KEYWORD');
l174.value=l174;
var l175=internals.intern('SI','KEYWORD');
l175.value=l175;
var l176=internals.intern('SA','KEYWORD');
l176.value=l176;
var l177=internals.intern('GO','KEYWORD');
l177.value=l177;
var l178=internals.intern('GE','KEYWORD');
l178.value=l178;
var l179=internals.intern('GU','KEYWORD');
l179.value=l179;
var l180=internals.intern('GI','KEYWORD');
l180.value=l180;
var l181=internals.intern('GA','KEYWORD');
l181.value=l181;
var l182=internals.intern('KO','KEYWORD');
l182.value=l182;
var l183=internals.intern('KE','KEYWORD');
l183.value=l183;
var l184=internals.intern('KU','KEYWORD');
l184.value=l184;
var l185=internals.intern('KI','KEYWORD');
l185.value=l185;
var l186=internals.intern('KA','KEYWORD');
l186.value=l186;
var l187=internals.intern('O','KEYWORD');
l187.value=l187;
var l188=internals.intern('E','KEYWORD');
l188.value=l188;
var l189=internals.intern('U','KEYWORD');
l189.value=l189;
var l190=internals.intern('I','KEYWORD');
l190.value=l190;
var l191=internals.intern('A','KEYWORD');
l191.value=l191;
var l192=internals.QIList(internals.QIList(l123,'ゆ'),internals.QIList(l124,'ん'),internals.QIList(l125,'を'),internals.QIList(l126,'わ'),internals.QIList(l127,'ろ'),internals.QIList(l128,'れ'),internals.QIList(l129,'る'),internals.QIList(l130,'り'),internals.QIList(l131,'ら'),internals.QIList(l132,'も'),internals.QIList(l133,'め'),internals.QIList(l134,'む'),internals.QIList(l135,'み'),internals.QIList(l136,'ま'),internals.QIList(l137,'ぽ'),internals.QIList(l138,'ぺ'),internals.QIList(l139,'ぷ'),internals.QIList(l140,'ぴ'),internals.QIList(l141,'ぱ'),internals.QIList(l142,'ぼ'),internals.QIList(l143,'べ'),internals.QIList(l144,'ぶ'),internals.QIList(l145,'び'),internals.QIList(l146,'ば'),internals.QIList(l147,'ほ'),internals.QIList(l148,'へ'),internals.QIList(l149,'ふ'),internals.QIList(l150,'ひ'),internals.QIList(l151,'は'),internals.QIList(l152,'の'),internals.QIList(l153,'ね'),internals.QIList(l154,'ぬ'),internals.QIList(l155,'に'),internals.QIList(l156,'な'),internals.QIList(l157,'ど'),internals.QIList(l158,'で'),internals.QIList(l159,'づ'),internals.QIList(l160,'ぢ'),internals.QIList(l161,'だ'),internals.QIList(l162,'と'),internals.QIList(l163,'て'),internals.QIList(l164,'つ'),internals.QIList(l165,'ち'),internals.QIList(l166,'た'),internals.QIList(l167,'ぞ'),internals.QIList(l168,'ぜ'),internals.QIList(l169,'ず'),internals.QIList(l170,'じ'),internals.QIList(l171,'ざ'),internals.QIList(l172,'そ'),internals.QIList(l173,'せ'),internals.QIList(l174,'す'),internals.QIList(l175,'し'),internals.QIList(l176,'さ'),internals.QIList(l177,'ご'),internals.QIList(l178,'げ'),internals.QIList(l179,'ぐ'),internals.QIList(l180,'ぎ'),internals.QIList(l181,'が'),internals.QIList(l182,'こ'),internals.QIList(l183,'け'),internals.QIList(l184,'く'),internals.QIList(l185,'き'),internals.QIList(l186,'か'),internals.QIList(l187,'お'),internals.QIList(l188,'え'),internals.QIList(l189,'う'),internals.QIList(l190,'い'),internals.QIList(l191,'あ'),l3);
(function(){var v114=l122;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v116){switch(arguments.length-1){case 0:v116=l3.value;
;
default:break;
}var v115=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v115=new internals.Cons(arguments[I+1],v115);
var v117=this;
return l31.fvalue(values,v116,l122,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l192,l29.fvalue(internals.pv,l122,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l122;
var l193=internals.intern('KATAKANA','KEYWORD');
l193.value=l193;
var l194=internals.QIList(internals.QIList(l123,'ユ'),internals.QIList(l124,'ン'),internals.QIList(l125,'ヲ'),internals.QIList(l126,'ワ'),internals.QIList(l127,'ロ'),internals.QIList(l128,'レ'),internals.QIList(l129,'ル'),internals.QIList(l130,'リ'),internals.QIList(l131,'ラ'),internals.QIList(l132,'モ'),internals.QIList(l133,'メ'),internals.QIList(l134,'ム'),internals.QIList(l135,'ミ'),internals.QIList(l136,'マ'),internals.QIList(l137,'ポ'),internals.QIList(l138,'ペ'),internals.QIList(l139,'プ'),internals.QIList(l140,'ピ'),internals.QIList(l141,'パ'),internals.QIList(l142,'ボ'),internals.QIList(l143,'ベ'),internals.QIList(l144,'ブ'),internals.QIList(l145,'ビ'),internals.QIList(l146,'バ'),internals.QIList(l147,'ホ'),internals.QIList(l148,'ヘ'),internals.QIList(l149,'フ'),internals.QIList(l150,'ヒ'),internals.QIList(l151,'ハ'),internals.QIList(l152,'ノ'),internals.QIList(l153,'ネ'),internals.QIList(l154,'ヌ'),internals.QIList(l155,'ニ'),internals.QIList(l156,'ナ'),internals.QIList(l157,'ド'),internals.QIList(l158,'デ'),internals.QIList(l159,'ヅ'),internals.QIList(l160,'ヂ'),internals.QIList(l161,'ダ'),internals.QIList(l162,'ト'),internals.QIList(l163,'テ'),internals.QIList(l164,'ツ'),internals.QIList(l165,'チ'),internals.QIList(l166,'タ'),internals.QIList(l167,'ゾ'),internals.QIList(l168,'ゼ'),internals.QIList(l169,'ズ'),internals.QIList(l170,'ジ'),internals.QIList(l171,'ザ'),internals.QIList(l172,'ソ'),internals.QIList(l173,'セ'),internals.QIList(l174,'ス'),internals.QIList(l175,'シ'),internals.QIList(l176,'サ'),internals.QIList(l177,'ゴ'),internals.QIList(l178,'ゲ'),internals.QIList(l179,'グ'),internals.QIList(l180,'ギ'),internals.QIList(l181,'ガ'),internals.QIList(l182,'コ'),internals.QIList(l183,'ケ'),internals.QIList(l184,'ク'),internals.QIList(l185,'キ'),internals.QIList(l186,'カ'),internals.QIList(l187,'オ'),internals.QIList(l188,'エ'),internals.QIList(l189,'ウ'),internals.QIList(l190,'イ'),internals.QIList(l191,'ア'),l3);
(function(){var v119=l193;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v121){switch(arguments.length-1){case 0:v121=l3.value;
;
default:break;
}var v120=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v120=new internals.Cons(arguments[I+1],v120);
var v122=this;
return l31.fvalue(values,v121,l193,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l194,l29.fvalue(internals.pv,l193,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l193;
var l195=internals.intern('SYMBOLS-1','KEYWORD');
l195.value=l195;
var l196=internals.intern('CIRCUMFLEX-ACCENT','KEYWORD');
l196.value=l196;
var l197=internals.intern('VERTICAL-LINE','KEYWORD');
l197.value=l197;
var l198=internals.intern('CURRENCY-SIGN','KEYWORD');
l198.value=l198;
var l199=internals.intern('MATHEMATICAL-ITALIC-SMALL-F','KEYWORD');
l199.value=l199;
var l200=internals.intern('YEN-SIGN','KEYWORD');
l200.value=l200;
var l201=internals.intern('POUND-SIGN','KEYWORD');
l201.value=l201;
var l202=internals.intern('EURO-SIGN','KEYWORD');
l202.value=l202;
var l203=internals.intern('CENT-SIGN','KEYWORD');
l203.value=l203;
var l204=internals.intern('DOLLAR-SIGN','KEYWORD');
l204.value=l204;
var l205=internals.intern('TILDE','KEYWORD');
l205.value=l205;
var l206=internals.intern('LEFT-RIGHT-DOUBLE-ARROW','KEYWORD');
l206.value=l206;
var l207=internals.intern('RIGHTWARDS-DOUBLE-ARROW','KEYWORD');
l207.value=l207;
var l208=internals.intern('DOWNWARDS-ARROW','KEYWORD');
l208.value=l208;
var l209=internals.intern('UPWARDS-ARROW','KEYWORD');
l209.value=l209;
var l210=internals.intern('RIGHTWARDS-ARROW','KEYWORD');
l210.value=l210;
var l211=internals.intern('LEFTWARDS-ARROW','KEYWORD');
l211.value=l211;
var l212=internals.intern('RIGHT-POINTING-DOUBLE-ANGLE-QUOTATION-MARK','KEYWORD');
l212.value=l212;
var l213=internals.intern('LEFT-POINTING-DOUBLE-ANGLE-QUOTATION-MARK','KEYWORD');
l213.value=l213;
var l214=internals.intern('RIGHT-DOUBLE-ANGLE-BRACKET','KEYWORD');
l214.value=l214;
var l215=internals.intern('LEFT-DOUBLE-ANGLE-BRACKET','KEYWORD');
l215.value=l215;
var l216=internals.intern('GREATER-THAN-SIGN','KEYWORD');
l216.value=l216;
var l217=internals.intern('LESS-THAN-SIGN','KEYWORD');
l217.value=l217;
var l218=internals.intern('LOW-LINE','KEYWORD');
l218.value=l218;
var l219=internals.intern('DOUBLE-LOW-9-QUOTATION-MARK','KEYWORD');
l219.value=l219;
var l220=internals.intern('RIGHT-DOUBLE-QUOTATION-MARK','KEYWORD');
l220.value=l220;
var l221=internals.intern('LEFT-DOUBLE-QUOTATION-MARK','KEYWORD');
l221.value=l221;
var l222=internals.intern('QUOTATION-MARK','KEYWORD');
l222.value=l222;
var l223=internals.intern('HORIZONTAL-ELLIPSIS','KEYWORD');
l223.value=l223;
var l224=internals.intern('MIDDLE-DOT','KEYWORD');
l224.value=l224;
var l225=internals.intern('RIGHT-CURLY-BRACKET','KEYWORD');
l225.value=l225;
var l226=internals.intern('LEFT-CURLY-BRACKET','KEYWORD');
l226.value=l226;
var l227=internals.intern('SOLIDUS','KEYWORD');
l227.value=l227;
var l228=internals.intern('SINGLE-HIGH-REVERSED-9-QUOTATION-MARK','KEYWORD');
l228.value=l228;
var l229=internals.intern('COMMA','KEYWORD');
l229.value=l229;
var l230=internals.intern('RIGHT-SINGLE-QUOTATION-MARK','KEYWORD');
l230.value=l230;
var l231=internals.intern('LEFT-SINGLE-QUOTATION-MARK','KEYWORD');
l231.value=l231;
var l232=internals.intern('APOSTROPHE','KEYWORD');
l232.value=l232;
var l233=internals.intern('COLON','KEYWORD');
l233.value=l233;
var l234=internals.intern('SEMICOLON','KEYWORD');
l234.value=l234;
var l235=internals.intern('RIGHT-SQUARE-BRACKET','KEYWORD');
l235.value=l235;
var l236=internals.intern('LEFT-SQUARE-BRACKET','KEYWORD');
l236.value=l236;
var l237=internals.intern('RIGHT-PARENTHESIS','KEYWORD');
l237.value=l237;
var l238=internals.intern('LEFT-PARENTHESIS','KEYWORD');
l238.value=l238;
var l239=internals.intern('HYPHEN-MINUS','KEYWORD');
l239.value=l239;
var l240=internals.intern('AMPERSAND','KEYWORD');
l240.value=l240;
var l241=internals.intern('NUMBER-SIGN','KEYWORD');
l241.value=l241;
var l242=internals.intern('FULL-STOP','KEYWORD');
l242.value=l242;
var l243=internals.intern('INVERTED-EXCLAMATION-MARK','KEYWORD');
l243.value=l243;
var l244=internals.intern('INVERTED-QUESTION-MARK','KEYWORD');
l244.value=l244;
var l245=internals.intern('EXCLAMATION-MARK','KEYWORD');
l245.value=l245;
var l246=internals.intern('QUESTION-MARK','KEYWORD');
l246.value=l246;
var l247=internals.QIList(internals.QIList(l196,'^'),internals.QIList(l197,'|'),internals.QIList(l198,'¤'),internals.QIList(l199,'𝑓'),internals.QIList(l200,'¥'),internals.QIList(l201,'£'),internals.QIList(l202,'€'),internals.QIList(l203,'¢'),internals.QIList(l204,'$'),internals.QIList(l205,'~'),internals.QIList(l206,'⇔'),internals.QIList(l207,'⇒'),internals.QIList(l208,'↓'),internals.QIList(l209,'↑'),internals.QIList(l210,'→'),internals.QIList(l211,'←'),internals.QIList(l212,'»'),internals.QIList(l213,'«'),internals.QIList(l214,'》'),internals.QIList(l215,'《'),internals.QIList(l216,'>'),internals.QIList(l217,'<'),internals.QIList(l218,'_'),internals.QIList(l219,'„'),internals.QIList(l220,'”'),internals.QIList(l221,'“'),internals.QIList(l222,'"'),internals.QIList(l223,'…'),internals.QIList(l224,'·'),internals.QIList(l225,'}'),internals.QIList(l226,'{'),internals.QIList(l227,'/'),internals.QIList(l228,'‛'),internals.QIList(l229,','),internals.QIList(l230,'’'),internals.QIList(l231,'‘'),internals.QIList(l232,"'"),internals.QIList(l233,':'),internals.QIList(l234,';'),internals.QIList(l235,']'),internals.QIList(l236,'['),internals.QIList(l237,')'),internals.QIList(l238,'('),internals.QIList(l239,'-'),internals.QIList(l240,'&'),internals.QIList(l241,'#'),internals.QIList(l242,'.'),internals.QIList(l229,','),internals.QIList(l243,'¡'),internals.QIList(l244,'¿'),internals.QIList(l245,'!'),internals.QIList(l246,'?'),l3);
(function(){var v124=l195;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v126){switch(arguments.length-1){case 0:v126=l3.value;
;
default:break;
}var v125=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v125=new internals.Cons(arguments[I+1],v125);
var v127=this;
return l31.fvalue(values,v126,l195,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l247,l29.fvalue(internals.pv,l195,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l195;
var l248=internals.intern('SYMBOLS-2','KEYWORD');
l248.value=l248;
(function(){var v129=l248;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v131){switch(arguments.length-1){case 0:v131=l3.value;
;
default:break;
}var v130=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v130=new internals.Cons(arguments[I+1],v130);
var v132=this;
return l31.fvalue(values,v131,l248,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l3,l29.fvalue(internals.pv,l248,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l248;
var l249=internals.intern('SYMBOLS-3','KEYWORD');
l249.value=l249;
var l250=internals.intern('OMEGA','KEYWORD');
l250.value=l250;
var l251=internals.intern('PSI','KEYWORD');
l251.value=l251;
var l252=internals.intern('CHI','KEYWORD');
l252.value=l252;
var l253=internals.intern('PHI','KEYWORD');
l253.value=l253;
var l254=internals.intern('UPSILON','KEYWORD');
l254.value=l254;
var l255=internals.intern('TAU','KEYWORD');
l255.value=l255;
var l256=internals.intern('SIGMA','KEYWORD');
l256.value=l256;
var l257=internals.intern('RHO','KEYWORD');
l257.value=l257;
var l258=internals.intern('OMICRON','KEYWORD');
l258.value=l258;
var l259=internals.intern('XI','KEYWORD');
l259.value=l259;
var l260=internals.intern('LAMBDA','KEYWORD');
l260.value=l260;
var l261=internals.intern('KAPPA','KEYWORD');
l261.value=l261;
var l262=internals.intern('IOTA','KEYWORD');
l262.value=l262;
var l263=internals.intern('THETA','KEYWORD');
l263.value=l263;
var l264=internals.intern('ETA','KEYWORD');
l264.value=l264;
var l265=internals.intern('ZETA','KEYWORD');
l265.value=l265;
var l266=internals.intern('EPSILON','KEYWORD');
l266.value=l266;
var l267=internals.intern('DELTA','KEYWORD');
l267.value=l267;
var l268=internals.intern('GAMMA','KEYWORD');
l268.value=l268;
var l269=internals.intern('BETA','KEYWORD');
l269.value=l269;
var l270=internals.intern('ALPHA','KEYWORD');
l270.value=l270;
var l271=internals.QIList(internals.QIList(l250,'ω'),internals.QIList(l251,'ψ'),internals.QIList(l252,'χ'),internals.QIList(l253,'φ'),internals.QIList(l254,'υ'),internals.QIList(l255,'τ'),internals.QIList(l256,'σ'),internals.QIList(l257,'ρ'),internals.QIList(l140,'π'),internals.QIList(l258,'ο'),internals.QIList(l259,'ξ'),internals.QIList(l154,'ν'),internals.QIList(l134,'μ'),internals.QIList(l260,'λ'),internals.QIList(l261,'κ'),internals.QIList(l262,'ι'),internals.QIList(l263,'θ'),internals.QIList(l264,'η'),internals.QIList(l265,'ζ'),internals.QIList(l266,'ε'),internals.QIList(l267,'δ'),internals.QIList(l268,'γ'),internals.QIList(l269,'β'),internals.QIList(l270,'α'),l3);
(function(){var v134=l249;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v136){switch(arguments.length-1){case 0:v136=l3.value;
;
default:break;
}var v135=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v135=new internals.Cons(arguments[I+1],v135);
var v137=this;
return l31.fvalue(values,v136,l249,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l271,l29.fvalue(internals.pv,l249,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l249;
var l272=internals.intern('SYMBOLS-4','KEYWORD');
l272.value=l272;
var l273=internals.QIList(internals.QIList(l250,'Ω'),internals.QIList(l251,'Ψ'),internals.QIList(l252,'Χ'),internals.QIList(l253,'Φ'),internals.QIList(l254,'Υ'),internals.QIList(l255,'Τ'),internals.QIList(l256,'Σ'),internals.QIList(l257,'Ρ'),internals.QIList(l140,'Π'),internals.QIList(l258,'Ο'),internals.QIList(l259,'Ξ'),internals.QIList(l154,'Ν'),internals.QIList(l134,'Μ'),internals.QIList(l260,'Λ'),internals.QIList(l261,'Κ'),internals.QIList(l262,'Ι'),internals.QIList(l263,'Θ'),internals.QIList(l264,'Η'),internals.QIList(l265,'Ζ'),internals.QIList(l266,'Ε'),internals.QIList(l267,'Δ'),internals.QIList(l268,'Γ'),internals.QIList(l269,'Β'),internals.QIList(l270,'Α'),l3);
(function(){var v139=l272;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v141){switch(arguments.length-1){case 0:v141=l3.value;
;
default:break;
}var v140=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v140=new internals.Cons(arguments[I+1],v140);
var v142=this;
return l31.fvalue(values,v141,l272,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l273,l29.fvalue(internals.pv,l272,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l272;
l17.value=l18.fvalue(internals.pv,l15);
var l274=internals.intern('IIIIKA-ERROR','IIIIKA');
var l275=internals.intern('DIRECT-SUPERCLASSES','KEYWORD');
l275.value=l275;
var l276=internals.intern('!FIND-CLASS');
var l277=internals.intern('DIRECT-SLOTS','KEYWORD');
l277.value=l277;
var l278=internals.intern('NAME','KEYWORD');
l278.value=l278;
var l279=internals.intern('ELEM','IIIIKA');
var l280=internals.intern('INITARGS','KEYWORD');
l280.value=l280;
var l281=internals.intern('ELEM','KEYWORD');
l281.value=l281;
var l282=internals.QIList(l281,l3);
var l283=internals.intern('MSG','IIIIKA');
var l284=internals.intern('MSG','KEYWORD');
l284.value=l284;
var l285=internals.QIList(l284,l3);
var l286=internals.intern('ENSURE-CLASS');
l286.fvalue(internals.pv,l274,l275.value,l35.fvalue(internals.pv,l276.fvalue(internals.pv,l23)),l277.value,l35.fvalue(internals.pv,l35.fvalue(internals.pv,l278.value,l279,l280.value,l282),l35.fvalue(internals.pv,l278.value,l283,l280.value,l285)),l3,l3);
l3.value;
l274;
var l287=internals.intern('UNKNOWN-RULE','IIIIKA');
l286.fvalue(internals.pv,l287,l275.value,l35.fvalue(internals.pv,l276.fvalue(internals.pv,l274)),l277.value,l3.value,l3,l3);
l3.value;
l287;
var l288=internals.intern('INVALID-RULE','IIIIKA');
l286.fvalue(internals.pv,l288,l275.value,l35.fvalue(internals.pv,l276.fvalue(internals.pv,l274)),l277.value,l3.value,l3,l3);
l3.value;
l288;
var l289=internals.intern('*STRICTP*','IIIIKA');
l289.value=l20.value;
l289;
var l290=internals.intern('*DEFAULT-FALLBACK-CHARACTER*','IIIIKA');
var l291=internals.make_lisp_string('ロ');
var l292=internals.make_lisp_string("Default fallback character when `ikasu-char' failed\nto find rule for the input character. ");
l290.value=l291;
(function(){var OBJ=l290;
var TMP=OBJ[internals.xstring(l40)]=internals.lisp_to_js(l292);
return TMP===undefined?l3.value:TMP;
})();
l290;
var l293=internals.intern('*RULE-TABLE*','IIIIKA');
var l294=internals.make_lisp_string("A simplified mapping rule table.\n\nThe rule table should be like:\n\n    {char | keyword} -> ({char | keyword | list})\n\nFROM\n+ `char' chinese word;\n+ `keyword' nickname of the `char',\n  also could be used as defining phrase and shortcuts;\n\nTO\n+ `char' and `keyword' should be another FROM element\n  in `*rule-table*';\n+ `list' should be the character (use `find-character'\n  to index the character)\n\nUse `defrule' and `defrule*' to define the mapping rule.\n");
l293.value=l39.fvalue(internals.pv);
(function(){var OBJ=l293;
var TMP=OBJ[internals.xstring(l40)]=internals.lisp_to_js(l294);
return TMP===undefined?l3.value:TMP;
})();
l293;
var l295=internals.intern('IKASU-CHAR','IIIIKA');
var l296=internals.intern('*HANDLER-BINDINGS*');
var l297=internals.make_lisp_string('message');
var l298=internals.intern('%%ERROR');
var l299=internals.intern('MAKE-STRING-OUTPUT-STREAM','COMMON-LISP');
var l300=internals.intern('OR','COMMON-LISP');
var l301=internals.intern('CHARACTER','COMMON-LISP');
var l302=internals.intern('KEYWORD','COMMON-LISP');
var l303=internals.QIList(l300,l301,l302,l3);
var l304=internals.intern('!TYPEP');
var l305=internals.intern('WRITE-CHAR','COMMON-LISP');
var l306=internals.intern('UNKNOWN-RULE','KEYWORD');
l306.value=l306;
var l307=internals.intern('UNKNOWN-CHAR','KEYWORD');
l307.value=l307;
var l308=internals.intern('GET-OUTPUT-STREAM-STRING','COMMON-LISP');
var l309=internals.intern('SLOT-VALUE','COMMON-LISP');
l295.fvalue=(function(){var FUNC=(function JSCL_USER_IKASUCHAR(values,v143,v144){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v144=internals.symbolValue(l290);
;
default:break;
}var v145=this;
return (function(){return (function(){try{var v147=[];
return (function(v148){return (function(){var v149=1;
var v150=[];
TBLOOP:while (true){try{switch(v149){case 1:(function(v151){return internals.bindSpecialBindings([l296],[v151],(function(){(function(){var v153=new internals.Cons(l287,(function JSCL_USER_NIL(values,v154){internals.checkArgs(arguments.length-1,1);
var v155=this;
v148=v154;
return (function(){throw new internals.TagNLX(v150,2);
})();
}));
var v156=new internals.Cons(v153,internals.symbolValue(l296));
return l296.value=v156;
})();
return (function(){try{return (function(){var values=internals.mv;
throw new internals.BlockNLX(v147,(function(v159){(function(){var v160=(function JSCL_USER_NIL(values,v161){internals.checkArgs(arguments.length-1,1);
var v162=this;
return (function(){return (function(v164){return l304.fvalue(internals.pv,v164,l303)!==l3.value?(function(v165){return v165!==l3.value?v165:(function(v166){return v166!==l3.value?v166:l23.fvalue(values,l287,l281.value,v161,l284.value,l306.value);
})(((function(){var X=v161;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})()!==l3.value?l47.fvalue(internals.pv,v161):l3.value)!==l3.value?l305.fvalue(internals.pv,v161,v159):l3.value);
})(l13.fvalue(internals.pv,v160,l29.fvalue(internals.pv,v161,internals.symbolValue(l293)))):l49.fvalue(internals.pv,v164)!==l3.value?l305.fvalue(values,(function(v167){return v167!==l3.value?v167:l23.fvalue(internals.pv,l287,l281.value,v161,l284.value,l307.value);
})(l47.fvalue(internals.pv,v161)),v159):l23.fvalue(values,l22,v161);
})(v161);
})();
});
return internals.pv(v160(internals.pv,v143),l3.value);
})();
return l308.fvalue(values,v159);
})(l299.fvalue(internals.pv)),'G1200');
})();
}catch (v157){v157=internals.js_to_lisp(v157);
return (internals.isNLX(v157)?l20.value:l3.value)!==l3.value?(function(){throw v157;
})():l298.fvalue(internals.pv,(function(v158){return v158!==l3.value?v158:v157;
})(internals.js_to_lisp((function(){var TMP=v157[internals.xstring(l297)];
return TMP===undefined?l3.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l296));
case 2:(function(){var values=internals.mv;
throw new internals.BlockNLX(v147,(function(v168){return values(v144,l35.fvalue(internals.pv,l309.fvalue(internals.pv,v168,l283),l309.fvalue(internals.pv,v168,l279)));
})(v148),'G1200');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v150) v149=JUMP.label;
 else throw JUMP;
}}return l3.value;
})();
})(l3.value);
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v147) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})();
});
FUNC.fname='IKASU-CHAR';
FUNC.docstring="Make char ikasu by `*rule-table*'.\nReturn an ikasu string. ";
return FUNC;
})();
l295;
var l310=internals.intern('IKASU','IIIIKA');
var l311=internals.intern('WRITE-STRING','COMMON-LISP');
l310.fvalue=(function(){var FUNC=(function JSCL_USER_IKASU(values,v169){internals.checkArgs(arguments.length-1,1);
var v170=this;
return (function(){return (function(v172){return (function(v173){l28.fvalue(internals.pv,l3.value,(function JSCL_USER_NIL(values,v174){internals.checkArgs(arguments.length-1,1);
var v175=this;
return (function(v176){return v176!==l3.value?v176:l26.fvalue(internals.pv,v174,' ');
})(l26.fvalue(internals.pv,v174,'\n'))!==l3.value?v172!==l3.value?l3.value:((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v179){switch(arguments.length-1){case 0:v179=l3.value;
;
default:break;
}var v178=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v178=new internals.Cons(arguments[I+1],v178);
var v180=this;
return v172=v179;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l20.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l305.fvalue(values,' ',v173)):((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v183){switch(arguments.length-1){case 0:v183=l3.value;
;
default:break;
}var v182=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v182=new internals.Cons(arguments[I+1],v182);
var v184=this;
return v172=v183;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l3.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l311.fvalue(values,l295.fvalue(internals.pv,v174),v173));
}),v169);
return l308.fvalue(values,v173);
})(l299.fvalue(internals.pv));
})(l3.value);
})();
});
FUNC.fname='IKASU';
FUNC.docstring="Make `input' ikasu.\nReturn an ikasu output string.\nThe input white spaces will be ignored\nand turned into single white space. ";
return FUNC;
})();
l310;
var l312=internals.intern('DEFINE-RULE','IIIIKA');
var l313=internals.intern('KEYWORDP','COMMON-LISP');
var l314=internals.intern('INVALID-TO-ELEM','KEYWORD');
l314.value=l314;
var l315=internals.intern('WARN','COMMON-LISP');
var l316=internals.intern('LOCKED-FROM','KEYWORD');
l316.value=l316;
l312.fvalue=(function(){var FUNC=(function JSCL_USER_DEFINERULE(values,v185,v186,v187){internals.checkArgsAtLeast(arguments.length-1,2);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 2:v187=internals.symbolValue(l289);
;
default:break;
}var v188=this;
return (function(){(function(v190,v191){return (function(){return (function(){var v193=1;
var v194=[];
TBLOOP:while (true){try{switch(v193){case 1:if (l46.fvalue(internals.pv,v191)!==l3.value) (function(){throw new internals.TagNLX(v194,2);
})();
 else l3.value;
v190=internals.car(v191);
v191=internals.cdr(v191);
if ((function(v195){return v195!==l3.value?v195:(function(v196){return v196!==l3.value?v196:l49.fvalue(internals.pv,v190)!==l3.value?l47.fvalue(internals.pv,v190):l3.value;
})(l313.fvalue(internals.pv,v190));
})((function(){var X=v190;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})())!==l3.value) l3.value;
 else if (v187!==l3.value) l23.fvalue(internals.pv,l288,l281.value,v190,l284.value,l314.value);
 else l315.fvalue(internals.pv,l288,l281.value,v190,l284.value,l314.value);
(function(){throw new internals.TagNLX(v194,1);
})();
case 2:default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v194) v193=JUMP.label;
 else throw JUMP;
}}return l3.value;
})();
})();
})(l3.value,v186);
if (l47.fvalue(internals.pv,v185)!==l3.value) if (v187!==l3.value) l23.fvalue(internals.pv,l288,l281.value,v185,l284.value,l316.value);
 else l315.fvalue(internals.pv,l288,l281.value,v185,l284.value,l316.value);
 else (function(){var v198=v185;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v200){switch(arguments.length-1){case 0:v200=l3.value;
;
default:break;
}var v199=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v199=new internals.Cons(arguments[I+1],v199);
var v201=this;
return l31.fvalue(values,v200,v185,internals.symbolValue(l293));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v186;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return v185;
})();
});
FUNC.fname='DEFINE-RULE';
FUNC.docstring="Define rule for the `from' to `to'.\nReturn values are `from'.\n\nArguments:\n+ `from'   should be {character | keyword}\n  `from'   should not be character;\n+ `to'     should be ({character | keyword | list})\n+ `strict' raise error/warn when:\n  + `from' is invalid ---> invalid-from-rule\n  + `to'   is invalid ---> invalid-to-rule\n";
return FUNC;
})();
l312;
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
