(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.make_lisp_string('IIIIKA/WEB');
var l2=internals.intern('CL','KEYWORD');
l2.value=l2;
var l3=internals.intern('NIL','COMMON-LISP');
var l4=internals.QIList(l2,l3);
var l5=internals.intern('%DEFPACKAGE');
var l6=internals.make_lisp_string('name');
var l7=internals.intern('INTERN','COMMON-LISP');
var l8=new internals.Symbol('*DEFAULT-LANGUAGE*');
var l9=new internals.Symbol('*LANGUAGE*');
var l10=new internals.Symbol('DEFTRANSLATION');
var l11=new internals.Symbol('DEFINE-BYNAME-ADJ');
var l12=new internals.Symbol('DEFINE-BYNAME-NOUN');
var l13=new internals.Symbol('GET-BYNAME');
var l14=new internals.Symbol('GET-BYNAME-ADJ');
var l15=new internals.Symbol('GET-BYNAME-NOUN');
var l16=internals.QIList(l8,l9,l10,l11,l12,l13,l14,l15,l3);
var l17=internals.intern('MAPCAR','COMMON-LISP');
var l18=internals.intern('EXPORT','COMMON-LISP');
var l19=internals.intern('IIIIKA/WEB','KEYWORD');
l19.value=l19;
var l20=internals.intern('FIND-PACKAGE','COMMON-LISP');
(function(v1){l18.fvalue(internals.pv,l17.fvalue(internals.pv,(function JSCL_USER_NIL(values,v2){internals.checkArgs(arguments.length-1,1);
var v3=this;
return l7.fvalue(values,internals.js_to_lisp((function(){var TMP=v2[internals.xstring(l6)];
return TMP===undefined?l3.value:TMP;
})()),v1);
}),l16),v1);
return v1;
})(l5.fvalue(internals.pv,l1,l4));
l20.fvalue(internals.pv,l19.value);
var l21=internals.intern('*PACKAGE*','COMMON-LISP');
var l22=internals.intern('FIND-PACKAGE-OR-FAIL');
l21.value=l22.fvalue(internals.pv,l19);
l21.value=l22.fvalue(internals.pv,l19);
var l23=internals.intern('JS-LIKE-CASE','IIIIKA/WEB');
var l24=internals.intern('MAKE-STRING-OUTPUT-STREAM','COMMON-LISP');
var l25=internals.intern('CHAR=','COMMON-LISP');
var l26=internals.intern('T','COMMON-LISP');
var l27=internals.intern('WRITE-CHAR','COMMON-LISP');
var l28=internals.intern('MAP','COMMON-LISP');
var l29=internals.intern('GET-OUTPUT-STREAM-STRING','COMMON-LISP');
l23.fvalue=(function(){var FUNC=(function JSCL_USER_JSLIKECASE(values,v4){internals.checkArgs(arguments.length-1,1);
var v5=this;
return (function(){return (function(v7){(function(v8){return l28.fvalue(internals.pv,l3.value,(function JSCL_USER_NIL(values,v9){internals.checkArgs(arguments.length-1,1);
var v10=this;
return l25.fvalue(internals.pv,'-',v9)!==l3.value?(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v13){switch(arguments.length-1){case 0:v13=l3.value;
;
default:break;
}var v12=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v12=new internals.Cons(arguments[I+1],v12);
var v14=this;
return v8=v13;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l26.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})():v8!==l3.value?(l27.fvalue(internals.pv,internals.safe_char_upcase(v9),v7),(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v17){switch(arguments.length-1){case 0:v17=l3.value;
;
default:break;
}var v16=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v16=new internals.Cons(arguments[I+1],v16);
var v18=this;
return v8=v17;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l3.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})()):l27.fvalue(values,internals.safe_char_downcase(v9),v7);
}),v4);
})(l3.value);
return l29.fvalue(values,v7);
})(l24.fvalue(internals.pv));
})();
});
FUNC.fname='JS-LIKE-CASE';
FUNC.docstring='Trun a-like-string to aLikeString. ';
return FUNC;
})();
l23;
var l30=internals.intern('GETHASH*','IIIIKA/WEB');
var l31=internals.intern('ENDP','COMMON-LISP');
var l32=internals.intern('HASH-TABLE-P','COMMON-LISP');
var l33=internals.intern('FIRST','COMMON-LISP');
var l34=internals.intern('GETHASH','COMMON-LISP');
var l35=internals.intern('REST','COMMON-LISP');
l30.fvalue=(function(){var FUNC=(function JSCL_USER_GETHASH(values,v20){internals.checkArgsAtLeast(arguments.length-1,1);
var v19=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v19=new internals.Cons(arguments[I+1],v19);
var v21=this;
return (function(){return l31.fvalue(internals.pv,v19)!==l3.value?v20:l32.fvalue(internals.pv,v20)!==l3.value?(function(){var F=internals.symbolFunction(l30);
var ARGS=[values,l34.fvalue(internals.pv,l33.fvalue(internals.pv,v19),v20)];
var TAIL=l35.fvalue(internals.pv,v19);
while (TAIL!=l3.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})():l3.value;
})();
});
FUNC.fname='GETHASH*';
FUNC.docstring="Get nested `hash-table' value by unpacking the `keys'. ";
return FUNC;
})();
l30;
var l36=internals.intern('LIST->ARRAY','IIIIKA/WEB');
var l37=internals.intern('VECTOR','COMMON-LISP');
var l38=internals.intern('IDENTITY','COMMON-LISP');
l36.fvalue=(function(){var FUNC=(function JSCL_USER_LISTARRAY(values,v23){internals.checkArgs(arguments.length-1,1);
var v24=this;
return (function(){return l28.fvalue(values,l37,internals.symbolFunction(l38),v23);
})();
});
FUNC.fname='LIST->ARRAY';
return FUNC;
})();
l36;
var l39=internals.intern('ARRAY->LIST','IIIIKA/WEB');
var l40=internals.intern('LIST','COMMON-LISP');
l39.fvalue=(function(){var FUNC=(function JSCL_USER_ARRAYLIST(values,v26){internals.checkArgs(arguments.length-1,1);
var v27=this;
return (function(){return l28.fvalue(values,l40,internals.symbolFunction(l38),v26);
})();
});
FUNC.fname='ARRAY->LIST';
return FUNC;
})();
l39;
l21.value=l22.fvalue(internals.pv,l19);
var l41=internals.intern('*DEFAULT-LANGUAGE*','IIIIKA/WEB');
var l42=internals.intern('CN-ZH','KEYWORD');
l42.value=l42;
var l43=internals.make_lisp_string('vardoc');
var l44=internals.make_lisp_string('Default UI language. ');
l41.value=l42.value;
(function(){var OBJ=l41;
var TMP=OBJ[internals.xstring(l43)]=internals.lisp_to_js(l44);
return TMP===undefined?l3.value:TMP;
})();
l41;
var l45=internals.intern('*LANGUAGE*','IIIIKA/WEB');
var l46=internals.make_lisp_string("The UI language.\n\nBy default, the language is `*default-language*'.\nPossible options:\n+ `:en'\n+ `:cn-zh'\n+ ... (translation contribute is wanted)\n\nTo contribute translations, use `deftranslation'\nmacro for defining the translations. ");
l45.value=l42.value;
(function(){var OBJ=l45;
var TMP=OBJ[internals.xstring(l43)]=internals.lisp_to_js(l46);
return TMP===undefined?l3.value:TMP;
})();
l45;
var l47=internals.intern('*COMMON-MESSAGE*','IIIIKA/WEB');
var l48=internals.intern('MAKE-HASH-TABLE','COMMON-LISP');
var l49=internals.make_lisp_string("The common message goes here.\n\nUse `deftranslation'. ");
l47.value=l48.fvalue(internals.pv);
(function(){var OBJ=l47;
var TMP=OBJ[internals.xstring(l43)]=internals.lisp_to_js(l49);
return TMP===undefined?l3.value:TMP;
})();
l47;
var l50=internals.intern('*BYNAME*','IIIIKA/WEB');
var l51=internals.make_lisp_string("The general CommonMsg/Byname Table.\n\nThe hash table is like:\n\n    language -> [adj, noun]\n\nwhere `adj' and `noun' is an array.\n\nUse `define-byname-adj' and `define-byname-noun' to\nsets the byname tags.\n\nNote: please refer to `scripts/splat3-gen.lisp' and\n`scripts/splat3_CNzh_unicode.json'.\n\nCredit: Jeanny's repo*.\n*: https://github.com/Leanny/splat3");
l50.value=l48.fvalue(internals.pv);
(function(){var OBJ=l50;
var TMP=OBJ[internals.xstring(l43)]=internals.lisp_to_js(l51);
return TMP===undefined?l3.value:TMP;
})();
l50;
var l52=internals.intern('GETUI','IIIIKA/WEB');
var l53=internals.make_lisp_string('~C');
var l54=internals.intern('FORMAT','COMMON-LISP');
var l55=internals.make_lisp_string('ロロロ');
var l56=internals.intern('LISTP','COMMON-LISP');
var l57=internals.intern('WRITE-STRING','COMMON-LISP');
l52.fvalue=(function(){var FUNC=(function JSCL_USER_GETUI(values,v29,v30){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v30=internals.symbolValue(l45);
;
default:break;
}var v31=this;
return (function(){return (function(v38){return l56.fvalue(internals.pv,v29)!==l3.value?(function(v39){(function(v40,v41){return (function(){return (function(){var v43=1;
var v44=[];
TBLOOP:while (true){try{switch(v43){case 1:if (l31.fvalue(internals.pv,v41)!==l3.value) (function(){throw new internals.TagNLX(v44,2);
})();
 else l3.value;
v40=internals.car(v41);
v41=internals.cdr(v41);
l57.fvalue(internals.pv,v38(internals.pv,v40),v39);
l27.fvalue(internals.pv,' ',v39);
(function(){throw new internals.TagNLX(v44,1);
})();
case 2:default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v44) v43=JUMP.label;
 else throw JUMP;
}}return l3.value;
})();
})();
})(l3.value,v29);
return l29.fvalue(values,v39);
})(l24.fvalue(internals.pv)):v38(values,v29);
})((function JSCL_USER_NIL(values,v33){internals.checkArgs(arguments.length-1,1);
var v34=this;
return (function(){return (function(){var X=v33;
return typeof X==='object'&&X!==null&&'length' in X&&X.stringp==1?l26.value:l3.value;
})()!==l3.value?v33:(function(){var X=v33;
return typeof X=='string'&&(X.length==1||X.length==2)?l26.value:l3.value;
})()!==l3.value?l54.fvalue(values,l3.value,l53,v33):(function(v36){return v36!==l3.value?v36:(function(v37){return v37!==l3.value?v37:l55;
})(l30.fvalue(internals.pv,internals.symbolValue(l47),internals.symbolValue(l41),v33));
})(l30.fvalue(internals.pv,internals.symbolValue(l47),v30,v33));
})();
}));
})();
});
FUNC.fname='GETUI';
FUNC.docstring="Get UI message for `language'.\n\nIf `ui' is not known to `language',\nwill fallback to `*default-language*'.\nIf `*default-language*' fails to render `ui',\nwill render `ui' as `ロロロ'. (Katakana RO, RO, RO)\n\nNote: why `ロロロ'?\nNormally if computer fails to render the character,\nit will render white square `□'. So in chinese,\nwe are calling it `口' (kǒu, mouse, 嘴). To render it\nusing Splatoon fonts, using Katakana RO character. ";
return FUNC;
})();
l52;
var l58=internals.intern('ENSURE-BYNAME-SLOT','IIIIKA/WEB');
var l59=internals.intern('MAKE-ARRAY','COMMON-LISP');
var l60=internals.intern('ASET');
var l61=internals.intern('ADJUSTABLE','KEYWORD');
l61.value=l61;
var l62=internals.intern('FILL-POINTER','KEYWORD');
l62.value=l62;
var l63=internals.intern('SETHASH');
l58.fvalue=(function(){var FUNC=(function JSCL_USER_ENSUREBYNAMESLOT(values,v45){internals.checkArgs(arguments.length-1,1);
var v46=this;
return (function(){return l34.fvalue(internals.pv,v45,internals.symbolValue(l50))!==l3.value?l3.value:(function(v48){(function(){var v50=v48;
var v51=0;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v53){switch(arguments.length-1){case 0:v53=l3.value;
;
default:break;
}var v52=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v52=new internals.Cons(arguments[I+1],v52);
var v54=this;
return l60.fvalue(values,v50,v51,v53);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l59.fvalue(values,0,l61.value,l26.value,l62.value,0);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v56=v48;
var v57=1;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v59){switch(arguments.length-1){case 0:v59=l3.value;
;
default:break;
}var v58=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v58=new internals.Cons(arguments[I+1],v58);
var v60=this;
return l60.fvalue(values,v56,v57,v59);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l59.fvalue(values,0,l61.value,l26.value,l62.value,0);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return (function(){var v62=v45;
var v63=internals.symbolValue(l50);
var v64=l3.value;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v66){switch(arguments.length-1){case 0:v66=l3.value;
;
default:break;
}var v65=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v65=new internals.Cons(arguments[I+1],v65);
var v67=this;
return l63.fvalue(internals.pv,v66,v62,v63),v66;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v48;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})(l59.fvalue(internals.pv,2));
})();
});
FUNC.fname='ENSURE-BYNAME-SLOT';
FUNC.docstring='Ensure the existance of byname [adj, noun] structure. ';
return FUNC;
})();
l58;
var l64=internals.intern('GET-BYNAME--AREF','IIIIKA/WEB');
var l65=internals.intern('AREF','COMMON-LISP');
var l66=internals.intern('LENGTH','COMMON-LISP');
var l67=internals.intern('MOD','COMMON-LISP');
var l68=internals.intern('RANDOM','COMMON-LISP');
l64.fvalue=(function(){var FUNC=(function JSCL_USER_GETBYNAMEAREF(values,v68,v69,v70){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v69=l3.value;
;
case 2:v70=internals.symbolValue(l45);
;
default:break;
}var v71=this;
return (function(){return (function(){var v74=l65.fvalue(internals.pv,(function(v75){return v75!==l3.value?v75:l34.fvalue(internals.pv,internals.symbolValue(l41),internals.symbolValue(l50));
})(l34.fvalue(internals.pv,v70,internals.symbolValue(l50))),v68);
var v76=v69!==l3.value?l67.fvalue(internals.pv,v69,l66.fvalue(internals.pv,v74)):l68.fvalue(internals.pv,l66.fvalue(internals.pv,v74));
return values(l65.fvalue(internals.pv,v74,v76),v76);
})();
})();
});
FUNC.fname='GET-BYNAME--AREF';
FUNC.docstring="Get tag of `id' for byname with `aref'.\nReturn values are tag, id of tag.\n\nIf `id' is `NIL', will return random `id'. ";
return FUNC;
})();
l64;
var l69=internals.intern('GET-BYNAME','IIIIKA/WEB');
var l70=internals.intern('CONS','COMMON-LISP');
var l71=internals.intern('VALUES-LIST','COMMON-LISP');
l69.fvalue=(function(){var FUNC=(function JSCL_USER_GETBYNAME(values,v77,v78,v79){internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 0:v77=l3.value;
;
case 1:v78=l3.value;
;
case 2:v79=internals.symbolValue(l45);
;
default:break;
}var v80=this;
return (function(){return l71.fvalue(values,l17.fvalue(internals.pv,internals.symbolFunction(l70),(function(){var FUNC=internals.symbolFunction(l40);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l64.fvalue(values,0,v77,v79);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})(),(function(){var FUNC=internals.symbolFunction(l40);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l64.fvalue(values,1,v78,v79);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})()));
})();
});
FUNC.fname='GET-BYNAME';
FUNC.docstring="Get Byname as cons.\nReturn values are (adj . noun), (adj-id . noun-id).\n\nIf `adj' or `noun' is `NIL', return a random `adj' or `noun';\nor `adj' or `noun' should be the index. ";
return FUNC;
})();
l69;
l21.value=l22.fvalue(internals.pv,l19);
var l72=internals.intern('*SELF*','IIIIKA/WEB');
var l73=internals.make_lisp_string('vardoc');
var l74=internals.make_lisp_string('Used for self reference. ');
if ((l72.value!==undefined?l26.value:l3.value)!==l3.value) l3.value;
 else l72.value=l3.value;
(function(){var OBJ=l72;
var TMP=OBJ[internals.xstring(l73)]=internals.lisp_to_js(l74);
return TMP===undefined?l3.value:TMP;
})();
l72;
var l75=internals.intern('SET-TIME-OUT','IIIIKA/WEB');
var l76=internals.intern('*ROOT*');
var l77=internals.make_lisp_string('setTimeout');
l75.fvalue=(function(){var FUNC=(function JSCL_USER_SETTIMEOUT(values,v82,v83){internals.checkArgs(arguments.length-1,2);
var v84=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l76)[internals.xstring(l77)](internals.lisp_to_js(v83),internals.lisp_to_js(v82)));
})();
});
FUNC.fname='SET-TIME-OUT';
FUNC.docstring="setTimeout(fn, delay)\n\nArgument:\n`delay' seconds;\n`fn'    function;";
return FUNC;
})();
l75;
var l78=internals.intern('ADD-EVENT-LISTENER','IIIIKA/WEB');
var l79=internals.intern('KEYWORDP','COMMON-LISP');
var l80=internals.make_lisp_string('addEventListener');
l78.fvalue=(function(){var FUNC=(function JSCL_USER_ADDEVENTLISTENER(values,v86,v87,v88){internals.checkArgs(arguments.length-1,3);
var v89=this;
return (function(){return internals.js_to_lisp(v86[internals.xstring(l80)](internals.lisp_to_js(l79.fvalue(internals.pv,v87)!==l3.value?l23.fvalue(internals.pv,internals.js_to_lisp((function(){var TMP=v87[internals.xstring(l6)];
return TMP===undefined?l3.value:TMP;
})())):v87),internals.lisp_to_js(v88)));
})();
});
FUNC.fname='ADD-EVENT-LISTENER';
FUNC.docstring="elem.addEventListener(type, fn)\n\nArgument:\n`type' could be\n    {string | keyword}\nif is `keyword', turn it into js-like string first.\n`fn' should be function";
return FUNC;
})();
l78;
var l81=internals.intern('GET-ELEM-BY-ID','IIIIKA/WEB');
var l82=internals.make_lisp_string('document');
var l83=internals.make_lisp_string('getElementById');
l81.fvalue=(function(){var FUNC=(function JSCL_USER_GETELEMBYID(values,v91){internals.checkArgs(arguments.length-1,1);
var v92=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l76)[internals.xstring(l82)][internals.xstring(l83)](internals.lisp_to_js(v91)));
})();
});
FUNC.fname='GET-ELEM-BY-ID';
FUNC.docstring="Get element by `id'.\nReturn HTML element or `NIL' if could not get. ";
return FUNC;
})();
l81;
var l84=internals.intern('TEXT','IIIIKA/WEB');
var l85=internals.make_lisp_string('innerText');
l84.fvalue=(function(){var FUNC=(function JSCL_USER_TEXT(values,v94){internals.checkArgs(arguments.length-1,1);
var v95=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v94[internals.xstring(l85)];
return TMP===undefined?l3.value:TMP;
})());
})();
});
FUNC.fname='TEXT';
FUNC.docstring="Get/Set `elem' text by setting innerText. ";
return FUNC;
})();
l84;
var l86=internals.intern('(SETF_TEXT)','IIIIKA/WEB');
var l87=internals.make_lisp_string('innerText');
var l88=internals.intern('VALIDATE-REQVARS');
var l89=internals.intern('GENSYM','COMMON-LISP');
var l90=internals.intern('LIST*','COMMON-LISP');
var l91=internals.intern('*SETF-EXPANDERS*');
l86.fvalue=(function(){var FUNC=(function JSCL_USER_SETFTEXT(values,v97,v98){internals.checkArgs(arguments.length-1,2);
var v99=this;
return (function(){return (function(){var v102=v98;
var v103=l87;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v105){switch(arguments.length-1){case 0:v105=l3.value;
;
default:break;
}var v104=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v104=new internals.Cons(arguments[I+1],v104);
var v106=this;
return (function(){var OBJ=v102;
var TMP=OBJ[internals.xstring(v103)]=internals.lisp_to_js(v105);
return TMP===undefined?l3.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v97;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='(SETF_TEXT)';
return FUNC;
})();
l86;
(function(){var v108=new internals.Cons(l84,(function JSCL_USER_NIL(values){var v109=l3.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v109=new internals.Cons(arguments[I+1],v109);
var v110=this;
return (function(){var v112=l88.fvalue(internals.pv,v109,0);
var v113=v112;
return (function(v116,v117,v118,v119){return values(l40.fvalue(internals.pv,v116),v113,l40.fvalue(internals.pv,v117),l90.fvalue(internals.pv,v118,v117,v113),new internals.Cons(v119,v113));
})(l17.fvalue(internals.pv,(function JSCL_USER_NIL(values,v114){internals.checkArgs(arguments.length-1,1);
var v115=this;
return l89.fvalue(values);
}),v113),l89.fvalue(internals.pv),l86,l84);
})();
}));
var v120=new internals.Cons(v108,internals.symbolValue(l91));
return l91.value=v120;
})();
l84;
var l92=internals.intern('INNER-HTML','IIIIKA/WEB');
var l93=internals.make_lisp_string('innerHTML');
l92.fvalue=(function(){var FUNC=(function JSCL_USER_INNERHTML(values,v121){internals.checkArgs(arguments.length-1,1);
var v122=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v121[internals.xstring(l93)];
return TMP===undefined?l3.value:TMP;
})());
})();
});
FUNC.fname='INNER-HTML';
FUNC.docstring="Get/Set `elem' inner HTML by setting innerHTML. ";
return FUNC;
})();
l92;
var l94=internals.intern('(SETF_INNER-HTML)','IIIIKA/WEB');
var l95=internals.make_lisp_string('innerHTML');
l94.fvalue=(function(){var FUNC=(function JSCL_USER_SETFINNERHTML(values,v124,v125){internals.checkArgs(arguments.length-1,2);
var v126=this;
return (function(){return (function(){var v129=v125;
var v130=l95;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v132){switch(arguments.length-1){case 0:v132=l3.value;
;
default:break;
}var v131=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v131=new internals.Cons(arguments[I+1],v131);
var v133=this;
return (function(){var OBJ=v129;
var TMP=OBJ[internals.xstring(v130)]=internals.lisp_to_js(v132);
return TMP===undefined?l3.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v124;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='(SETF_INNER-HTML)';
return FUNC;
})();
l94;
(function(){var v135=new internals.Cons(l92,(function JSCL_USER_NIL(values){var v136=l3.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v136=new internals.Cons(arguments[I+1],v136);
var v137=this;
return (function(){var v139=l88.fvalue(internals.pv,v136,0);
var v140=v139;
return (function(v143,v144,v145,v146){return values(l40.fvalue(internals.pv,v143),v140,l40.fvalue(internals.pv,v144),l90.fvalue(internals.pv,v145,v144,v140),new internals.Cons(v146,v140));
})(l17.fvalue(internals.pv,(function JSCL_USER_NIL(values,v141){internals.checkArgs(arguments.length-1,1);
var v142=this;
return l89.fvalue(values);
}),v140),l89.fvalue(internals.pv),l94,l92);
})();
}));
var v147=new internals.Cons(v135,internals.symbolValue(l91));
return l91.value=v147;
})();
l92;
var l96=internals.intern('CREATE-ELEM','IIIIKA/WEB');
var l97=internals.make_lisp_string('document');
var l98=internals.make_lisp_string('createElement');
l96.fvalue=(function(){var FUNC=(function JSCL_USER_CREATEELEM(values,v148,v149){internals.checkArgs(arguments.length-1,2);
var v150=this;
return (function(){return (function(v152){(function(){var v154=v152;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v156){switch(arguments.length-1){case 0:v156=l3.value;
;
default:break;
}var v155=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v155=new internals.Cons(arguments[I+1],v155);
var v157=this;
return l94.fvalue(values,v156,v152);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v149;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return v152;
})(internals.js_to_lisp(internals.symbolValue(l76)[internals.xstring(l97)][internals.xstring(l98)](internals.lisp_to_js(v148))));
})();
});
FUNC.fname='CREATE-ELEM';
FUNC.docstring='Create <tag>inner-html</tag> like HTML object. ';
return FUNC;
})();
l96;
var l99=internals.intern('APPEND-CHILDREN','IIIIKA/WEB');
var l100=internals.make_lisp_string('appendChild');
l99.fvalue=(function(){var FUNC=(function JSCL_USER_APPENDCHILDREN(values,v158,v159){internals.checkArgs(arguments.length-1,2);
var v160=this;
return (function(){return internals.js_to_lisp(v158[internals.xstring(l100)](internals.lisp_to_js(v159)));
})();
});
FUNC.fname='APPEND-CHILDREN';
return FUNC;
})();
l99;
var l101=internals.intern('ADD-CSS-CLASS','IIIIKA/WEB');
var l102=internals.make_lisp_string('classList');
var l103=internals.make_lisp_string('add');
l101.fvalue=(function(){var FUNC=(function JSCL_USER_ADDCSSCLASS(values,v162,v163){internals.checkArgs(arguments.length-1,2);
var v164=this;
return (function(){return internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v162[internals.xstring(l102)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l103)](internals.lisp_to_js(v163)));
})();
});
FUNC.fname='ADD-CSS-CLASS';
return FUNC;
})();
l101;
var l104=internals.intern('REMOVE-CSS-CLASS','IIIIKA/WEB');
var l105=internals.make_lisp_string('classList');
var l106=internals.make_lisp_string('remove');
l104.fvalue=(function(){var FUNC=(function JSCL_USER_REMOVECSSCLASS(values,v166,v167){internals.checkArgs(arguments.length-1,2);
var v168=this;
return (function(){return internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v166[internals.xstring(l105)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l106)](internals.lisp_to_js(v167)));
})();
});
FUNC.fname='REMOVE-CSS-CLASS';
return FUNC;
})();
l104;
var l107=internals.intern('ATTACH-TOOLTIP','IIIIKA/WEB');
var l108=internals.make_lisp_string('span');
var l109=internals.make_lisp_string('tooltiptext');
var l110=internals.make_lisp_string('classList');
var l111=internals.make_lisp_string('add');
var l112=internals.make_lisp_string('tooltip');
var l113=internals.make_lisp_string('classList');
var l114=internals.make_lisp_string('add');
l107.fvalue=(function(){var FUNC=(function JSCL_USER_ATTACHTOOLTIP(values,v170,v171){internals.checkArgs(arguments.length-1,2);
var v172=this;
return (function(){return (function(v174){internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v174[internals.xstring(l110)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l111)](internals.lisp_to_js(l109)));
internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v170[internals.xstring(l113)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l114)](internals.lisp_to_js(l112)));
return l99.fvalue(values,v170,v174);
})(l96.fvalue(internals.pv,l108,v171));
})();
});
FUNC.fname='ATTACH-TOOLTIP';
return FUNC;
})();
l107;
var l115=internals.intern('HIDE-ELEM','IIIIKA/WEB');
var l116=internals.make_lisp_string('fade-in');
var l117=internals.make_lisp_string('classList');
var l118=internals.make_lisp_string('remove');
var l119=internals.make_lisp_string('fade-out');
var l120=internals.make_lisp_string('classList');
var l121=internals.make_lisp_string('add');
l115.fvalue=(function(){var FUNC=(function JSCL_USER_HIDEELEM(values,v175){internals.checkArgs(arguments.length-1,1);
var v176=this;
return (function(){internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v175[internals.xstring(l117)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l118)](internals.lisp_to_js(l116)));
return internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v175[internals.xstring(l120)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l121)](internals.lisp_to_js(l119)));
})();
});
FUNC.fname='HIDE-ELEM';
return FUNC;
})();
l115;
var l122=internals.intern('SHOW-ELEM','IIIIKA/WEB');
var l123=internals.make_lisp_string('fade-out');
var l124=internals.make_lisp_string('classList');
var l125=internals.make_lisp_string('remove');
var l126=internals.make_lisp_string('fade-in');
var l127=internals.make_lisp_string('classList');
var l128=internals.make_lisp_string('add');
l122.fvalue=(function(){var FUNC=(function JSCL_USER_SHOWELEM(values,v178){internals.checkArgs(arguments.length-1,1);
var v179=this;
return (function(){internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v178[internals.xstring(l124)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l125)](internals.lisp_to_js(l123)));
return internals.js_to_lisp(internals.js_to_lisp((function(){var TMP=v178[internals.xstring(l127)];
return TMP===undefined?l3.value:TMP;
})())[internals.xstring(l128)](internals.lisp_to_js(l126)));
})();
});
FUNC.fname='SHOW-ELEM';
return FUNC;
})();
l122;
var l129=internals.intern('QUERY','IIIIKA/WEB');
var l130=internals.intern('TITLE','KEYWORD');
l130.value=l130;
var l131=internals.intern('QUERY','KEYWORD');
l131.value=l131;
var l132=internals.intern('HINT','KEYWORD');
l132.value=l132;
var l133=internals.intern('CALLBACK','KEYWORD');
l133.value=l133;
var l134=internals.intern('CANCEL-CALLBACK','KEYWORD');
l134.value=l134;
var l135=internals.make_lisp_string('query-title');
var l136=internals.make_lisp_string('query-message');
var l137=internals.make_lisp_string('query-input');
var l138=internals.make_lisp_string('query-confirm');
var l139=internals.make_lisp_string('query-cancel');
var l140=internals.make_lisp_string('value');
var l141=internals.make_lisp_string('');
var l142=internals.make_lisp_string('placeholder');
var l143=internals.intern('CONFIRM','KEYWORD');
l143.value=l143;
var l144=internals.intern('CANCEL','KEYWORD');
l144.value=l144;
var l145=internals.make_lisp_string('click');
var l146=internals.make_lisp_string('mask');
var l147=internals.make_lisp_string('query');
var l148=internals.make_lisp_string('click');
var l149=internals.make_lisp_string('value');
var l150=internals.make_lisp_string('mask');
var l151=internals.make_lisp_string('query');
var l152=internals.make_lisp_string('mask');
var l153=internals.make_lisp_string('query');
l129.fvalue=(function(){var FUNC=(function JSCL_USER_QUERY(values,v181){internals.checkArgsAtLeast(arguments.length-1,1);
var v182;
var v183;
var v184;
var v185;
var I;
for (I=1;I<arguments.length-1;I+=2)if (arguments[I+1]===l130.value) {v182=arguments[I+1+1];
break;
}if (I==arguments.length-1) v182=l52.fvalue(internals.pv,l131.value);
for (I=1;I<arguments.length-1;I+=2)if (arguments[I+1]===l132.value) {v183=arguments[I+1+1];
break;
}if (I==arguments.length-1) v183=l52.fvalue(internals.pv,l132.value);
for (I=1;I<arguments.length-1;I+=2)if (arguments[I+1]===l133.value) {v184=arguments[I+1+1];
break;
}if (I==arguments.length-1) v184=internals.symbolFunction(l38);
for (I=1;I<arguments.length-1;I+=2)if (arguments[I+1]===l134.value) {v185=arguments[I+1+1];
break;
}if (I==arguments.length-1) v185=(function JSCL_USER_NIL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v186=this;
return l3.value;
});
var START=1;
if ((arguments.length-1-START)%2==1) throw 'Odd number of keyword arguments.';
for (I=START;I<arguments.length-1;I+=2)if (arguments[I+1]!==l130.value&&arguments[I+1]!==l132.value&&arguments[I+1]!==l133.value&&arguments[I+1]!==l134.value) throw 'Unknown keyword argument '+arguments[I+1]['name'];
var v187=this;
return (function(){(function(){var v190=l81.fvalue(internals.pv,l135);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v192){switch(arguments.length-1){case 0:v192=l3.value;
;
default:break;
}var v191=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v191=new internals.Cons(arguments[I+1],v191);
var v193=this;
return l86.fvalue(values,v192,l81.fvalue(internals.pv,l135));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v182;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v195=l81.fvalue(internals.pv,l136);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v197){switch(arguments.length-1){case 0:v197=l3.value;
;
default:break;
}var v196=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v196=new internals.Cons(arguments[I+1],v196);
var v198=this;
return l86.fvalue(values,v197,l81.fvalue(internals.pv,l136));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v181;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return (function(v199,v200,v201){(function(){var v203=v199;
var v204=l140;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v206){switch(arguments.length-1){case 0:v206=l3.value;
;
default:break;
}var v205=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v205=new internals.Cons(arguments[I+1],v205);
var v207=this;
return (function(){var OBJ=v203;
var TMP=OBJ[internals.xstring(v204)]=internals.lisp_to_js(v206);
return TMP===undefined?l3.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l141;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v209=v199;
var v210=l142;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v212){switch(arguments.length-1){case 0:v212=l3.value;
;
default:break;
}var v211=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v211=new internals.Cons(arguments[I+1],v211);
var v213=this;
return (function(){var OBJ=v209;
var TMP=OBJ[internals.xstring(v210)]=internals.lisp_to_js(v212);
return TMP===undefined?l3.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v183;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v215=v200;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v217){switch(arguments.length-1){case 0:v217=l3.value;
;
default:break;
}var v216=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v216=new internals.Cons(arguments[I+1],v216);
var v218=this;
return l86.fvalue(values,v217,v200);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l52.fvalue(values,l143.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v220=v201;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v222){switch(arguments.length-1){case 0:v222=l3.value;
;
default:break;
}var v221=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v221=new internals.Cons(arguments[I+1],v221);
var v223=this;
return l86.fvalue(values,v222,v201);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l52.fvalue(values,l144.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v224=[];
try{var v225=v201;
var v226=v225;
l72.stack.push(l72.value);
v224.push(l72);
l72.value=v226;
return l78.fvalue(internals.pv,v225,l145,(function JSCL_USER_NIL(values,v227){internals.checkArgs(arguments.length-1,1);
var v228=this;
(function(){var F=v185;
return (typeof F==='function'?F:F.fvalue)(internals.pv);
})();
l115.fvalue(internals.pv,l81.fvalue(internals.pv,l146));
return l115.fvalue(values,l81.fvalue(internals.pv,l147));
}));
}finally{v224.forEach((function(S){S.value=S.stack.pop();
}));
}})();
(function(){var v229=[];
try{var v230=v200;
var v231=v230;
l72.stack.push(l72.value);
v229.push(l72);
l72.value=v231;
return l78.fvalue(internals.pv,v230,l148,(function JSCL_USER_NIL(values,v232){internals.checkArgs(arguments.length-1,1);
var v233=this;
(function(){var F=v184;
return (typeof F==='function'?F:F.fvalue)(internals.pv,internals.js_to_lisp((function(){var TMP=v199[internals.xstring(l149)];
return TMP===undefined?l3.value:TMP;
})()));
})();
l115.fvalue(internals.pv,l81.fvalue(internals.pv,l150));
return l115.fvalue(values,l81.fvalue(internals.pv,l151));
}));
}finally{v229.forEach((function(S){S.value=S.stack.pop();
}));
}})();
l122.fvalue(internals.pv,l81.fvalue(internals.pv,l152));
return l122.fvalue(values,l81.fvalue(internals.pv,l153));
})(l81.fvalue(internals.pv,l137),l81.fvalue(internals.pv,l138),l81.fvalue(internals.pv,l139));
})();
});
FUNC.fname='QUERY';
FUNC.docstring='Query input with prompt. ';
return FUNC;
})();
l129;
var l154=internals.intern('ALERT','IIIIKA/WEB');
var l155=internals.intern('ALERT-TITLE','KEYWORD');
l155.value=l155;
var l156=internals.intern('BUTTON','KEYWORD');
l156.value=l156;
var l157=internals.make_lisp_string('alert-title');
var l158=internals.make_lisp_string('alert-content');
var l159=internals.make_lisp_string('alert-button');
var l160=internals.make_lisp_string('mask');
var l161=internals.make_lisp_string('alert');
l154.fvalue=(function(){var FUNC=(function JSCL_USER_ALERT(values,v234){internals.checkArgsAtLeast(arguments.length-1,1);
var v235;
var v236;
var I;
for (I=1;I<arguments.length-1;I+=2)if (arguments[I+1]===l130.value) {v235=arguments[I+1+1];
break;
}if (I==arguments.length-1) v235=l52.fvalue(internals.pv,l155.value);
for (I=1;I<arguments.length-1;I+=2)if (arguments[I+1]===l156.value) {v236=arguments[I+1+1];
break;
}if (I==arguments.length-1) v236=l52.fvalue(internals.pv,l143.value);
var START=1;
if ((arguments.length-1-START)%2==1) throw 'Odd number of keyword arguments.';
for (I=START;I<arguments.length-1;I+=2)if (arguments[I+1]!==l130.value&&arguments[I+1]!==l156.value) throw 'Unknown keyword argument '+arguments[I+1]['name'];
var v237=this;
return (function(){(function(){var v240=l81.fvalue(internals.pv,l157);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v242){switch(arguments.length-1){case 0:v242=l3.value;
;
default:break;
}var v241=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v241=new internals.Cons(arguments[I+1],v241);
var v243=this;
return l86.fvalue(values,v242,l81.fvalue(internals.pv,l157));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v235;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v245=l81.fvalue(internals.pv,l158);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v247){switch(arguments.length-1){case 0:v247=l3.value;
;
default:break;
}var v246=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v246=new internals.Cons(arguments[I+1],v246);
var v248=this;
return l86.fvalue(values,v247,l81.fvalue(internals.pv,l158));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v234;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v250=l81.fvalue(internals.pv,l159);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v252){switch(arguments.length-1){case 0:v252=l3.value;
;
default:break;
}var v251=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v251=new internals.Cons(arguments[I+1],v251);
var v253=this;
return l86.fvalue(values,v252,l81.fvalue(internals.pv,l159));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v236;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l122.fvalue(internals.pv,l81.fvalue(internals.pv,l160));
return l122.fvalue(values,l81.fvalue(internals.pv,l161));
})();
});
FUNC.fname='ALERT';
FUNC.docstring='Popup alert. ';
return FUNC;
})();
l154;
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
