(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.intern('*PACKAGE*','COMMON-LISP');
var l2=internals.intern('IIIIKA/WEB','KEYWORD');
l2.value=l2;
var l3=internals.intern('FIND-PACKAGE-OR-FAIL');
l1.value=l3.fvalue(internals.pv,l2);
var l4=internals.intern('BYNAME-SELECT','IIIIKA/WEB');
var l5=internals.make_lisp_string('byname-select-title');
var l6=internals.intern('GET-ELEM-BY-ID','IIIIKA/WEB');
var l7=internals.intern('NIL','COMMON-LISP');
var l8=internals.intern('(SETF_TEXT)','IIIIKA/WEB');
var l9=internals.intern('BYNAME','KEYWORD');
l9.value=l9;
var l10=internals.intern('LIST','COMMON-LISP');
var l11=internals.intern('GETUI','IIIIKA/WEB');
var l12=internals.make_lisp_string('byname-select-message');
var l13=internals.intern('CLICK','KEYWORD');
l13.value=l13;
var l14=internals.intern('TO','KEYWORD');
l14.value=l14;
var l15=internals.intern('CHOOSE','KEYWORD');
l15.value=l15;
var l16=internals.make_lisp_string('byname-select-list');
var l17=internals.intern('(SETF_INNER-HTML)','IIIIKA/WEB');
var l18=internals.make_lisp_string('');
var l19=internals.make_lisp_string('li');
var l20=internals.intern('CREATE-ELEM','IIIIKA/WEB');
var l21=internals.intern('*SELF*','IIIIKA/WEB');
var l22=internals.make_lisp_string('click');
var l23=internals.intern('ADJ','KEYWORD');
l23.value=l23;
var l24=internals.intern('T','COMMON-LISP');
var l25=internals.make_lisp_string('byname-adj');
var l26=internals.make_lisp_string('byname-noun');
var l27=internals.make_lisp_string('mask');
var l28=internals.intern('HIDE-ELEM','IIIIKA/WEB');
var l29=internals.make_lisp_string('byname-select');
var l30=internals.intern('ADD-EVENT-LISTENER','IIIIKA/WEB');
var l31=internals.make_lisp_string('appendChild');
var l32=internals.intern('*LANGUAGE*','IIIIKA/WEB');
var l33=internals.intern('*BYNAME*','IIIIKA/WEB');
var l34=internals.intern('GETHASH','COMMON-LISP');
var l35=internals.intern('AREF','COMMON-LISP');
var l36=internals.intern('MAP','COMMON-LISP');
var l37=internals.make_lisp_string('mask');
var l38=internals.intern('SHOW-ELEM','IIIIKA/WEB');
var l39=internals.make_lisp_string('byname-select');
l4.fvalue=(function(){var FUNC=(function JSCL_USER_BYNAMESELECT(values,v1){internals.checkArgs(arguments.length-1,1);
var v2=this;
return (function(){(function(){var v5=l6.fvalue(internals.pv,l5);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v7){switch(arguments.length-1){case 0:v7=l7.value;
;
default:break;
}var v6=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v6=new internals.Cons(arguments[I+1],v6);
var v8=this;
return l8.fvalue(values,v7,l6.fvalue(internals.pv,l5));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l10.fvalue(internals.pv,l9.value,v1));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v10=l6.fvalue(internals.pv,l12);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v12){switch(arguments.length-1){case 0:v12=l7.value;
;
default:break;
}var v11=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v11=new internals.Cons(arguments[I+1],v11);
var v13=this;
return l8.fvalue(values,v12,l6.fvalue(internals.pv,l12));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l10.fvalue(internals.pv,l13.value,l14.value,l15.value,l9.value,v1));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(v14){(function(){var v16=v14;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v18){switch(arguments.length-1){case 0:v18=l7.value;
;
default:break;
}var v17=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v17=new internals.Cons(arguments[I+1],v17);
var v19=this;
return l17.fvalue(values,v18,v14);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return l36.fvalue(internals.pv,l7.value,(function JSCL_USER_NIL(values,v20){internals.checkArgs(arguments.length-1,1);
var v21=this;
return (function(v22){(function(){var v23=[];
try{var v24=v22;
var v25=v24;
l21.stack.push(l21.value);
v23.push(l21);
l21.value=v25;
return l30.fvalue(internals.pv,v24,l22,(function JSCL_USER_NIL(values,v26){internals.checkArgs(arguments.length-1,1);
var v27=this;
(function(){var v29=l6.fvalue(internals.pv,(v1===l23.value?l24.value:l7.value)!==l7.value?l25:l26);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v31){switch(arguments.length-1){case 0:v31=l7.value;
;
default:break;
}var v30=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v30=new internals.Cons(arguments[I+1],v30);
var v32=this;
return l8.fvalue(values,v31,l6.fvalue(internals.pv,(v1===l23.value?l24.value:l7.value)!==l7.value?l25:l26));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v20;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l27));
return l28.fvalue(values,l6.fvalue(internals.pv,l29));
}));
}finally{v23.forEach((function(S){S.value=S.stack.pop();
}));
}})();
return internals.js_to_lisp(v14[internals.xstring(l31)](internals.lisp_to_js(v22)));
})(l20.fvalue(internals.pv,l19,v20));
}),l35.fvalue(internals.pv,l34.fvalue(internals.pv,internals.symbolValue(l32),internals.symbolValue(l33)),(v1===l23.value?l24.value:l7.value)!==l7.value?0:1));
})(l6.fvalue(internals.pv,l16));
l38.fvalue(internals.pv,l6.fvalue(internals.pv,l37));
return l38.fvalue(values,l6.fvalue(internals.pv,l39));
})();
});
FUNC.fname='BYNAME-SELECT';
FUNC.docstring='Popup byname-select. ';
return FUNC;
})();
l4;
var l40=internals.intern('MAIN','IIIIKA/WEB');
var l41=internals.intern('USAGE','KEYWORD');
l41.value=l41;
var l42=internals.intern('TITLE','KEYWORD');
l42.value=l42;
var l43=internals.intern('NAME','KEYWORD');
l43.value=l43;
var l44=internals.intern('HINT','KEYWORD');
l44.value=l44;
var l45=internals.intern('CALLBACK','KEYWORD');
l45.value=l45;
var l46=internals.make_lisp_string('name');
var l47=internals.intern('IKASU','IIIIKA');
var l48=internals.intern('QUERY','IIIIKA/WEB');
var l49=internals.make_lisp_string('name');
var l50=internals.make_lisp_string('click');
var l51=internals.make_lisp_string('detail');
var l52=internals.make_lisp_string('byname-adj');
var l53=internals.intern('CN-ZH','KEYWORD');
l53.value=l53;
var l54=internals.intern('GET-BYNAME--AREF','IIIIKA/WEB');
var l55=internals.make_lisp_string('detail');
var l56=internals.intern('NOUN','KEYWORD');
l56.value=l56;
var l57=internals.make_lisp_string('byname-noun');
var l58=internals.make_lisp_string('byname-adj');
var l59=internals.make_lisp_string('click');
var l60=internals.make_lisp_string('byname-noun');
var l61=internals.make_lisp_string('click');
var l62=internals.intern('SORRY','KEYWORD');
l62.value=l62;
var l63=internals.intern('BADGE','KEYWORD');
l63.value=l63;
var l64=internals.intern('*-IS-WORKING','KEYWORD');
l64.value=l64;
var l65=internals.QIList(l62,l63,l64,l7);
var l66=internals.intern('ALERT','IIIIKA/WEB');
var l67=internals.make_lisp_string('badge-1');
var l68=internals.make_lisp_string('click');
var l69=internals.make_lisp_string('badge-2');
var l70=internals.make_lisp_string('click');
var l71=internals.make_lisp_string('badge-3');
var l72=internals.make_lisp_string('click');
var l73=internals.make_lisp_string('alert-button');
var l74=internals.make_lisp_string('click');
var l75=internals.make_lisp_string('alert');
var l76=internals.make_lisp_string('mask');
var l77=internals.make_lisp_string('byname-select-cancel');
var l78=internals.make_lisp_string('click');
var l79=internals.make_lisp_string('byname-select');
var l80=internals.make_lisp_string('mask');
var l81=internals.make_lisp_string('iiiika');
var l82=internals.make_lisp_string('click');
l40.fvalue=(function(){var FUNC=(function JSCL_USER_MAIN(values){internals.checkArgsAtMost(arguments.length-1,0);
var v33=this;
return (function(){(function(v45){return l30.fvalue(internals.pv,l6.fvalue(internals.pv,l49),l50,v45);
})((function JSCL_USER_NIL(values,v35){internals.checkArgs(arguments.length-1,1);
var v36=this;
return (function(){return l48.fvalue(values,l11.fvalue(internals.pv,l41.value),l42.value,l11.fvalue(internals.pv,l43.value),l44.value,l11.fvalue(internals.pv,l43.value),l45.value,(function JSCL_USER_NIL(values,v38){internals.checkArgs(arguments.length-1,1);
var v39=this;
return (function(){var v41=l6.fvalue(internals.pv,l46);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v43){switch(arguments.length-1){case 0:v43=l7.value;
;
default:break;
}var v42=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v42=new internals.Cons(arguments[I+1],v42);
var v44=this;
return l8.fvalue(values,v43,l6.fvalue(internals.pv,l46));
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l47.fvalue(values,v38);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
}));
})();
}));
(function(v62,v63){l30.fvalue(internals.pv,l6.fvalue(internals.pv,l58),l59,v62);
l30.fvalue(internals.pv,l6.fvalue(internals.pv,l60),l61,v63);
v62(internals.pv);
return v63(internals.pv);
})((function JSCL_USER_NIL(values,v46){internals.checkArgsAtMost(arguments.length-1,1);
switch(arguments.length-1){case 0:v46=l7.value;
;
default:break;
}var v47=this;
return (function(){return (v46!==l7.value?(function(){var x1=internals.js_to_lisp((function(){var TMP=v46[internals.xstring(l51)];
return TMP===undefined?l7.value:TMP;
})());
if (typeof x1!='number') throw 'Not a number!';
return x1==2?l24.value:l7.value;
})():l7.value)!==l7.value?l4.fvalue(values,l23.value):(function(){var v50=l6.fvalue(internals.pv,l52);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v52){switch(arguments.length-1){case 0:v52=l7.value;
;
default:break;
}var v51=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v51=new internals.Cons(arguments[I+1],v51);
var v53=this;
return l8.fvalue(values,v52,l6.fvalue(internals.pv,l52));
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l54.fvalue(values,0,l7.value,l53.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
}),(function JSCL_USER_NIL(values,v54){internals.checkArgsAtMost(arguments.length-1,1);
switch(arguments.length-1){case 0:v54=l7.value;
;
default:break;
}var v55=this;
return (function(){return (v54!==l7.value?(function(){var x1=internals.js_to_lisp((function(){var TMP=v54[internals.xstring(l55)];
return TMP===undefined?l7.value:TMP;
})());
if (typeof x1!='number') throw 'Not a number!';
return x1==2?l24.value:l7.value;
})():l7.value)!==l7.value?l4.fvalue(values,l56.value):(function(){var v58=l6.fvalue(internals.pv,l57);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v60){switch(arguments.length-1){case 0:v60=l7.value;
;
default:break;
}var v59=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v59=new internals.Cons(arguments[I+1],v59);
var v61=this;
return l8.fvalue(values,v60,l6.fvalue(internals.pv,l57));
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l54.fvalue(values,1,l7.value,l53.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
}));
(function(v67){l30.fvalue(internals.pv,l6.fvalue(internals.pv,l67),l68,v67);
l30.fvalue(internals.pv,l6.fvalue(internals.pv,l69),l70,v67);
return l30.fvalue(internals.pv,l6.fvalue(internals.pv,l71),l72,v67);
})((function JSCL_USER_NIL(values,v64){internals.checkArgs(arguments.length-1,1);
var v65=this;
return (function(){return l66.fvalue(values,l11.fvalue(internals.pv,l65));
})();
}));
(function(){var v68=[];
try{var v69=l6.fvalue(internals.pv,l73);
var v70=v69;
l21.stack.push(l21.value);
v68.push(l21);
l21.value=v70;
return l30.fvalue(internals.pv,v69,l74,(function JSCL_USER_NIL(values,v71){internals.checkArgs(arguments.length-1,1);
var v72=this;
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l75));
return l28.fvalue(values,l6.fvalue(internals.pv,l76));
}));
}finally{v68.forEach((function(S){S.value=S.stack.pop();
}));
}})();
(function(){var v73=[];
try{var v74=l6.fvalue(internals.pv,l77);
var v75=v74;
l21.stack.push(l21.value);
v73.push(l21);
l21.value=v75;
return l30.fvalue(internals.pv,v74,l78,(function JSCL_USER_NIL(values,v76){internals.checkArgs(arguments.length-1,1);
var v77=this;
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l79));
return l28.fvalue(values,l6.fvalue(internals.pv,l80));
}));
}finally{v73.forEach((function(S){S.value=S.stack.pop();
}));
}})();
return (function(){var v78=[];
try{var v79=l6.fvalue(internals.pv,l81);
var v80=v79;
l21.stack.push(l21.value);
v78.push(l21);
l21.value=v80;
return l30.fvalue(values,v79,l82,(function JSCL_USER_NIL(values,v81){internals.checkArgs(arguments.length-1,1);
var v82=this;
return l7.value;
}));
}finally{v78.forEach((function(S){S.value=S.stack.pop();
}));
}})();
})();
});
FUNC.fname='MAIN';
FUNC.docstring='Binds all the events to front-end UI. ';
return FUNC;
})();
l40;
l40.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
