(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.make_lisp_string('IIIIKA');
var l2=internals.intern('CL','KEYWORD');
l2.value=l2;
var l3=internals.intern('NIL','COMMON-LISP');
var l4=internals.QIList(l2,l3);
var l5=internals.intern('%DEFPACKAGE');
var l6=internals.make_lisp_string('name');
var l7=internals.intern('INTERN','COMMON-LISP');
var l8=new internals.Symbol('DEFCHARACTERS');
var l9=new internals.Symbol('DEFPART');
var l10=new internals.Symbol('DEFWORD');
var l11=new internals.Symbol('IKASU');
var l12=internals.QIList(l8,l9,l10,l11,l3);
var l13=internals.intern('MAPCAR','COMMON-LISP');
var l14=internals.intern('EXPORT','COMMON-LISP');
var l15=internals.intern('IIIIKA','KEYWORD');
l15.value=l15;
var l16=internals.intern('FIND-PACKAGE','COMMON-LISP');
(function(v1){l14.fvalue(internals.pv,l13.fvalue(internals.pv,(function JSCL_USER_NIL(values,v2){internals.checkArgs(arguments.length-1,1);
var v3=this;
return l7.fvalue(values,internals.js_to_lisp((function(){var TMP=v2[internals.xstring(l6)];
return TMP===undefined?l3.value:TMP;
})()),v1);
}),l12),v1);
return v1;
})(l5.fvalue(internals.pv,l1,l4));
l16.fvalue(internals.pv,l15.value);
var l17=internals.intern('*PACKAGE*','COMMON-LISP');
var l18=internals.intern('FIND-PACKAGE-OR-FAIL');
l17.value=l18.fvalue(internals.pv,l15);
l17.value=l18.fvalue(internals.pv,l15);
var l19=internals.intern('MAKE-KEYWORD','IIIIKA');
var l20=internals.intern('T','COMMON-LISP');
var l21=internals.intern('KEYWORD','KEYWORD');
l21.value=l21;
var l22=internals.make_lisp_string('~S fell through etypecase expression.');
var l23=internals.intern('ERROR','COMMON-LISP');
l19.fvalue=(function(){var FUNC=(function JSCL_USER_MAKEKEYWORD(values,v4){internals.checkArgs(arguments.length-1,1);
var v5=this;
return (function(){return (function(v7){return (function(){var X=v7;
return typeof X==='object'&&X!==null&&'length' in X&&X.stringp==1?l20.value:l3.value;
})()!==l3.value?l7.fvalue(values,v4,l21.value):(v7 instanceof internals.Symbol?l20.value:l3.value)!==l3.value?l7.fvalue(values,internals.js_to_lisp((function(){var TMP=v4[internals.xstring(l6)];
return TMP===undefined?l3.value:TMP;
})()),l21.value):l23.fvalue(values,l22,v4);
})(v4);
})();
});
FUNC.fname='MAKE-KEYWORD';
FUNC.docstring='Make keyword (copied from alexandria:make-keyword). ';
return FUNC;
})();
l19;
var l24=internals.intern('PARAM-CASE','IIIIKA');
var l25=internals.intern('STRING','COMMON-LISP');
var l26=internals.intern('CHAR=','COMMON-LISP');
var l27=internals.intern('STRING-UPCASE','COMMON-LISP');
var l28=internals.intern('MAP','COMMON-LISP');
l24.fvalue=(function(){var FUNC=(function JSCL_USER_PARAMCASE(values,v8){internals.checkArgs(arguments.length-1,1);
var v9=this;
return (function(){return l28.fvalue(values,l25,(function JSCL_USER_NIL(values,v11){internals.checkArgs(arguments.length-1,1);
var v12=this;
return l26.fvalue(internals.pv,v11,'_')!==l3.value?'-':v11;
}),l27.fvalue(internals.pv,v8));
})();
});
FUNC.fname='PARAM-CASE';
FUNC.docstring="Make string like `param-case'. (like `str:param-case'). ";
return FUNC;
})();
l24;
var l29=internals.intern('GETHASH+','IIIIKA');
var l30=internals.intern('GETHASH','COMMON-LISP');
l29.fvalue=(function(){var FUNC=(function JSCL_USER_GETHASH(values,v13,v14,v15){internals.checkArgsAtLeast(arguments.length-1,2);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 2:v15=l3.value;
;
default:break;
}var v16=this;
return (function(){return (function(){var X=v13;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})()!==l3.value?l30.fvalue(values,internals.char_to_codepoint(v13),v14,v15):l30.fvalue(values,v13,v14,v15);
})();
});
FUNC.fname='GETHASH+';
FUNC.docstring="For JSCL:\nIf `key' is character, use `char-code' as hash key.\nFor other situation, `gethash*' is equal to `gethash'. ";
return FUNC;
})();
l29;
var l31=internals.intern('(SETF_GETHASH+)','IIIIKA');
var l32=internals.intern('SETHASH');
var l33=internals.intern('VALIDATE-REQVARS');
var l34=internals.intern('GENSYM','COMMON-LISP');
var l35=internals.intern('LIST','COMMON-LISP');
var l36=internals.intern('LIST*','COMMON-LISP');
var l37=internals.intern('*SETF-EXPANDERS*');
l31.fvalue=(function(){var FUNC=(function JSCL_USER_SETFGETHASH(values,v18,v19,v20,v21){internals.checkArgsAtLeast(arguments.length-1,3);
internals.checkArgsAtMost(arguments.length-1,4);
switch(arguments.length-1){case 3:v21=l3.value;
;
default:break;
}var v22=this;
return (function(){return (function(){var X=v19;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})()!==l3.value?(function(){var v25=internals.char_to_codepoint(v19);
var v26=v20;
var v27=l3.value;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v29){switch(arguments.length-1){case 0:v29=l3.value;
;
default:break;
}var v28=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v28=new internals.Cons(arguments[I+1],v28);
var v30=this;
return l32.fvalue(internals.pv,v29,v25,v26),v29;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})():(function(){var v32=v19;
var v33=v20;
var v34=l3.value;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v36){switch(arguments.length-1){case 0:v36=l3.value;
;
default:break;
}var v35=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v35=new internals.Cons(arguments[I+1],v35);
var v37=this;
return l32.fvalue(internals.pv,v36,v32,v33),v36;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='(SETF_GETHASH+)';
return FUNC;
})();
l31;
(function(){var v39=new internals.Cons(l29,(function JSCL_USER_NIL(values){var v40=l3.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v40=new internals.Cons(arguments[I+1],v40);
var v41=this;
return (function(){var v43=l33.fvalue(internals.pv,v40,0);
var v44=v43;
return (function(v47,v48,v49,v50){return values(l35.fvalue(internals.pv,v47),v44,l35.fvalue(internals.pv,v48),l36.fvalue(internals.pv,v49,v48,v44),new internals.Cons(v50,v44));
})(l13.fvalue(internals.pv,(function JSCL_USER_NIL(values,v45){internals.checkArgs(arguments.length-1,1);
var v46=this;
return l34.fvalue(values);
}),v44),l34.fvalue(internals.pv),l31,l29);
})();
}));
var v51=new internals.Cons(v39,internals.symbolValue(l37));
return l37.value=v51;
})();
l29;
l17.value=l18.fvalue(internals.pv,l15);
var l38=internals.intern('*CHARACTER-SETS*','IIIIKA');
var l39=internals.intern('MAKE-HASH-TABLE','COMMON-LISP');
var l40=internals.make_lisp_string('vardoc');
var l41=internals.make_lisp_string('An hashtable for all characters sets. ');
l38.value=l39.fvalue(internals.pv);
(function(){var OBJ=l38;
var TMP=OBJ[internals.xstring(l40)]=internals.lisp_to_js(l41);
return TMP===undefined?l3.value:TMP;
})();
l38;
var l42=internals.intern('MAKE-CHARACTER-SET','IIIIKA');
var l43=internals.intern('FWD','KEYWORD');
l43.value=l43;
var l44=internals.intern('GETF','COMMON-LISP');
var l45=internals.intern('BWD','KEYWORD');
l45.value=l45;
var l46=internals.intern('ENDP','COMMON-LISP');
l42.fvalue=(function(){var FUNC=(function JSCL_USER_MAKECHARACTERSET(values,v52,v53){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v53=l3.value;
;
default:break;
}var v54=this;
return (function(){return (function(v57){return (function(v59){return (function(v60,v61,v62){return (function(){try{var v63=[];
return (function(){var v64=1;
var v65=[];
TBLOOP:while (true){try{switch(v64){case 1:if (l46.fvalue(internals.pv,v62)!==l3.value) (function(){throw new internals.TagNLX(v65,2);
})();
 else l3.value;
(function(v66){v60=internals.car(v66);
v66=internals.cdr(v66);
return v61=v66;
})(internals.car(v62));
v62=internals.cdr(v62);
(function(){var v68=v60;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v70){switch(arguments.length-1){case 0:v70=l3.value;
;
default:break;
}var v69=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v69=new internals.Cons(arguments[I+1],v69);
var v71=this;
return l31.fvalue(values,v70,v60,v57);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v61;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v73=v61;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v75){switch(arguments.length-1){case 0:v75=l3.value;
;
default:break;
}var v74=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v74=new internals.Cons(arguments[I+1],v74);
var v76=this;
return l31.fvalue(values,v75,v61,v59);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v60;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){throw new internals.TagNLX(v65,1);
})();
case 2:(function(){var values=internals.mv;
throw new internals.BlockNLX(v63,l35.fvalue(values,l43.value,v57,l45.value,v59),'NIL');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v65) v64=JUMP.label;
 else throw JUMP;
}}return l3.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v63) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})(l3.value,l3.value,v52);
})((function(v58){return v58!==l3.value?v58:l39.fvalue(internals.pv);
})(l44.fvalue(internals.pv,v53,l45.value)));
})((function(v56){return v56!==l3.value?v56:l39.fvalue(internals.pv);
})(l44.fvalue(internals.pv,v53,l43.value)));
})();
});
FUNC.fname='MAKE-CHARACTER-SET';
FUNC.docstring="Character set with name.\n\nThe `character-alist' should be like\n\n    (:name . char)\n\nExample:\n\n    (:question-mark . #?)\n";
return FUNC;
})();
l42;
var l47=internals.intern('FIND-CHARACTER','IIIIKA');
var l48=internals.intern('NULL','COMMON-LISP');
var l49=internals.intern('LISTP','COMMON-LISP');
var l50=internals.intern('VALIDATE-MAX-ARGS');
var l51=internals.intern('MAPHASH','COMMON-LISP');
l47.fvalue=(function(){var FUNC=(function JSCL_USER_FINDCHARACTER(values,v77){internals.checkArgs(arguments.length-1,1);
var v78=this;
return (function(){return l48.fvalue(internals.pv,v77)!==l3.value?l3.value:l49.fvalue(internals.pv,v77)!==l3.value?(function(){var v81=l33.fvalue(internals.pv,v77,2);
var v82=internals.car(v81);
var v83=internals.car(internals.cdr(v81));
var v84=l50.fvalue(internals.pv,internals.cdr(internals.cdr(v81)));
return (function(v85){return v85!==l3.value?(function(){var X=v83;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})()!==l3.value?(function(v86){return v86!==l3.value?values(v86,l35.fvalue(internals.pv,v82,v86)):l3.value;
})(l29.fvalue(internals.pv,v83,l44.fvalue(internals.pv,v85,l45.value))):(function(v87){return v87!==l3.value?values(v87,l35.fvalue(internals.pv,v82,v83)):l3.value;
})(l29.fvalue(internals.pv,v83,l44.fvalue(internals.pv,v85,l43.value))):l3.value;
})(l29.fvalue(internals.pv,v82,internals.symbolValue(l38)));
})():(function(){var X=v77;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})()!==l3.value?(function(){try{var v88=[];
return l51.fvalue(values,(function JSCL_USER_NIL(values,v89,v90){internals.checkArgs(arguments.length-1,2);
var v91=this;
return (function(v92){return v92!==l3.value?(function(){var values=internals.mv;
throw new internals.BlockNLX(v88,values(v92,l35.fvalue(internals.pv,v89,v92)),'SEARCH');
})():l3.value;
})(l29.fvalue(internals.pv,v77,l44.fvalue(internals.pv,v90,l45.value)));
}),internals.symbolValue(l38));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v88) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})():(function(){try{var v93=[];
return l51.fvalue(values,(function JSCL_USER_NIL(values,v94,v95){internals.checkArgs(arguments.length-1,2);
var v96=this;
return (function(v97){return v97!==l3.value?(function(){var values=internals.mv;
throw new internals.BlockNLX(v93,values(v97,l35.fvalue(internals.pv,v94,v77)),'SEARCH');
})():l3.value;
})(l29.fvalue(internals.pv,v77,l44.fvalue(internals.pv,v95,l43.value)));
}),internals.symbolValue(l38));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v93) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})();
});
FUNC.fname='FIND-CHARACTER';
FUNC.docstring="Find characters in `*character-sets*'.\nReturn values are search-result, (character-setname character-name);\nor `NIL' if could not found.\n\nArguments:\n`search':\n+ explicitly: (:character-set-name :character-name)\n+ explicitly but no character-name: (:character-set-name char)\n+ ambigiously: char or character-name\n\nNote this will only find the EXACTLY the character.\n";
return FUNC;
})();
l47;
l17.value=l18.fvalue(internals.pv,l15);
var l52=internals.intern('ENGLISH','KEYWORD');
l52.value=l52;
var l53=internals.intern('UPPER-Z','KEYWORD');
l53.value=l53;
var l54=internals.intern('UPPER-Y','KEYWORD');
l54.value=l54;
var l55=internals.intern('UPPER-X','KEYWORD');
l55.value=l55;
var l56=internals.intern('UPPER-W','KEYWORD');
l56.value=l56;
var l57=internals.intern('UPPER-V','KEYWORD');
l57.value=l57;
var l58=internals.intern('UPPER-U','KEYWORD');
l58.value=l58;
var l59=internals.intern('UPPER-T','KEYWORD');
l59.value=l59;
var l60=internals.intern('UPPER-S','KEYWORD');
l60.value=l60;
var l61=internals.intern('UPPER-R','KEYWORD');
l61.value=l61;
var l62=internals.intern('UPPER-Q','KEYWORD');
l62.value=l62;
var l63=internals.intern('UPPER-P','KEYWORD');
l63.value=l63;
var l64=internals.intern('UPPER-O','KEYWORD');
l64.value=l64;
var l65=internals.intern('UPPER-N','KEYWORD');
l65.value=l65;
var l66=internals.intern('UPPER-M','KEYWORD');
l66.value=l66;
var l67=internals.intern('UPPER-L','KEYWORD');
l67.value=l67;
var l68=internals.intern('UPPER-K','KEYWORD');
l68.value=l68;
var l69=internals.intern('UPPER-J','KEYWORD');
l69.value=l69;
var l70=internals.intern('UPPER-I','KEYWORD');
l70.value=l70;
var l71=internals.intern('UPPER-H','KEYWORD');
l71.value=l71;
var l72=internals.intern('UPPER-G','KEYWORD');
l72.value=l72;
var l73=internals.intern('UPPER-F','KEYWORD');
l73.value=l73;
var l74=internals.intern('UPPER-E','KEYWORD');
l74.value=l74;
var l75=internals.intern('UPPER-D','KEYWORD');
l75.value=l75;
var l76=internals.intern('UPPER-C','KEYWORD');
l76.value=l76;
var l77=internals.intern('UPPER-B','KEYWORD');
l77.value=l77;
var l78=internals.intern('UPPER-A','KEYWORD');
l78.value=l78;
var l79=internals.intern('LOWER-Z','KEYWORD');
l79.value=l79;
var l80=internals.intern('LOWER-Y','KEYWORD');
l80.value=l80;
var l81=internals.intern('LOWER-X','KEYWORD');
l81.value=l81;
var l82=internals.intern('LOWER-W','KEYWORD');
l82.value=l82;
var l83=internals.intern('LOWER-V','KEYWORD');
l83.value=l83;
var l84=internals.intern('LOWER-U','KEYWORD');
l84.value=l84;
var l85=internals.intern('LOWER-T','KEYWORD');
l85.value=l85;
var l86=internals.intern('LOWER-S','KEYWORD');
l86.value=l86;
var l87=internals.intern('LOWER-R','KEYWORD');
l87.value=l87;
var l88=internals.intern('LOWER-Q','KEYWORD');
l88.value=l88;
var l89=internals.intern('LOWER-P','KEYWORD');
l89.value=l89;
var l90=internals.intern('LOWER-O','KEYWORD');
l90.value=l90;
var l91=internals.intern('LOWER-N','KEYWORD');
l91.value=l91;
var l92=internals.intern('LOWER-M','KEYWORD');
l92.value=l92;
var l93=internals.intern('LOWER-L','KEYWORD');
l93.value=l93;
var l94=internals.intern('LOWER-K','KEYWORD');
l94.value=l94;
var l95=internals.intern('LOWER-J','KEYWORD');
l95.value=l95;
var l96=internals.intern('LOWER-I','KEYWORD');
l96.value=l96;
var l97=internals.intern('LOWER-H','KEYWORD');
l97.value=l97;
var l98=internals.intern('LOWER-G','KEYWORD');
l98.value=l98;
var l99=internals.intern('LOWER-F','KEYWORD');
l99.value=l99;
var l100=internals.intern('LOWER-E','KEYWORD');
l100.value=l100;
var l101=internals.intern('LOWER-D','KEYWORD');
l101.value=l101;
var l102=internals.intern('LOWER-C','KEYWORD');
l102.value=l102;
var l103=internals.intern('LOWER-B','KEYWORD');
l103.value=l103;
var l104=internals.intern('LOWER-A','KEYWORD');
l104.value=l104;
var l105=internals.QIList(internals.QIList(l53,'Z'),internals.QIList(l54,'Y'),internals.QIList(l55,'X'),internals.QIList(l56,'W'),internals.QIList(l57,'V'),internals.QIList(l58,'U'),internals.QIList(l59,'T'),internals.QIList(l60,'S'),internals.QIList(l61,'R'),internals.QIList(l62,'Q'),internals.QIList(l63,'P'),internals.QIList(l64,'O'),internals.QIList(l65,'N'),internals.QIList(l66,'M'),internals.QIList(l67,'L'),internals.QIList(l68,'K'),internals.QIList(l69,'J'),internals.QIList(l70,'I'),internals.QIList(l71,'H'),internals.QIList(l72,'G'),internals.QIList(l73,'F'),internals.QIList(l74,'E'),internals.QIList(l75,'D'),internals.QIList(l76,'C'),internals.QIList(l77,'B'),internals.QIList(l78,'A'),internals.QIList(l79,'z'),internals.QIList(l80,'y'),internals.QIList(l81,'x'),internals.QIList(l82,'w'),internals.QIList(l83,'v'),internals.QIList(l84,'u'),internals.QIList(l85,'t'),internals.QIList(l86,'s'),internals.QIList(l87,'r'),internals.QIList(l88,'q'),internals.QIList(l89,'p'),internals.QIList(l90,'o'),internals.QIList(l91,'n'),internals.QIList(l92,'m'),internals.QIList(l93,'l'),internals.QIList(l94,'k'),internals.QIList(l95,'j'),internals.QIList(l96,'i'),internals.QIList(l97,'h'),internals.QIList(l98,'g'),internals.QIList(l99,'f'),internals.QIList(l100,'e'),internals.QIList(l101,'d'),internals.QIList(l102,'c'),internals.QIList(l103,'b'),internals.QIList(l104,'a'),l3);
(function(){var v99=l52;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v101){switch(arguments.length-1){case 0:v101=l3.value;
;
default:break;
}var v100=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v100=new internals.Cons(arguments[I+1],v100);
var v102=this;
return l31.fvalue(values,v101,l52,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l105,l29.fvalue(internals.pv,l52,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l52;
var l106=internals.intern('JAPANESE-SYMBOL','KEYWORD');
l106.value=l106;
var l107=internals.intern('IDEOGRAPHIC-COMMA','KEYWORD');
l107.value=l107;
var l108=internals.QIList(internals.QIList(l107,'、'),l3);
(function(){var v104=l106;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v106){switch(arguments.length-1){case 0:v106=l3.value;
;
default:break;
}var v105=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v105=new internals.Cons(arguments[I+1],v105);
var v107=this;
return l31.fvalue(values,v106,l106,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l108,l29.fvalue(internals.pv,l106,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l106;
var l109=internals.intern('HIRAGANA','KEYWORD');
l109.value=l109;
var l110=internals.intern('N','KEYWORD');
l110.value=l110;
var l111=internals.intern('WO','KEYWORD');
l111.value=l111;
var l112=internals.intern('WA','KEYWORD');
l112.value=l112;
var l113=internals.intern('RO','KEYWORD');
l113.value=l113;
var l114=internals.intern('RE','KEYWORD');
l114.value=l114;
var l115=internals.intern('RU','KEYWORD');
l115.value=l115;
var l116=internals.intern('RI','KEYWORD');
l116.value=l116;
var l117=internals.intern('RA','KEYWORD');
l117.value=l117;
var l118=internals.intern('MO','KEYWORD');
l118.value=l118;
var l119=internals.intern('ME','KEYWORD');
l119.value=l119;
var l120=internals.intern('MU','KEYWORD');
l120.value=l120;
var l121=internals.intern('MI','KEYWORD');
l121.value=l121;
var l122=internals.intern('MA','KEYWORD');
l122.value=l122;
var l123=internals.intern('PO','KEYWORD');
l123.value=l123;
var l124=internals.intern('PE','KEYWORD');
l124.value=l124;
var l125=internals.intern('PU','KEYWORD');
l125.value=l125;
var l126=internals.intern('PI','KEYWORD');
l126.value=l126;
var l127=internals.intern('PA','KEYWORD');
l127.value=l127;
var l128=internals.intern('BO','KEYWORD');
l128.value=l128;
var l129=internals.intern('BE','KEYWORD');
l129.value=l129;
var l130=internals.intern('BU','KEYWORD');
l130.value=l130;
var l131=internals.intern('BI','KEYWORD');
l131.value=l131;
var l132=internals.intern('BA','KEYWORD');
l132.value=l132;
var l133=internals.intern('HO','KEYWORD');
l133.value=l133;
var l134=internals.intern('HE','KEYWORD');
l134.value=l134;
var l135=internals.intern('FU','KEYWORD');
l135.value=l135;
var l136=internals.intern('HI','KEYWORD');
l136.value=l136;
var l137=internals.intern('HA','KEYWORD');
l137.value=l137;
var l138=internals.intern('NO','KEYWORD');
l138.value=l138;
var l139=internals.intern('NE','KEYWORD');
l139.value=l139;
var l140=internals.intern('NU','KEYWORD');
l140.value=l140;
var l141=internals.intern('NI','KEYWORD');
l141.value=l141;
var l142=internals.intern('NA','KEYWORD');
l142.value=l142;
var l143=internals.intern('DO','KEYWORD');
l143.value=l143;
var l144=internals.intern('DE','KEYWORD');
l144.value=l144;
var l145=internals.intern('DU','KEYWORD');
l145.value=l145;
var l146=internals.intern('DI','KEYWORD');
l146.value=l146;
var l147=internals.intern('DA','KEYWORD');
l147.value=l147;
var l148=internals.intern('TO','KEYWORD');
l148.value=l148;
var l149=internals.intern('TE','KEYWORD');
l149.value=l149;
var l150=internals.intern('TU','KEYWORD');
l150.value=l150;
var l151=internals.intern('TI','KEYWORD');
l151.value=l151;
var l152=internals.intern('TA','KEYWORD');
l152.value=l152;
var l153=internals.intern('ZO','KEYWORD');
l153.value=l153;
var l154=internals.intern('ZE','KEYWORD');
l154.value=l154;
var l155=internals.intern('ZU','KEYWORD');
l155.value=l155;
var l156=internals.intern('JI','KEYWORD');
l156.value=l156;
var l157=internals.intern('ZA','KEYWORD');
l157.value=l157;
var l158=internals.intern('SO','KEYWORD');
l158.value=l158;
var l159=internals.intern('SE','KEYWORD');
l159.value=l159;
var l160=internals.intern('SU','KEYWORD');
l160.value=l160;
var l161=internals.intern('SI','KEYWORD');
l161.value=l161;
var l162=internals.intern('SA','KEYWORD');
l162.value=l162;
var l163=internals.intern('GO','KEYWORD');
l163.value=l163;
var l164=internals.intern('GE','KEYWORD');
l164.value=l164;
var l165=internals.intern('GU','KEYWORD');
l165.value=l165;
var l166=internals.intern('GI','KEYWORD');
l166.value=l166;
var l167=internals.intern('GA','KEYWORD');
l167.value=l167;
var l168=internals.intern('KO','KEYWORD');
l168.value=l168;
var l169=internals.intern('KE','KEYWORD');
l169.value=l169;
var l170=internals.intern('KU','KEYWORD');
l170.value=l170;
var l171=internals.intern('KI','KEYWORD');
l171.value=l171;
var l172=internals.intern('KA','KEYWORD');
l172.value=l172;
var l173=internals.intern('O','KEYWORD');
l173.value=l173;
var l174=internals.intern('E','KEYWORD');
l174.value=l174;
var l175=internals.intern('U','KEYWORD');
l175.value=l175;
var l176=internals.intern('I','KEYWORD');
l176.value=l176;
var l177=internals.intern('A','KEYWORD');
l177.value=l177;
var l178=internals.QIList(internals.QIList(l110,'ん'),internals.QIList(l111,'を'),internals.QIList(l112,'わ'),internals.QIList(l113,'ろ'),internals.QIList(l114,'れ'),internals.QIList(l115,'る'),internals.QIList(l116,'り'),internals.QIList(l117,'ら'),internals.QIList(l118,'も'),internals.QIList(l119,'め'),internals.QIList(l120,'む'),internals.QIList(l121,'み'),internals.QIList(l122,'ま'),internals.QIList(l123,'ぽ'),internals.QIList(l124,'ぺ'),internals.QIList(l125,'ぷ'),internals.QIList(l126,'ぴ'),internals.QIList(l127,'ぱ'),internals.QIList(l128,'ぼ'),internals.QIList(l129,'べ'),internals.QIList(l130,'ぶ'),internals.QIList(l131,'び'),internals.QIList(l132,'ば'),internals.QIList(l133,'ほ'),internals.QIList(l134,'へ'),internals.QIList(l135,'ふ'),internals.QIList(l136,'ひ'),internals.QIList(l137,'は'),internals.QIList(l138,'の'),internals.QIList(l139,'ね'),internals.QIList(l140,'ぬ'),internals.QIList(l141,'に'),internals.QIList(l142,'な'),internals.QIList(l143,'ど'),internals.QIList(l144,'で'),internals.QIList(l145,'づ'),internals.QIList(l146,'ぢ'),internals.QIList(l147,'だ'),internals.QIList(l148,'と'),internals.QIList(l149,'て'),internals.QIList(l150,'つ'),internals.QIList(l151,'ち'),internals.QIList(l152,'た'),internals.QIList(l153,'ぞ'),internals.QIList(l154,'ぜ'),internals.QIList(l155,'ず'),internals.QIList(l156,'じ'),internals.QIList(l157,'ざ'),internals.QIList(l158,'そ'),internals.QIList(l159,'せ'),internals.QIList(l160,'す'),internals.QIList(l161,'し'),internals.QIList(l162,'さ'),internals.QIList(l163,'ご'),internals.QIList(l164,'げ'),internals.QIList(l165,'ぐ'),internals.QIList(l166,'ぎ'),internals.QIList(l167,'が'),internals.QIList(l168,'こ'),internals.QIList(l169,'け'),internals.QIList(l170,'く'),internals.QIList(l171,'き'),internals.QIList(l172,'か'),internals.QIList(l173,'お'),internals.QIList(l174,'え'),internals.QIList(l175,'う'),internals.QIList(l176,'い'),internals.QIList(l177,'あ'),l3);
(function(){var v109=l109;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v111){switch(arguments.length-1){case 0:v111=l3.value;
;
default:break;
}var v110=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v110=new internals.Cons(arguments[I+1],v110);
var v112=this;
return l31.fvalue(values,v111,l109,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l178,l29.fvalue(internals.pv,l109,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l109;
var l179=internals.intern('KATAKANA','KEYWORD');
l179.value=l179;
var l180=internals.QIList(internals.QIList(l110,'ン'),internals.QIList(l111,'ヲ'),internals.QIList(l112,'ワ'),internals.QIList(l113,'ロ'),internals.QIList(l114,'レ'),internals.QIList(l115,'ル'),internals.QIList(l116,'リ'),internals.QIList(l117,'ラ'),internals.QIList(l118,'モ'),internals.QIList(l119,'メ'),internals.QIList(l120,'ム'),internals.QIList(l121,'ミ'),internals.QIList(l122,'マ'),internals.QIList(l123,'ポ'),internals.QIList(l124,'ペ'),internals.QIList(l125,'プ'),internals.QIList(l126,'ピ'),internals.QIList(l127,'パ'),internals.QIList(l128,'ボ'),internals.QIList(l129,'ベ'),internals.QIList(l130,'ブ'),internals.QIList(l131,'ビ'),internals.QIList(l132,'バ'),internals.QIList(l133,'ホ'),internals.QIList(l134,'ヘ'),internals.QIList(l135,'フ'),internals.QIList(l136,'ヒ'),internals.QIList(l137,'ハ'),internals.QIList(l138,'ノ'),internals.QIList(l139,'ネ'),internals.QIList(l140,'ヌ'),internals.QIList(l141,'ニ'),internals.QIList(l142,'ナ'),internals.QIList(l143,'ド'),internals.QIList(l144,'デ'),internals.QIList(l145,'ヅ'),internals.QIList(l146,'ヂ'),internals.QIList(l147,'ダ'),internals.QIList(l148,'ト'),internals.QIList(l149,'テ'),internals.QIList(l150,'ツ'),internals.QIList(l151,'チ'),internals.QIList(l152,'タ'),internals.QIList(l153,'ゾ'),internals.QIList(l154,'ゼ'),internals.QIList(l155,'ズ'),internals.QIList(l156,'ジ'),internals.QIList(l157,'ザ'),internals.QIList(l158,'ソ'),internals.QIList(l159,'セ'),internals.QIList(l160,'ス'),internals.QIList(l161,'シ'),internals.QIList(l162,'サ'),internals.QIList(l163,'ゴ'),internals.QIList(l164,'ゲ'),internals.QIList(l165,'グ'),internals.QIList(l166,'ギ'),internals.QIList(l167,'ガ'),internals.QIList(l168,'コ'),internals.QIList(l169,'ケ'),internals.QIList(l170,'ク'),internals.QIList(l171,'キ'),internals.QIList(l172,'カ'),internals.QIList(l173,'オ'),internals.QIList(l174,'エ'),internals.QIList(l175,'ウ'),internals.QIList(l176,'イ'),internals.QIList(l177,'ア'),l3);
(function(){var v114=l179;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v116){switch(arguments.length-1){case 0:v116=l3.value;
;
default:break;
}var v115=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v115=new internals.Cons(arguments[I+1],v115);
var v117=this;
return l31.fvalue(values,v116,l179,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l180,l29.fvalue(internals.pv,l179,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l179;
var l181=internals.intern('SYMBOLS-1','KEYWORD');
l181.value=l181;
var l182=internals.intern('CIRCUMFLEX-ACCENT','KEYWORD');
l182.value=l182;
var l183=internals.intern('VERTICAL-LINE','KEYWORD');
l183.value=l183;
var l184=internals.intern('CURRENCY-SIGN','KEYWORD');
l184.value=l184;
var l185=internals.intern('MATHEMATICAL-ITALIC-SMALL-F','KEYWORD');
l185.value=l185;
var l186=internals.intern('YEN-SIGN','KEYWORD');
l186.value=l186;
var l187=internals.intern('POUND-SIGN','KEYWORD');
l187.value=l187;
var l188=internals.intern('EURO-SIGN','KEYWORD');
l188.value=l188;
var l189=internals.intern('CENT-SIGN','KEYWORD');
l189.value=l189;
var l190=internals.intern('DOLLAR-SIGN','KEYWORD');
l190.value=l190;
var l191=internals.intern('TILDE','KEYWORD');
l191.value=l191;
var l192=internals.intern('LEFT-RIGHT-DOUBLE-ARROW','KEYWORD');
l192.value=l192;
var l193=internals.intern('RIGHTWARDS-DOUBLE-ARROW','KEYWORD');
l193.value=l193;
var l194=internals.intern('DOWNWARDS-ARROW','KEYWORD');
l194.value=l194;
var l195=internals.intern('UPWARDS-ARROW','KEYWORD');
l195.value=l195;
var l196=internals.intern('RIGHTWARDS-ARROW','KEYWORD');
l196.value=l196;
var l197=internals.intern('LEFTWARDS-ARROW','KEYWORD');
l197.value=l197;
var l198=internals.intern('RIGHT-POINTING-DOUBLE-ANGLE-QUOTATION-MARK','KEYWORD');
l198.value=l198;
var l199=internals.intern('LEFT-POINTING-DOUBLE-ANGLE-QUOTATION-MARK','KEYWORD');
l199.value=l199;
var l200=internals.intern('RIGHT-DOUBLE-ANGLE-BRACKET','KEYWORD');
l200.value=l200;
var l201=internals.intern('LEFT-DOUBLE-ANGLE-BRACKET','KEYWORD');
l201.value=l201;
var l202=internals.intern('GREATER-THAN-SIGN','KEYWORD');
l202.value=l202;
var l203=internals.intern('LESS-THAN-SIGN','KEYWORD');
l203.value=l203;
var l204=internals.intern('LOW-LINE','KEYWORD');
l204.value=l204;
var l205=internals.intern('DOUBLE-LOW-9-QUOTATION-MARK','KEYWORD');
l205.value=l205;
var l206=internals.intern('RIGHT-DOUBLE-QUOTATION-MARK','KEYWORD');
l206.value=l206;
var l207=internals.intern('LEFT-DOUBLE-QUOTATION-MARK','KEYWORD');
l207.value=l207;
var l208=internals.intern('QUOTATION-MARK','KEYWORD');
l208.value=l208;
var l209=internals.intern('HORIZONTAL-ELLIPSIS','KEYWORD');
l209.value=l209;
var l210=internals.intern('MIDDLE-DOT','KEYWORD');
l210.value=l210;
var l211=internals.intern('RIGHT-CURLY-BRACKET','KEYWORD');
l211.value=l211;
var l212=internals.intern('LEFT-CURLY-BRACKET','KEYWORD');
l212.value=l212;
var l213=internals.intern('SOLIDUS','KEYWORD');
l213.value=l213;
var l214=internals.intern('SINGLE-HIGH-REVERSED-9-QUOTATION-MARK','KEYWORD');
l214.value=l214;
var l215=internals.intern('COMMA','KEYWORD');
l215.value=l215;
var l216=internals.intern('RIGHT-SINGLE-QUOTATION-MARK','KEYWORD');
l216.value=l216;
var l217=internals.intern('LEFT-SINGLE-QUOTATION-MARK','KEYWORD');
l217.value=l217;
var l218=internals.intern('APOSTROPHE','KEYWORD');
l218.value=l218;
var l219=internals.intern('COLON','KEYWORD');
l219.value=l219;
var l220=internals.intern('SEMICOLON','KEYWORD');
l220.value=l220;
var l221=internals.intern('RIGHT-SQUARE-BRACKET','KEYWORD');
l221.value=l221;
var l222=internals.intern('LEFT-SQUARE-BRACKET','KEYWORD');
l222.value=l222;
var l223=internals.intern('RIGHT-PARENTHESIS','KEYWORD');
l223.value=l223;
var l224=internals.intern('LEFT-PARENTHESIS','KEYWORD');
l224.value=l224;
var l225=internals.intern('HYPHEN-MINUS','KEYWORD');
l225.value=l225;
var l226=internals.intern('AMPERSAND','KEYWORD');
l226.value=l226;
var l227=internals.intern('NUMBER-SIGN','KEYWORD');
l227.value=l227;
var l228=internals.intern('FULL-STOP','KEYWORD');
l228.value=l228;
var l229=internals.intern('INVERTED-EXCLAMATION-MARK','KEYWORD');
l229.value=l229;
var l230=internals.intern('INVERTED-QUESTION-MARK','KEYWORD');
l230.value=l230;
var l231=internals.intern('EXCLAMATION-MARK','KEYWORD');
l231.value=l231;
var l232=internals.intern('QUESTION-MARK','KEYWORD');
l232.value=l232;
var l233=internals.QIList(internals.QIList(l182,'^'),internals.QIList(l183,'|'),internals.QIList(l184,'¤'),internals.QIList(l185,'𝑓'),internals.QIList(l186,'¥'),internals.QIList(l187,'£'),internals.QIList(l188,'€'),internals.QIList(l189,'¢'),internals.QIList(l190,'$'),internals.QIList(l191,'~'),internals.QIList(l192,'⇔'),internals.QIList(l193,'⇒'),internals.QIList(l194,'↓'),internals.QIList(l195,'↑'),internals.QIList(l196,'→'),internals.QIList(l197,'←'),internals.QIList(l198,'»'),internals.QIList(l199,'«'),internals.QIList(l200,'》'),internals.QIList(l201,'《'),internals.QIList(l202,'>'),internals.QIList(l203,'<'),internals.QIList(l204,'_'),internals.QIList(l205,'„'),internals.QIList(l206,'”'),internals.QIList(l207,'“'),internals.QIList(l208,'"'),internals.QIList(l209,'…'),internals.QIList(l210,'·'),internals.QIList(l211,'}'),internals.QIList(l212,'{'),internals.QIList(l213,'/'),internals.QIList(l214,'‛'),internals.QIList(l215,','),internals.QIList(l216,'’'),internals.QIList(l217,'‘'),internals.QIList(l218,"'"),internals.QIList(l219,':'),internals.QIList(l220,';'),internals.QIList(l221,']'),internals.QIList(l222,'['),internals.QIList(l223,')'),internals.QIList(l224,'('),internals.QIList(l225,'-'),internals.QIList(l226,'&'),internals.QIList(l227,'#'),internals.QIList(l228,'.'),internals.QIList(l215,','),internals.QIList(l229,'¡'),internals.QIList(l230,'¿'),internals.QIList(l231,'!'),internals.QIList(l232,'?'),l3);
(function(){var v119=l181;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v121){switch(arguments.length-1){case 0:v121=l3.value;
;
default:break;
}var v120=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v120=new internals.Cons(arguments[I+1],v120);
var v122=this;
return l31.fvalue(values,v121,l181,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l233,l29.fvalue(internals.pv,l181,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l181;
var l234=internals.intern('SYMBOLS-2','KEYWORD');
l234.value=l234;
(function(){var v124=l234;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v126){switch(arguments.length-1){case 0:v126=l3.value;
;
default:break;
}var v125=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v125=new internals.Cons(arguments[I+1],v125);
var v127=this;
return l31.fvalue(values,v126,l234,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l3,l29.fvalue(internals.pv,l234,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l234;
var l235=internals.intern('SYMBOLS-3','KEYWORD');
l235.value=l235;
var l236=internals.intern('OMEGA','KEYWORD');
l236.value=l236;
var l237=internals.intern('PSI','KEYWORD');
l237.value=l237;
var l238=internals.intern('CHI','KEYWORD');
l238.value=l238;
var l239=internals.intern('PHI','KEYWORD');
l239.value=l239;
var l240=internals.intern('UPSILON','KEYWORD');
l240.value=l240;
var l241=internals.intern('TAU','KEYWORD');
l241.value=l241;
var l242=internals.intern('SIGMA','KEYWORD');
l242.value=l242;
var l243=internals.intern('RHO','KEYWORD');
l243.value=l243;
var l244=internals.intern('OMICRON','KEYWORD');
l244.value=l244;
var l245=internals.intern('XI','KEYWORD');
l245.value=l245;
var l246=internals.intern('LAMBDA','KEYWORD');
l246.value=l246;
var l247=internals.intern('KAPPA','KEYWORD');
l247.value=l247;
var l248=internals.intern('IOTA','KEYWORD');
l248.value=l248;
var l249=internals.intern('THETA','KEYWORD');
l249.value=l249;
var l250=internals.intern('ETA','KEYWORD');
l250.value=l250;
var l251=internals.intern('ZETA','KEYWORD');
l251.value=l251;
var l252=internals.intern('EPSILON','KEYWORD');
l252.value=l252;
var l253=internals.intern('DELTA','KEYWORD');
l253.value=l253;
var l254=internals.intern('GAMMA','KEYWORD');
l254.value=l254;
var l255=internals.intern('BETA','KEYWORD');
l255.value=l255;
var l256=internals.intern('ALPHA','KEYWORD');
l256.value=l256;
var l257=internals.QIList(internals.QIList(l236,'ω'),internals.QIList(l237,'ψ'),internals.QIList(l238,'χ'),internals.QIList(l239,'φ'),internals.QIList(l240,'υ'),internals.QIList(l241,'τ'),internals.QIList(l242,'σ'),internals.QIList(l243,'ρ'),internals.QIList(l126,'π'),internals.QIList(l244,'ο'),internals.QIList(l245,'ξ'),internals.QIList(l140,'ν'),internals.QIList(l120,'μ'),internals.QIList(l246,'λ'),internals.QIList(l247,'κ'),internals.QIList(l248,'ι'),internals.QIList(l249,'θ'),internals.QIList(l250,'η'),internals.QIList(l251,'ζ'),internals.QIList(l252,'ε'),internals.QIList(l253,'δ'),internals.QIList(l254,'γ'),internals.QIList(l255,'β'),internals.QIList(l256,'α'),l3);
(function(){var v129=l235;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v131){switch(arguments.length-1){case 0:v131=l3.value;
;
default:break;
}var v130=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v130=new internals.Cons(arguments[I+1],v130);
var v132=this;
return l31.fvalue(values,v131,l235,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l257,l29.fvalue(internals.pv,l235,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l235;
var l258=internals.intern('SYMBOLS-4','KEYWORD');
l258.value=l258;
var l259=internals.QIList(internals.QIList(l236,'Ω'),internals.QIList(l237,'Ψ'),internals.QIList(l238,'Χ'),internals.QIList(l239,'Φ'),internals.QIList(l240,'Υ'),internals.QIList(l241,'Τ'),internals.QIList(l242,'Σ'),internals.QIList(l243,'Ρ'),internals.QIList(l126,'Π'),internals.QIList(l244,'Ο'),internals.QIList(l245,'Ξ'),internals.QIList(l140,'Ν'),internals.QIList(l120,'Μ'),internals.QIList(l246,'Λ'),internals.QIList(l247,'Κ'),internals.QIList(l248,'Ι'),internals.QIList(l249,'Θ'),internals.QIList(l250,'Η'),internals.QIList(l251,'Ζ'),internals.QIList(l252,'Ε'),internals.QIList(l253,'Δ'),internals.QIList(l254,'Γ'),internals.QIList(l255,'Β'),internals.QIList(l256,'Α'),l3);
(function(){var v134=l258;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v136){switch(arguments.length-1){case 0:v136=l3.value;
;
default:break;
}var v135=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v135=new internals.Cons(arguments[I+1],v135);
var v137=this;
return l31.fvalue(values,v136,l258,internals.symbolValue(l38));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l42.fvalue(values,l259,l29.fvalue(internals.pv,l258,internals.symbolValue(l38),l3.value));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l258;
l17.value=l18.fvalue(internals.pv,l15);
var l260=internals.intern('IIIIKA-ERROR','IIIIKA');
var l261=internals.intern('DIRECT-SUPERCLASSES','KEYWORD');
l261.value=l261;
var l262=internals.intern('!FIND-CLASS');
var l263=internals.intern('DIRECT-SLOTS','KEYWORD');
l263.value=l263;
var l264=internals.intern('NAME','KEYWORD');
l264.value=l264;
var l265=internals.intern('ELEM','IIIIKA');
var l266=internals.intern('INITARGS','KEYWORD');
l266.value=l266;
var l267=internals.intern('ELEM','KEYWORD');
l267.value=l267;
var l268=internals.QIList(l267,l3);
var l269=internals.intern('MSG','IIIIKA');
var l270=internals.intern('MSG','KEYWORD');
l270.value=l270;
var l271=internals.QIList(l270,l3);
var l272=internals.intern('ENSURE-CLASS');
l272.fvalue(internals.pv,l260,l261.value,l35.fvalue(internals.pv,l262.fvalue(internals.pv,l23)),l263.value,l35.fvalue(internals.pv,l35.fvalue(internals.pv,l264.value,l265,l266.value,l268),l35.fvalue(internals.pv,l264.value,l269,l266.value,l271)),l3,l3);
l3.value;
l260;
var l273=internals.intern('UNKNOWN-RULE','IIIIKA');
l272.fvalue(internals.pv,l273,l261.value,l35.fvalue(internals.pv,l262.fvalue(internals.pv,l260)),l263.value,l3.value,l3,l3);
l3.value;
l273;
var l274=internals.intern('INVALID-RULE','IIIIKA');
l272.fvalue(internals.pv,l274,l261.value,l35.fvalue(internals.pv,l262.fvalue(internals.pv,l260)),l263.value,l3.value,l3,l3);
l3.value;
l274;
var l275=internals.intern('*STRICTP*','IIIIKA');
l275.value=l20.value;
l275;
var l276=internals.intern('*DEFAULT-FALLBACK-CHARACTER*','IIIIKA');
var l277=internals.make_lisp_string('ロ');
var l278=internals.make_lisp_string("Default fallback character when `ikasu-char' failed\nto find rule for the input character. ");
l276.value=l277;
(function(){var OBJ=l276;
var TMP=OBJ[internals.xstring(l40)]=internals.lisp_to_js(l278);
return TMP===undefined?l3.value:TMP;
})();
l276;
var l279=internals.intern('*RULE-TABLE*','IIIIKA');
var l280=internals.make_lisp_string("A simplified mapping rule table.\n\nThe rule table should be like:\n\n    {char | keyword} -> ({char | keyword | list})\n\nFROM\n+ `char' chinese word;\n+ `keyword' nickname of the `char',\n  also could be used as defining phrase and shortcuts;\n\nTO\n+ `char' and `keyword' should be another FROM element\n  in `*rule-table*';\n+ `list' should be the character (use `find-character'\n  to index the character)\n\nUse `defrule' and `defrule*' to define the mapping rule.\n");
l279.value=l39.fvalue(internals.pv);
(function(){var OBJ=l279;
var TMP=OBJ[internals.xstring(l40)]=internals.lisp_to_js(l280);
return TMP===undefined?l3.value:TMP;
})();
l279;
var l281=internals.intern('IKASU-CHAR','IIIIKA');
var l282=internals.intern('*HANDLER-BINDINGS*');
var l283=internals.make_lisp_string('message');
var l284=internals.intern('%%ERROR');
var l285=internals.intern('MAKE-STRING-OUTPUT-STREAM','COMMON-LISP');
var l286=internals.intern('OR','COMMON-LISP');
var l287=internals.intern('CHARACTER','COMMON-LISP');
var l288=internals.intern('KEYWORD','COMMON-LISP');
var l289=internals.QIList(l286,l287,l288,l3);
var l290=internals.intern('!TYPEP');
var l291=internals.intern('WRITE-CHAR','COMMON-LISP');
var l292=internals.intern('UNKNOWN-RULE','KEYWORD');
l292.value=l292;
var l293=internals.intern('UNKNOWN-CHAR','KEYWORD');
l293.value=l293;
var l294=internals.intern('GET-OUTPUT-STREAM-STRING','COMMON-LISP');
var l295=internals.intern('SLOT-VALUE','COMMON-LISP');
l281.fvalue=(function(){var FUNC=(function JSCL_USER_IKASUCHAR(values,v138,v139){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v139=internals.symbolValue(l276);
;
default:break;
}var v140=this;
return (function(){return (function(){try{var v142=[];
return (function(v143){return (function(){var v144=1;
var v145=[];
TBLOOP:while (true){try{switch(v144){case 1:(function(v146){return internals.bindSpecialBindings([l282],[v146],(function(){(function(){var v148=new internals.Cons(l273,(function JSCL_USER_NIL(values,v149){internals.checkArgs(arguments.length-1,1);
var v150=this;
v143=v149;
return (function(){throw new internals.TagNLX(v145,2);
})();
}));
var v151=new internals.Cons(v148,internals.symbolValue(l282));
return l282.value=v151;
})();
return (function(){try{return (function(){var values=internals.mv;
throw new internals.BlockNLX(v142,(function(v154){(function(){var v155=(function JSCL_USER_NIL(values,v156){internals.checkArgs(arguments.length-1,1);
var v157=this;
return (function(){return (function(v159){return l290.fvalue(internals.pv,v159,l289)!==l3.value?(function(v160){return v160!==l3.value?v160:(function(v161){return v161!==l3.value?v161:l23.fvalue(values,l273,l267.value,v156,l270.value,l292.value);
})(((function(){var X=v156;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})()!==l3.value?l47.fvalue(internals.pv,v156):l3.value)!==l3.value?l291.fvalue(internals.pv,v156,v154):l3.value);
})(l13.fvalue(internals.pv,v155,l29.fvalue(internals.pv,v156,internals.symbolValue(l279)))):l49.fvalue(internals.pv,v159)!==l3.value?l291.fvalue(values,(function(v162){return v162!==l3.value?v162:l23.fvalue(internals.pv,l273,l267.value,v156,l270.value,l293.value);
})(l47.fvalue(internals.pv,v156)),v154):l23.fvalue(values,l22,v156);
})(v156);
})();
});
return internals.pv(v155(internals.pv,v138),l3.value);
})();
return l294.fvalue(values,v154);
})(l285.fvalue(internals.pv)),'G1186');
})();
}catch (v152){v152=internals.js_to_lisp(v152);
return (internals.isNLX(v152)?l20.value:l3.value)!==l3.value?(function(){throw v152;
})():l284.fvalue(internals.pv,(function(v153){return v153!==l3.value?v153:v152;
})(internals.js_to_lisp((function(){var TMP=v152[internals.xstring(l283)];
return TMP===undefined?l3.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l282));
case 2:(function(){var values=internals.mv;
throw new internals.BlockNLX(v142,(function(v163){return values(v139,l35.fvalue(internals.pv,l295.fvalue(internals.pv,v163,l269),l295.fvalue(internals.pv,v163,l265)));
})(v143),'G1186');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v145) v144=JUMP.label;
 else throw JUMP;
}}return l3.value;
})();
})(l3.value);
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v142) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})();
});
FUNC.fname='IKASU-CHAR';
FUNC.docstring="Make char ikasu by `*rule-table*'.\nReturn an ikasu string. ";
return FUNC;
})();
l281;
var l296=internals.intern('IKASU','IIIIKA');
var l297=internals.intern('WRITE-STRING','COMMON-LISP');
l296.fvalue=(function(){var FUNC=(function JSCL_USER_IKASU(values,v164){internals.checkArgs(arguments.length-1,1);
var v165=this;
return (function(){return (function(v167){l28.fvalue(internals.pv,l3.value,(function JSCL_USER_NIL(values,v168){internals.checkArgs(arguments.length-1,1);
var v169=this;
return (function(v170){return v170!==l3.value?v170:l26.fvalue(internals.pv,v168,' ');
})(l26.fvalue(internals.pv,v168,'\n'))!==l3.value?l3.value:l297.fvalue(values,l281.fvalue(internals.pv,v168),v167);
}),v164);
return l294.fvalue(values,v167);
})(l285.fvalue(internals.pv));
})();
});
FUNC.fname='IKASU';
FUNC.docstring="Make `input' ikasu.\nReturn an ikasu output string. ";
return FUNC;
})();
l296;
var l298=internals.intern('DEFINE-RULE','IIIIKA');
var l299=internals.intern('KEYWORDP','COMMON-LISP');
var l300=internals.intern('INVALID-TO-ELEM','KEYWORD');
l300.value=l300;
var l301=internals.intern('WARN','COMMON-LISP');
var l302=internals.intern('LOCKED-FROM','KEYWORD');
l302.value=l302;
l298.fvalue=(function(){var FUNC=(function JSCL_USER_DEFINERULE(values,v171,v172,v173){internals.checkArgsAtLeast(arguments.length-1,2);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 2:v173=internals.symbolValue(l275);
;
default:break;
}var v174=this;
return (function(){(function(v176,v177){return (function(){return (function(){var v179=1;
var v180=[];
TBLOOP:while (true){try{switch(v179){case 1:if (l46.fvalue(internals.pv,v177)!==l3.value) (function(){throw new internals.TagNLX(v180,2);
})();
 else l3.value;
v176=internals.car(v177);
v177=internals.cdr(v177);
if ((function(v181){return v181!==l3.value?v181:(function(v182){return v182!==l3.value?v182:l49.fvalue(internals.pv,v176)!==l3.value?l47.fvalue(internals.pv,v176):l3.value;
})(l299.fvalue(internals.pv,v176));
})((function(){var X=v176;
return typeof X=='string'&&(X.length==1||X.length==2)?l20.value:l3.value;
})())!==l3.value) l3.value;
 else if (v173!==l3.value) l23.fvalue(internals.pv,l274,l267.value,v176,l270.value,l300.value);
 else l301.fvalue(internals.pv,l274,l267.value,v176,l270.value,l300.value);
(function(){throw new internals.TagNLX(v180,1);
})();
case 2:default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v180) v179=JUMP.label;
 else throw JUMP;
}}return l3.value;
})();
})();
})(l3.value,v172);
if (l47.fvalue(internals.pv,v171)!==l3.value) if (v173!==l3.value) l23.fvalue(internals.pv,l274,l267.value,v171,l270.value,l302.value);
 else l301.fvalue(internals.pv,l274,l267.value,v171,l270.value,l302.value);
 else (function(){var v184=v171;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v186){switch(arguments.length-1){case 0:v186=l3.value;
;
default:break;
}var v185=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v185=new internals.Cons(arguments[I+1],v185);
var v187=this;
return l31.fvalue(values,v186,v171,internals.symbolValue(l279));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v172;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return v171;
})();
});
FUNC.fname='DEFINE-RULE';
FUNC.docstring="Define rule for the `from' to `to'.\nReturn values are `from'.\n\nArguments:\n+ `from'   should be {character | keyword}\n  `from'   should not be character;\n+ `to'     should be ({character | keyword | list})\n+ `strict' raise error/warn when:\n  + `from' is invalid ---> invalid-from-rule\n  + `to'   is invalid ---> invalid-to-rule\n";
return FUNC;
})();
l298;
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
