(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.intern('*PACKAGE*','COMMON-LISP');
var l2=internals.intern('IIIIKA/WEB','KEYWORD');
l2.value=l2;
var l3=internals.intern('FIND-PACKAGE-OR-FAIL');
l1.value=l3.fvalue(internals.pv,l2);
var l4=internals.intern('BYNAME-SELECT','IIIIKA/WEB');
var l5=internals.make_lisp_string('byname-select-title');
var l6=internals.intern('GET-ELEM-BY-ID','IIIIKA/WEB');
var l7=internals.intern('NIL','COMMON-LISP');
var l8=internals.intern('(SETF_TEXT)','IIIIKA/WEB');
var l9=internals.intern('BYNAME','KEYWORD');
l9.value=l9;
var l10=internals.intern('LIST','COMMON-LISP');
var l11=internals.intern('GETUI','IIIIKA/WEB');
var l12=internals.make_lisp_string('byname-select-message');
var l13=internals.intern('CLICK','KEYWORD');
l13.value=l13;
var l14=internals.intern('TO','KEYWORD');
l14.value=l14;
var l15=internals.intern('CHOOSE','KEYWORD');
l15.value=l15;
var l16=internals.make_lisp_string('byname-select-list');
var l17=internals.intern('(SETF_INNER-HTML)','IIIIKA/WEB');
var l18=internals.make_lisp_string('');
var l19=internals.make_lisp_string('li');
var l20=internals.intern('CREATE-ELEM','IIIIKA/WEB');
var l21=internals.intern('*SELF*','IIIIKA/WEB');
var l22=internals.make_lisp_string('click');
var l23=internals.intern('ADJ','KEYWORD');
l23.value=l23;
var l24=internals.intern('T','COMMON-LISP');
var l25=internals.make_lisp_string('byname-adj');
var l26=internals.make_lisp_string('byname-noun');
var l27=internals.make_lisp_string('mask');
var l28=internals.intern('HIDE-ELEM','IIIIKA/WEB');
var l29=internals.make_lisp_string('byname-select');
var l30=internals.intern('ADD-EVENT-LISTENER','IIIIKA/WEB');
var l31=internals.make_lisp_string('appendChild');
var l32=internals.intern('*LANGUAGE*','IIIIKA/WEB');
var l33=internals.intern('*BYNAME*','IIIIKA/WEB');
var l34=internals.intern('GETHASH','COMMON-LISP');
var l35=internals.intern('AREF','COMMON-LISP');
var l36=internals.intern('MAP','COMMON-LISP');
var l37=internals.make_lisp_string('mask');
var l38=internals.intern('SHOW-ELEM','IIIIKA/WEB');
var l39=internals.make_lisp_string('byname-select');
l4.fvalue=(function(){var FUNC=(function JSCL_USER_BYNAMESELECT(values,v1){internals.checkArgs(arguments.length-1,1);
var v2=this;
return (function(){(function(){var v5=l6.fvalue(internals.pv,l5);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v7){switch(arguments.length-1){case 0:v7=l7.value;
;
default:break;
}var v6=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v6=new internals.Cons(arguments[I+1],v6);
var v8=this;
return l8.fvalue(values,v7,l6.fvalue(internals.pv,l5));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l10.fvalue(internals.pv,l9.value,v1));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v10=l6.fvalue(internals.pv,l12);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v12){switch(arguments.length-1){case 0:v12=l7.value;
;
default:break;
}var v11=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v11=new internals.Cons(arguments[I+1],v11);
var v13=this;
return l8.fvalue(values,v12,l6.fvalue(internals.pv,l12));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l10.fvalue(internals.pv,l13.value,l14.value,l15.value,l9.value,v1));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(v14){(function(){var v16=v14;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v18){switch(arguments.length-1){case 0:v18=l7.value;
;
default:break;
}var v17=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v17=new internals.Cons(arguments[I+1],v17);
var v19=this;
return l17.fvalue(values,v18,v14);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return l36.fvalue(internals.pv,l7.value,(function JSCL_USER_NIL(values,v20){internals.checkArgs(arguments.length-1,1);
var v21=this;
return (function(v22){(function(){var v23=[];
try{var v24=v22;
var v25=v24;
l21.stack.push(l21.value);
v23.push(l21);
l21.value=v25;
return l30.fvalue(internals.pv,v24,l22,(function JSCL_USER_NIL(values,v26){internals.checkArgs(arguments.length-1,1);
var v27=this;
(function(){var v29=l6.fvalue(internals.pv,(v1===l23.value?l24.value:l7.value)!==l7.value?l25:l26);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v31){switch(arguments.length-1){case 0:v31=l7.value;
;
default:break;
}var v30=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v30=new internals.Cons(arguments[I+1],v30);
var v32=this;
return l8.fvalue(values,v31,l6.fvalue(internals.pv,(v1===l23.value?l24.value:l7.value)!==l7.value?l25:l26));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v20;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l27));
return l28.fvalue(values,l6.fvalue(internals.pv,l29));
}));
}finally{v23.forEach((function(S){S.value=S.stack.pop();
}));
}})();
return internals.js_to_lisp(v14[internals.xstring(l31)](internals.lisp_to_js(v22)));
})(l20.fvalue(internals.pv,l19,v20));
}),l35.fvalue(internals.pv,l34.fvalue(internals.pv,internals.symbolValue(l32),internals.symbolValue(l33)),(v1===l23.value?l24.value:l7.value)!==l7.value?0:1));
})(l6.fvalue(internals.pv,l16));
l38.fvalue(internals.pv,l6.fvalue(internals.pv,l37));
return l38.fvalue(values,l6.fvalue(internals.pv,l39));
})();
});
FUNC.fname='BYNAME-SELECT';
FUNC.docstring='Popup byname-select. ';
return FUNC;
})();
l4;
var l40=internals.intern('UPDATE-QUERY-NAME-MESSAGE','IIIIKA/WEB');
var l41=internals.make_lisp_string('query-name-input');
var l42=internals.make_lisp_string('query-name-message');
var l43=internals.make_lisp_string('value');
var l44=internals.intern('LENGTH','COMMON-LISP');
var l45=internals.make_lisp_string('...');
var l46=internals.intern('CHAR=','COMMON-LISP');
var l47=internals.make_lisp_string('span');
var l48=internals.make_lisp_string(' ');
var l49=internals.intern('APPEND-CHILDREN','IIIIKA/WEB');
var l50=internals.make_lisp_string('~C');
var l51=internals.intern('FORMAT','COMMON-LISP');
var l52=internals.make_lisp_string('span');
var l53=internals.make_lisp_string('unknown');
var l54=internals.intern('ADD-CSS-CLASS','IIIIKA/WEB');
var l55=internals.intern('ATTACH-TOOLTIP','IIIIKA/WEB');
var l56=internals.intern('IKASU-CHAR','IIIIKA');
l40.fvalue=(function(){var FUNC=(function JSCL_USER_UPDATEQUERYNAMEMESSAGE(values){internals.checkArgsAtMost(arguments.length-1,0);
var v33=this;
return (function(){return (function(){var v36=l6.fvalue(internals.pv,l41);
var v37=l6.fvalue(internals.pv,l42);
var v38=internals.js_to_lisp((function(){var TMP=v36[internals.xstring(l43)];
return TMP===undefined?l7.value:TMP;
})());
(function(){var v40=v37;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v42){switch(arguments.length-1){case 0:v42=l7.value;
;
default:break;
}var v41=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v41=new internals.Cons(arguments[I+1],v41);
var v43=this;
return l17.fvalue(values,v42,v37);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return (function(){var x1=l44.fvalue(internals.pv,v38);
if (typeof x1!='number') throw 'Not a number!';
return x1==0?l24.value:l7.value;
})()!==l7.value?(function(){var v45=v37;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v47){switch(arguments.length-1){case 0:v47=l7.value;
;
default:break;
}var v46=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v46=new internals.Cons(arguments[I+1],v46);
var v48=this;
return l8.fvalue(values,v47,v37);
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l45;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})():(function(v49){return l36.fvalue(values,l7.value,(function JSCL_USER_NIL(values,v50){internals.checkArgs(arguments.length-1,1);
var v51=this;
return (function(v52){return v52!==l7.value?v52:l46.fvalue(internals.pv,v50,' ');
})(l46.fvalue(internals.pv,v50,'\n'))!==l7.value?v49!==l7.value?l7.value:((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v55){switch(arguments.length-1){case 0:v55=l7.value;
;
default:break;
}var v54=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v54=new internals.Cons(arguments[I+1],v54);
var v56=this;
return v49=v55;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l24.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l49.fvalue(values,v37,l20.fvalue(internals.pv,l47,l48))):((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v59){switch(arguments.length-1){case 0:v59=l7.value;
;
default:break;
}var v58=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v58=new internals.Cons(arguments[I+1],v58);
var v60=this;
return v49=v59;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l7.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),(function(){var FUNC=(function JSCL_USER_NIL(values,v62,v63){switch(arguments.length-1){case 0:v62=l7.value;
;
case 1:v63=l7.value;
;
default:break;
}var v61=l7.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v61=new internals.Cons(arguments[I+1],v61);
var v64=this;
return (function(){var v66=v63!==l7.value?l51.fvalue(internals.pv,l7.value,l50,v50):v62;
var v67=l20.fvalue(internals.pv,l52,v66);
if (v63!==l7.value) {l54.fvalue(internals.pv,v67,l53);
l55.fvalue(internals.pv,v67,l11.fvalue(internals.pv,v63));
} else l7.value;
return l49.fvalue(values,v37,v67);
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l56.fvalue(values,v50);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})());
}),v38);
})(l7.value);
})();
})();
});
FUNC.fname='UPDATE-QUERY-NAME-MESSAGE';
FUNC.docstring='Refresh query name message. ';
return FUNC;
})();
l40;
var l57=internals.intern('UPDATE-NAME','IIIIKA/WEB');
var l58=internals.make_lisp_string('name');
var l59=internals.make_lisp_string('query-name-input');
var l60=internals.make_lisp_string('value');
var l61=internals.intern('ZEROP','COMMON-LISP');
var l62=internals.make_lisp_string('CLICK ME');
var l63=internals.make_lisp_string('span');
var l64=internals.make_lisp_string(' ');
var l65=internals.intern('NORMAL','KEYWORD');
l65.value=l65;
var l66=internals.intern('KEYBOARD','KEYWORD');
l66.value=l66;
var l67=internals.intern('SPACE','KEYWORD');
l67.value=l67;
var l68=internals.QIList(l65,l66,l67,l7);
var l69=internals.make_lisp_string('span');
var l70=internals.make_lisp_string('span');
var l71=internals.make_lisp_string('~C');
var l72=internals.intern('FIRST','COMMON-LISP');
var l73=internals.intern('FIND-CHARACTER','IIIIKA');
l57.fvalue=(function(){var FUNC=(function JSCL_USER_UPDATENAME(values){internals.checkArgsAtMost(arguments.length-1,0);
var v68=this;
return (function(){return (function(v70,v71){(function(){var v73=v70;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v75){switch(arguments.length-1){case 0:v75=l7.value;
;
default:break;
}var v74=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v74=new internals.Cons(arguments[I+1],v74);
var v76=this;
return l17.fvalue(values,v75,v70);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return l61.fvalue(internals.pv,l44.fvalue(internals.pv,v71))!==l7.value?(function(){var v78=v70;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v80){switch(arguments.length-1){case 0:v80=l7.value;
;
default:break;
}var v79=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v79=new internals.Cons(arguments[I+1],v79);
var v81=this;
return l17.fvalue(values,v80,v70);
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l62;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})():(function(v82){return l36.fvalue(values,l7.value,(function JSCL_USER_NIL(values,v83){internals.checkArgs(arguments.length-1,1);
var v84=this;
return (function(v85){return v85!==l7.value?v85:l46.fvalue(internals.pv,v83,' ');
})(l46.fvalue(internals.pv,v83,'\n'))!==l7.value?v82!==l7.value?l7.value:((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v88){switch(arguments.length-1){case 0:v88=l7.value;
;
default:break;
}var v87=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v87=new internals.Cons(arguments[I+1],v87);
var v89=this;
return v82=v88;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l24.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),(function(v90){l55.fvalue(internals.pv,v90,l11.fvalue(internals.pv,l68));
return l49.fvalue(values,v70,v90);
})(l20.fvalue(internals.pv,l63,l64))):((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v93){switch(arguments.length-1){case 0:v93=l7.value;
;
default:break;
}var v92=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v92=new internals.Cons(arguments[I+1],v92);
var v94=this;
return v82=v93;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l7.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),(function(){var FUNC=(function JSCL_USER_NIL(values,v96,v97){switch(arguments.length-1){case 0:v96=l7.value;
;
case 1:v97=l7.value;
;
default:break;
}var v95=l7.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v95=new internals.Cons(arguments[I+1],v95);
var v98=this;
return v97!==l7.value?(function(v99){l55.fvalue(internals.pv,v99,l11.fvalue(internals.pv,v97));
return l49.fvalue(values,v70,v99);
})(l20.fvalue(internals.pv,l69,v96)):(function(v100){return l36.fvalue(values,l7.value,(function JSCL_USER_NIL(values,v101){internals.checkArgs(arguments.length-1,1);
var v102=this;
return (function(v103){return v103!==l7.value?v103:l46.fvalue(internals.pv,v101,' ');
})(l46.fvalue(internals.pv,v101,'\n'))!==l7.value?v100!==l7.value?l7.value:((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v106){switch(arguments.length-1){case 0:v106=l7.value;
;
default:break;
}var v105=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v105=new internals.Cons(arguments[I+1],v105);
var v107=this;
return v100=v106;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l24.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l7.value):((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v110){switch(arguments.length-1){case 0:v110=l7.value;
;
default:break;
}var v109=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v109=new internals.Cons(arguments[I+1],v109);
var v111=this;
return v100=v110;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l7.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),(function(v112){return (function(){var FUNC=(function JSCL_USER_NIL(values,v114,v115){switch(arguments.length-1){case 0:v114=l7.value;
;
case 1:v115=l7.value;
;
default:break;
}var v113=l7.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v113=new internals.Cons(arguments[I+1],v113);
var v116=this;
l55.fvalue(internals.pv,v112,l11.fvalue(internals.pv,l10.fvalue(internals.pv,l72.fvalue(internals.pv,v115),l66.value,v101)));
return l49.fvalue(values,v70,v112);
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l73.fvalue(values,v101);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(l20.fvalue(internals.pv,l70,l51.fvalue(internals.pv,l7.value,l71,v101))));
}),v96);
})(l7.value);
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l56.fvalue(values,v83);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})());
}),v71);
})(l7.value);
})(l6.fvalue(internals.pv,l58),internals.js_to_lisp((function(){var TMP=l6.fvalue(internals.pv,l59)[internals.xstring(l60)];
return TMP===undefined?l7.value:TMP;
})()));
})();
});
FUNC.fname='UPDATE-NAME';
return FUNC;
})();
l57;
var l74=internals.intern('TOGGLE-KEYBOARD','IIIIKA/WEB');
var l75=internals.make_lisp_string('style');
var l76=internals.make_lisp_string('display');
var l77=internals.make_lisp_string('none');
var l78=internals.make_lisp_string('button-popuped');
var l79=internals.intern('REMOVE-CSS-CLASS','IIIIKA/WEB');
var l80=internals.make_lisp_string('style');
var l81=internals.make_lisp_string('display');
var l82=internals.make_lisp_string('none');
var l83=internals.intern('STRING=','COMMON-LISP');
var l84=internals.make_lisp_string('style');
var l85=internals.make_lisp_string('display');
var l86=internals.make_lisp_string('block');
var l87=internals.make_lisp_string('button-popuped');
var l88=internals.make_lisp_string('style');
var l89=internals.make_lisp_string('display');
var l90=internals.make_lisp_string('none');
var l91=internals.make_lisp_string('button-popuped');
l74.fvalue=(function(){var FUNC=(function JSCL_USER_TOGGLEKEYBOARD(values,v117,v118,v119){internals.checkArgsAtLeast(arguments.length-1,2);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 2:v119=l7.value;
;
default:break;
}var v120=this;
return (function(){return (function(v122,v123){return v119!==l7.value?((function(){var v125=internals.js_to_lisp((function(){var TMP=v122[internals.xstring(l75)];
return TMP===undefined?l7.value:TMP;
})());
var v126=l76;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v128){switch(arguments.length-1){case 0:v128=l7.value;
;
default:break;
}var v127=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v127=new internals.Cons(arguments[I+1],v127);
var v129=this;
return (function(){var OBJ=v125;
var TMP=OBJ[internals.xstring(v126)]=internals.lisp_to_js(v128);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l77;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l79.fvalue(values,v123,l78)):l83.fvalue(internals.pv,internals.js_to_lisp((function(){var TMP=internals.js_to_lisp((function(){var TMP=v122[internals.xstring(l80)];
return TMP===undefined?l7.value:TMP;
})())[internals.xstring(l81)];
return TMP===undefined?l7.value:TMP;
})()),l82)!==l7.value?((function(){var v131=internals.js_to_lisp((function(){var TMP=v122[internals.xstring(l84)];
return TMP===undefined?l7.value:TMP;
})());
var v132=l85;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v134){switch(arguments.length-1){case 0:v134=l7.value;
;
default:break;
}var v133=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v133=new internals.Cons(arguments[I+1],v133);
var v135=this;
return (function(){var OBJ=v131;
var TMP=OBJ[internals.xstring(v132)]=internals.lisp_to_js(v134);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l86;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l54.fvalue(values,v123,l87)):((function(){var v137=internals.js_to_lisp((function(){var TMP=v122[internals.xstring(l88)];
return TMP===undefined?l7.value:TMP;
})());
var v138=l89;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v140){switch(arguments.length-1){case 0:v140=l7.value;
;
default:break;
}var v139=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v139=new internals.Cons(arguments[I+1],v139);
var v141=this;
return (function(){var OBJ=v137;
var TMP=OBJ[internals.xstring(v138)]=internals.lisp_to_js(v140);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l90;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l79.fvalue(values,v123,l91));
})(l6.fvalue(internals.pv,v117),l6.fvalue(internals.pv,v118));
})();
});
FUNC.fname='TOGGLE-KEYBOARD';
return FUNC;
})();
l74;
var l92=internals.intern('QUERY-NAME-SELECT-KEYBOARD','IIIIKA/WEB');
var l93=internals.make_lisp_string('style');
var l94=internals.make_lisp_string('display');
var l95=internals.make_lisp_string('none');
var l96=internals.make_lisp_string('popup-keyboard-content');
var l97=internals.intern('*ROOT*');
var l98=internals.make_lisp_string('document');
var l99=internals.make_lisp_string('getElementsByClassName');
var l100=internals.make_lisp_string('button-popuped');
var l101=internals.make_lisp_string('query-name-sets');
var l102=internals.make_lisp_string('document');
var l103=internals.make_lisp_string('getElementById');
var l104=internals.make_lisp_string('children');
var l105=internals.make_lisp_string('style');
var l106=internals.make_lisp_string('display');
var l107=internals.make_lisp_string('table');
var l108=internals.make_lisp_string('~A-button');
var l109=internals.make_lisp_string('button-popuped');
l92.fvalue=(function(){var FUNC=(function JSCL_USER_QUERYNAMESELECTKEYBOARD(values,v142){internals.checkArgs(arguments.length-1,1);
var v143=this;
return (function(){l36.fvalue(internals.pv,l7.value,(function JSCL_USER_NIL(values,v145){internals.checkArgs(arguments.length-1,1);
var v146=this;
return (function(){var v148=internals.js_to_lisp((function(){var TMP=v145[internals.xstring(l93)];
return TMP===undefined?l7.value:TMP;
})());
var v149=l94;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v151){switch(arguments.length-1){case 0:v151=l7.value;
;
default:break;
}var v150=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v150=new internals.Cons(arguments[I+1],v150);
var v152=this;
return (function(){var OBJ=v148;
var TMP=OBJ[internals.xstring(v149)]=internals.lisp_to_js(v151);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l95;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
}),internals.js_to_lisp(internals.symbolValue(l97)[internals.xstring(l98)][internals.xstring(l99)](internals.lisp_to_js(l96))));
l36.fvalue(internals.pv,l7.value,(function JSCL_USER_NIL(values,v153){internals.checkArgs(arguments.length-1,1);
var v154=this;
return l79.fvalue(values,v153,l100);
}),internals.js_to_lisp((function(){var TMP=internals.js_to_lisp(internals.symbolValue(l97)[internals.xstring(l102)][internals.xstring(l103)](internals.lisp_to_js(l101)))[internals.xstring(l104)];
return TMP===undefined?l7.value:TMP;
})()));
return v142!==l7.value?((function(){var v156=internals.js_to_lisp((function(){var TMP=l6.fvalue(internals.pv,v142)[internals.xstring(l105)];
return TMP===undefined?l7.value:TMP;
})());
var v157=l106;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v159){switch(arguments.length-1){case 0:v159=l7.value;
;
default:break;
}var v158=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v158=new internals.Cons(arguments[I+1],v158);
var v160=this;
return (function(){var OBJ=v156;
var TMP=OBJ[internals.xstring(v157)]=internals.lisp_to_js(v159);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l107;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l54.fvalue(values,l6.fvalue(internals.pv,l51.fvalue(internals.pv,l7.value,l108,v142)),l109)):l7.value;
})();
});
FUNC.fname='QUERY-NAME-SELECT-KEYBOARD';
FUNC.docstring="In query name, select keyboard with `id'.\n`id' should be the keyword in `iiiika::*character-sets*'. ";
return FUNC;
})();
l92;
var l110=internals.intern('PRERENDER-KEYBOARD','IIIIKA/WEB');
var l111=internals.make_lisp_string('query-name-sets');
var l112=internals.make_lisp_string('button');
var l113=internals.make_lisp_string('query-name-~A');
var l114=internals.make_lisp_string('name');
var l115=internals.make_lisp_string('table');
var l116=internals.make_lisp_string('tr');
var l117=internals.make_lisp_string('popup-button');
var l118=internals.make_lisp_string('popup-keyboard-content');
var l119=internals.make_lisp_string('id');
var l120=internals.make_lisp_string('id');
var l121=internals.make_lisp_string('~A-button');
var l122=internals.make_lisp_string('click');
var l123=internals.make_lisp_string('td');
var l124=internals.make_lisp_string('~C');
var l125=internals.make_lisp_string('popup-button');
var l126=internals.make_lisp_string('click');
var l127=internals.make_lisp_string('value');
var l128=internals.make_lisp_string('~A~C');
var l129=internals.make_lisp_string('value');
var l130=internals.make_lisp_string('tr');
var l131=internals.intern('BWD','KEYWORD');
l131.value=l131;
var l132=internals.intern('GETF','COMMON-LISP');
var l133=internals.intern('MAPHASH','COMMON-LISP');
var l134=internals.intern('*CHARACTER-SETS*','IIIIKA');
var l135=internals.make_lisp_string('query-name-~A');
var l136=internals.intern('HIRAGANA','KEYWORD');
l136.value=l136;
l110.fvalue=(function(){var FUNC=(function JSCL_USER_PRERENDERKEYBOARD(values,v161,v162,v163){internals.checkArgsAtLeast(arguments.length-1,2);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 2:v163=8;
;
default:break;
}var v164=this;
return (function(){return (function(v166){l133.fvalue(internals.pv,(function JSCL_USER_NIL(values,v167,v168){internals.checkArgs(arguments.length-1,2);
var v169=this;
return (function(v170,v171,v172,v173,v174){l54.fvalue(internals.pv,v171,l117);
l54.fvalue(internals.pv,v173,l118);
(function(){var v176=v173;
var v177=l119;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v179){switch(arguments.length-1){case 0:v179=l7.value;
;
default:break;
}var v178=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v178=new internals.Cons(arguments[I+1],v178);
var v180=this;
return (function(){var OBJ=v176;
var TMP=OBJ[internals.xstring(v177)]=internals.lisp_to_js(v179);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v172;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v182=v171;
var v183=l120;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v185){switch(arguments.length-1){case 0:v185=l7.value;
;
default:break;
}var v184=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v184=new internals.Cons(arguments[I+1],v184);
var v186=this;
return (function(){var OBJ=v182;
var TMP=OBJ[internals.xstring(v183)]=internals.lisp_to_js(v185);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l51.fvalue(values,l7.value,l121,v172);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v187=[];
try{var v188=v171;
var v189=v188;
l21.stack.push(l21.value);
v187.push(l21);
l21.value=v189;
return l30.fvalue(internals.pv,v188,l122,(function JSCL_USER_NIL(values,v190){internals.checkArgs(arguments.length-1,1);
var v191=this;
return l92.fvalue(values,v172);
}));
}finally{v187.forEach((function(S){S.value=S.stack.pop();
}));
}})();
l49.fvalue(internals.pv,v166,v171);
l133.fvalue(internals.pv,(function JSCL_USER_NIL(values,v192,v193){internals.checkArgs(arguments.length-1,2);
var v194=this;
return (function(){var v196=internals.char_from_codepoint(v192);
var v197=l20.fvalue(internals.pv,l123,l51.fvalue(internals.pv,l7.value,l124,v196));
l54.fvalue(internals.pv,v197,l125);
(function(){var v198=[];
try{var v199=v197;
var v200=v199;
l21.stack.push(l21.value);
v198.push(l21);
l21.value=v200;
return l30.fvalue(internals.pv,v199,l126,(function JSCL_USER_NIL(values,v201){internals.checkArgs(arguments.length-1,1);
var v202=this;
(function(){var v204=l6.fvalue(internals.pv,v162);
var v205=l127;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v207){switch(arguments.length-1){case 0:v207=l7.value;
;
default:break;
}var v206=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v206=new internals.Cons(arguments[I+1],v206);
var v208=this;
return (function(){var OBJ=v204;
var TMP=OBJ[internals.xstring(v205)]=internals.lisp_to_js(v207);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l51.fvalue(values,l7.value,l128,internals.js_to_lisp((function(){var TMP=l6.fvalue(internals.pv,v162)[internals.xstring(l129)];
return TMP===undefined?l7.value:TMP;
})()),v196);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return l40.fvalue(values);
}));
}finally{v198.forEach((function(S){S.value=S.stack.pop();
}));
}})();
l49.fvalue(internals.pv,v174,v197);
(function(){var v210=1;
var v211=(function(){var x1=v170;
if (typeof x1!='number') throw 'Not a number!';
var x2=v210;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v170=v211;
})();
return (function(){var x1=v170;
if (typeof x1!='number') throw 'Not a number!';
var x2=v163;
if (typeof x2!='number') throw 'Not a number!';
return x1==x2?l24.value:l7.value;
})()!==l7.value?(l49.fvalue(internals.pv,v173,v174),(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v214){switch(arguments.length-1){case 0:v214=l7.value;
;
default:break;
}var v213=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v213=new internals.Cons(arguments[I+1],v213);
var v215=this;
return v174=v214;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l20.fvalue(values,l130,l18);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v218){switch(arguments.length-1){case 0:v218=l7.value;
;
default:break;
}var v217=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v217=new internals.Cons(arguments[I+1],v217);
var v219=this;
return v170=v218;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=0;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})()):l7.value;
})();
}),l132.fvalue(internals.pv,v168,l131.value));
if (l61.fvalue(internals.pv,v170)!==l7.value) l7.value;
 else l49.fvalue(internals.pv,v173,v174);
return l49.fvalue(values,l6.fvalue(internals.pv,v161),v173);
})(0,l20.fvalue(internals.pv,l112,l11.fvalue(internals.pv,v167)),l51.fvalue(internals.pv,l7.value,l113,internals.js_to_lisp((function(){var TMP=v167[internals.xstring(l114)];
return TMP===undefined?l7.value:TMP;
})())),l20.fvalue(internals.pv,l115,l18),l20.fvalue(internals.pv,l116,l18));
}),internals.symbolValue(l134));
return l92.fvalue(values,l51.fvalue(internals.pv,l7.value,l135,internals.js_to_lisp((function(){var TMP=l136.value[internals.xstring(l114)];
return TMP===undefined?l7.value:TMP;
})())));
})(l6.fvalue(internals.pv,l111));
})();
});
FUNC.fname='PRERENDER-KEYBOARD';
FUNC.docstring="pre-render keyboard on `elem'. ";
return FUNC;
})();
l110;
var l137=internals.intern('QUERY-NAME','IIIIKA/WEB');
var l138=internals.make_lisp_string('query-name-title');
var l139=internals.intern('USAGE','KEYWORD');
l139.value=l139;
var l140=internals.make_lisp_string('query-name-input');
var l141=internals.make_lisp_string('query-name-message');
var l142=internals.make_lisp_string('query-name-kbd');
var l143=internals.make_lisp_string('query-name-confirm');
var l144=internals.make_lisp_string('query-name-cancel');
var l145=internals.make_lisp_string('↓↓↓');
var l146=internals.make_lisp_string('value');
var l147=internals.make_lisp_string('placeholder');
var l148=internals.intern('NAME','KEYWORD');
l148.value=l148;
var l149=internals.intern('CONFIRM','KEYWORD');
l149.value=l149;
var l150=internals.intern('CANCEL','KEYWORD');
l150.value=l150;
var l151=internals.make_lisp_string('click');
var l152=internals.make_lisp_string('query-name-keyboard');
var l153=internals.make_lisp_string('query-name-kbd');
var l154=internals.make_lisp_string('click');
var l155=internals.make_lisp_string('query-name-keyboard');
var l156=internals.make_lisp_string('query-name-kbd');
var l157=internals.make_lisp_string('mask');
var l158=internals.make_lisp_string('query-name');
var l159=internals.make_lisp_string('click');
var l160=internals.make_lisp_string('query-name-keyboard');
var l161=internals.make_lisp_string('query-name-kbd');
var l162=internals.make_lisp_string('mask');
var l163=internals.make_lisp_string('query-name');
var l164=internals.make_lisp_string('input');
var l165=internals.make_lisp_string('query-name-keyboard');
var l166=internals.make_lisp_string('query-name-kbd');
var l167=internals.make_lisp_string('mask');
var l168=internals.make_lisp_string('query-name');
l137.fvalue=(function(){var FUNC=(function JSCL_USER_QUERYNAME(values){internals.checkArgsAtMost(arguments.length-1,0);
var v220=this;
return (function(){(function(){var v223=l6.fvalue(internals.pv,l138);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v225){switch(arguments.length-1){case 0:v225=l7.value;
;
default:break;
}var v224=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v224=new internals.Cons(arguments[I+1],v224);
var v226=this;
return l8.fvalue(values,v225,l6.fvalue(internals.pv,l138));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l139.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(v227,v228,v229,v230,v231){(function(){var v233=v228;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v235){switch(arguments.length-1){case 0:v235=l7.value;
;
default:break;
}var v234=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v234=new internals.Cons(arguments[I+1],v234);
var v236=this;
return l17.fvalue(values,v235,v228);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l145;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v238=v227;
var v239=l146;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v241){switch(arguments.length-1){case 0:v241=l7.value;
;
default:break;
}var v240=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v240=new internals.Cons(arguments[I+1],v240);
var v242=this;
return (function(){var OBJ=v238;
var TMP=OBJ[internals.xstring(v239)]=internals.lisp_to_js(v241);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v244=v227;
var v245=l147;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v247){switch(arguments.length-1){case 0:v247=l7.value;
;
default:break;
}var v246=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v246=new internals.Cons(arguments[I+1],v246);
var v248=this;
return (function(){var OBJ=v244;
var TMP=OBJ[internals.xstring(v245)]=internals.lisp_to_js(v247);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l148.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v250=v230;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v252){switch(arguments.length-1){case 0:v252=l7.value;
;
default:break;
}var v251=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v251=new internals.Cons(arguments[I+1],v251);
var v253=this;
return l8.fvalue(values,v252,v230);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l149.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v255=v229;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v257){switch(arguments.length-1){case 0:v257=l7.value;
;
default:break;
}var v256=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v256=new internals.Cons(arguments[I+1],v256);
var v258=this;
return l8.fvalue(values,v257,v229);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l66.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v260=v231;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v262){switch(arguments.length-1){case 0:v262=l7.value;
;
default:break;
}var v261=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v261=new internals.Cons(arguments[I+1],v261);
var v263=this;
return l8.fvalue(values,v262,v231);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l150.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v264=[];
try{var v265=v229;
var v266=v265;
l21.stack.push(l21.value);
v264.push(l21);
l21.value=v266;
return l30.fvalue(internals.pv,v265,l151,(function JSCL_USER_NIL(values,v267){internals.checkArgs(arguments.length-1,1);
var v268=this;
return l74.fvalue(values,l152,l153);
}));
}finally{v264.forEach((function(S){S.value=S.stack.pop();
}));
}})();
(function(){var v269=[];
try{var v270=v231;
var v271=v270;
l21.stack.push(l21.value);
v269.push(l21);
l21.value=v271;
return l30.fvalue(internals.pv,v270,l154,(function JSCL_USER_NIL(values,v272){internals.checkArgs(arguments.length-1,1);
var v273=this;
l74.fvalue(internals.pv,l155,l156,l24.value);
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l157));
return l28.fvalue(values,l6.fvalue(internals.pv,l158));
}));
}finally{v269.forEach((function(S){S.value=S.stack.pop();
}));
}})();
(function(){var v274=[];
try{var v275=v230;
var v276=v275;
l21.stack.push(l21.value);
v274.push(l21);
l21.value=v276;
return l30.fvalue(internals.pv,v275,l159,(function JSCL_USER_NIL(values,v277){internals.checkArgs(arguments.length-1,1);
var v278=this;
l57.fvalue(internals.pv);
l74.fvalue(internals.pv,l160,l161,l24.value);
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l162));
return l28.fvalue(values,l6.fvalue(internals.pv,l163));
}));
}finally{v274.forEach((function(S){S.value=S.stack.pop();
}));
}})();
return (function(){var v279=[];
try{var v280=v227;
var v281=v280;
l21.stack.push(l21.value);
v279.push(l21);
l21.value=v281;
return l30.fvalue(internals.pv,v280,l164,(function JSCL_USER_NIL(values,v282){internals.checkArgs(arguments.length-1,1);
var v283=this;
return l40.fvalue(values);
}));
}finally{v279.forEach((function(S){S.value=S.stack.pop();
}));
}})();
})(l6.fvalue(internals.pv,l140),l6.fvalue(internals.pv,l141),l6.fvalue(internals.pv,l142),l6.fvalue(internals.pv,l143),l6.fvalue(internals.pv,l144));
l74.fvalue(internals.pv,l165,l166,l24.value);
l38.fvalue(internals.pv,l6.fvalue(internals.pv,l167));
return l38.fvalue(values,l6.fvalue(internals.pv,l168));
})();
});
FUNC.fname='QUERY-NAME';
FUNC.docstring="Like `query' but popup `query-name' widget.\n\nThe input name will be checked and goes to `query-name-message'\nwhile input, if fails, will goes like color red. ";
return FUNC;
})();
l137;
var l169=internals.intern('MAIN','IIIIKA/WEB');
var l170=internals.make_lisp_string('name');
var l171=internals.make_lisp_string('click');
var l172=internals.make_lisp_string('detail');
var l173=internals.make_lisp_string('byname-adj');
var l174=internals.intern('CN-ZH','KEYWORD');
l174.value=l174;
var l175=internals.intern('GET-BYNAME--AREF','IIIIKA/WEB');
var l176=internals.make_lisp_string('detail');
var l177=internals.intern('NOUN','KEYWORD');
l177.value=l177;
var l178=internals.make_lisp_string('byname-noun');
var l179=internals.make_lisp_string('byname-adj');
var l180=internals.make_lisp_string('click');
var l181=internals.make_lisp_string('byname-noun');
var l182=internals.make_lisp_string('click');
var l183=internals.intern('SORRY','KEYWORD');
l183.value=l183;
var l184=internals.intern('BADGE','KEYWORD');
l184.value=l184;
var l185=internals.intern('*-IS-WORKING','KEYWORD');
l185.value=l185;
var l186=internals.QIList(l183,l184,l185,l7);
var l187=internals.intern('ALERT','IIIIKA/WEB');
var l188=internals.make_lisp_string('badge-1');
var l189=internals.make_lisp_string('click');
var l190=internals.make_lisp_string('badge-2');
var l191=internals.make_lisp_string('click');
var l192=internals.make_lisp_string('badge-3');
var l193=internals.make_lisp_string('click');
var l194=internals.make_lisp_string('alert-button');
var l195=internals.make_lisp_string('click');
var l196=internals.make_lisp_string('alert');
var l197=internals.make_lisp_string('mask');
var l198=internals.make_lisp_string('byname-select-cancel');
var l199=internals.make_lisp_string('click');
var l200=internals.make_lisp_string('byname-select');
var l201=internals.make_lisp_string('mask');
var l202=internals.make_lisp_string('iiiika');
var l203=internals.make_lisp_string('click');
var l204=internals.make_lisp_string('query-name-keyboard');
var l205=internals.make_lisp_string('query-name-input');
l169.fvalue=(function(){var FUNC=(function JSCL_USER_MAIN(values){internals.checkArgsAtMost(arguments.length-1,0);
var v284=this;
return (function(){(function(v289){return l30.fvalue(internals.pv,l6.fvalue(internals.pv,l170),l171,v289);
})((function JSCL_USER_NIL(values,v286){internals.checkArgs(arguments.length-1,1);
var v287=this;
return (function(){return l137.fvalue(values);
})();
}));
(function(v306,v307){l30.fvalue(internals.pv,l6.fvalue(internals.pv,l179),l180,v306);
l30.fvalue(internals.pv,l6.fvalue(internals.pv,l181),l182,v307);
v306(internals.pv);
return v307(internals.pv);
})((function JSCL_USER_NIL(values,v290){internals.checkArgsAtMost(arguments.length-1,1);
switch(arguments.length-1){case 0:v290=l7.value;
;
default:break;
}var v291=this;
return (function(){return (v290!==l7.value?(function(){var x1=internals.js_to_lisp((function(){var TMP=v290[internals.xstring(l172)];
return TMP===undefined?l7.value:TMP;
})());
if (typeof x1!='number') throw 'Not a number!';
return x1==2?l24.value:l7.value;
})():l7.value)!==l7.value?l4.fvalue(values,l23.value):(function(){var v294=l6.fvalue(internals.pv,l173);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v296){switch(arguments.length-1){case 0:v296=l7.value;
;
default:break;
}var v295=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v295=new internals.Cons(arguments[I+1],v295);
var v297=this;
return l8.fvalue(values,v296,l6.fvalue(internals.pv,l173));
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l175.fvalue(values,0,l7.value,l174.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
}),(function JSCL_USER_NIL(values,v298){internals.checkArgsAtMost(arguments.length-1,1);
switch(arguments.length-1){case 0:v298=l7.value;
;
default:break;
}var v299=this;
return (function(){return (v298!==l7.value?(function(){var x1=internals.js_to_lisp((function(){var TMP=v298[internals.xstring(l176)];
return TMP===undefined?l7.value:TMP;
})());
if (typeof x1!='number') throw 'Not a number!';
return x1==2?l24.value:l7.value;
})():l7.value)!==l7.value?l4.fvalue(values,l177.value):(function(){var v302=l6.fvalue(internals.pv,l178);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v304){switch(arguments.length-1){case 0:v304=l7.value;
;
default:break;
}var v303=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v303=new internals.Cons(arguments[I+1],v303);
var v305=this;
return l8.fvalue(values,v304,l6.fvalue(internals.pv,l178));
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l175.fvalue(values,1,l7.value,l174.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
}));
(function(v311){l30.fvalue(internals.pv,l6.fvalue(internals.pv,l188),l189,v311);
l30.fvalue(internals.pv,l6.fvalue(internals.pv,l190),l191,v311);
return l30.fvalue(internals.pv,l6.fvalue(internals.pv,l192),l193,v311);
})((function JSCL_USER_NIL(values,v308){internals.checkArgs(arguments.length-1,1);
var v309=this;
return (function(){return l187.fvalue(values,l11.fvalue(internals.pv,l186));
})();
}));
(function(){var v312=[];
try{var v313=l6.fvalue(internals.pv,l194);
var v314=v313;
l21.stack.push(l21.value);
v312.push(l21);
l21.value=v314;
return l30.fvalue(internals.pv,v313,l195,(function JSCL_USER_NIL(values,v315){internals.checkArgs(arguments.length-1,1);
var v316=this;
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l196));
return l28.fvalue(values,l6.fvalue(internals.pv,l197));
}));
}finally{v312.forEach((function(S){S.value=S.stack.pop();
}));
}})();
(function(){var v317=[];
try{var v318=l6.fvalue(internals.pv,l198);
var v319=v318;
l21.stack.push(l21.value);
v317.push(l21);
l21.value=v319;
return l30.fvalue(internals.pv,v318,l199,(function JSCL_USER_NIL(values,v320){internals.checkArgs(arguments.length-1,1);
var v321=this;
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l200));
return l28.fvalue(values,l6.fvalue(internals.pv,l201));
}));
}finally{v317.forEach((function(S){S.value=S.stack.pop();
}));
}})();
(function(){var v322=[];
try{var v323=l6.fvalue(internals.pv,l202);
var v324=v323;
l21.stack.push(l21.value);
v322.push(l21);
l21.value=v324;
return l30.fvalue(internals.pv,v323,l203,(function JSCL_USER_NIL(values,v325){internals.checkArgs(arguments.length-1,1);
var v326=this;
return l7.value;
}));
}finally{v322.forEach((function(S){S.value=S.stack.pop();
}));
}})();
return l110.fvalue(values,l204,l205);
})();
});
FUNC.fname='MAIN';
FUNC.docstring='Binds all the events to front-end UI. ';
return FUNC;
})();
l169;
l169.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
