(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.intern('*PACKAGE*','COMMON-LISP');
var l2=internals.intern('IIIIKA/WEB','KEYWORD');
l2.value=l2;
var l3=internals.intern('FIND-PACKAGE-OR-FAIL');
l1.value=l3.fvalue(internals.pv,l2);
var l4=internals.intern('BYNAME-SELECT','IIIIKA/WEB');
var l5=internals.make_lisp_string('byname-select-title');
var l6=internals.intern('GET-ELEM-BY-ID','IIIIKA/WEB');
var l7=internals.intern('NIL','COMMON-LISP');
var l8=internals.intern('(SETF_TEXT)','IIIIKA/WEB');
var l9=internals.intern('BYNAME','KEYWORD');
l9.value=l9;
var l10=internals.intern('LIST','COMMON-LISP');
var l11=internals.intern('GETUI','IIIIKA/WEB');
var l12=internals.make_lisp_string('byname-select-message');
var l13=internals.intern('CLICK','KEYWORD');
l13.value=l13;
var l14=internals.intern('TO','KEYWORD');
l14.value=l14;
var l15=internals.intern('CHOOSE','KEYWORD');
l15.value=l15;
var l16=internals.make_lisp_string('byname-select-list');
var l17=internals.intern('(SETF_INNER-HTML)','IIIIKA/WEB');
var l18=internals.make_lisp_string('');
var l19=internals.make_lisp_string('li');
var l20=internals.intern('CREATE-ELEM','IIIIKA/WEB');
var l21=internals.intern('*SELF*','IIIIKA/WEB');
var l22=internals.make_lisp_string('click');
var l23=internals.intern('ADJ','KEYWORD');
l23.value=l23;
var l24=internals.intern('T','COMMON-LISP');
var l25=internals.make_lisp_string('byname-adj');
var l26=internals.make_lisp_string('byname-noun');
var l27=internals.make_lisp_string('mask');
var l28=internals.intern('HIDE-ELEM','IIIIKA/WEB');
var l29=internals.make_lisp_string('byname-select');
var l30=internals.intern('ADD-EVENT-LISTENER','IIIIKA/WEB');
var l31=internals.make_lisp_string('appendChild');
var l32=internals.intern('*LANGUAGE*','IIIIKA/WEB');
var l33=internals.intern('*BYNAME*','IIIIKA/WEB');
var l34=internals.intern('GETHASH','COMMON-LISP');
var l35=internals.intern('AREF','COMMON-LISP');
var l36=internals.intern('MAP','COMMON-LISP');
var l37=internals.make_lisp_string('mask');
var l38=internals.intern('SHOW-ELEM','IIIIKA/WEB');
var l39=internals.make_lisp_string('byname-select');
l4.fvalue=(function(){var FUNC=(function JSCL_USER_BYNAMESELECT(values,v1){internals.checkArgs(arguments.length-1,1);
var v2=this;
return (function(){(function(){var v5=l6.fvalue(internals.pv,l5);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v7){switch(arguments.length-1){case 0:v7=l7.value;
;
default:break;
}var v6=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v6=new internals.Cons(arguments[I+1],v6);
var v8=this;
return l8.fvalue(values,v7,l6.fvalue(internals.pv,l5));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l10.fvalue(internals.pv,l9.value,v1));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v10=l6.fvalue(internals.pv,l12);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v12){switch(arguments.length-1){case 0:v12=l7.value;
;
default:break;
}var v11=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v11=new internals.Cons(arguments[I+1],v11);
var v13=this;
return l8.fvalue(values,v12,l6.fvalue(internals.pv,l12));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l10.fvalue(internals.pv,l13.value,l14.value,l15.value,l9.value,v1));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(v14){(function(){var v16=v14;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v18){switch(arguments.length-1){case 0:v18=l7.value;
;
default:break;
}var v17=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v17=new internals.Cons(arguments[I+1],v17);
var v19=this;
return l17.fvalue(values,v18,v14);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return l36.fvalue(internals.pv,l7.value,(function JSCL_USER_NIL(values,v20){internals.checkArgs(arguments.length-1,1);
var v21=this;
return (function(v22){(function(){var v23=[];
try{var v24=v22;
var v25=v24;
l21.stack.push(l21.value);
v23.push(l21);
l21.value=v25;
return l30.fvalue(internals.pv,v24,l22,(function JSCL_USER_NIL(values,v26){internals.checkArgs(arguments.length-1,1);
var v27=this;
(function(){var v29=l6.fvalue(internals.pv,(v1===l23.value?l24.value:l7.value)!==l7.value?l25:l26);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v31){switch(arguments.length-1){case 0:v31=l7.value;
;
default:break;
}var v30=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v30=new internals.Cons(arguments[I+1],v30);
var v32=this;
return l8.fvalue(values,v31,l6.fvalue(internals.pv,(v1===l23.value?l24.value:l7.value)!==l7.value?l25:l26));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v20;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l27));
return l28.fvalue(values,l6.fvalue(internals.pv,l29));
}));
}finally{v23.forEach((function(S){S.value=S.stack.pop();
}));
}})();
return internals.js_to_lisp(v14[internals.xstring(l31)](internals.lisp_to_js(v22)));
})(l20.fvalue(internals.pv,l19,v20));
}),l35.fvalue(internals.pv,l34.fvalue(internals.pv,internals.symbolValue(l32),internals.symbolValue(l33)),(v1===l23.value?l24.value:l7.value)!==l7.value?0:1));
})(l6.fvalue(internals.pv,l16));
l38.fvalue(internals.pv,l6.fvalue(internals.pv,l37));
return l38.fvalue(values,l6.fvalue(internals.pv,l39));
})();
});
FUNC.fname='BYNAME-SELECT';
FUNC.docstring='Popup byname-select. ';
return FUNC;
})();
l4;
var l40=internals.intern('QUERY-NAME','IIIIKA/WEB');
var l41=internals.make_lisp_string('query-name-title');
var l42=internals.intern('USAGE','KEYWORD');
l42.value=l42;
var l43=internals.make_lisp_string('query-name-input');
var l44=internals.make_lisp_string('query-name-message');
var l45=internals.make_lisp_string('query-name-confirm');
var l46=internals.make_lisp_string('query-name-cancel');
var l47=internals.make_lisp_string('value');
var l48=internals.make_lisp_string('placeholder');
var l49=internals.intern('NAME','KEYWORD');
l49.value=l49;
var l50=internals.intern('CONFIRM','KEYWORD');
l50.value=l50;
var l51=internals.intern('CANCEL','KEYWORD');
l51.value=l51;
var l52=internals.make_lisp_string('click');
var l53=internals.make_lisp_string('mask');
var l54=internals.make_lisp_string('query-name');
var l55=internals.make_lisp_string('click');
var l56=internals.make_lisp_string('name');
var l57=internals.make_lisp_string('value');
var l58=internals.intern('IKASU','IIIIKA');
var l59=internals.make_lisp_string('mask');
var l60=internals.make_lisp_string('query-name');
var l61=internals.make_lisp_string('input');
var l62=internals.intern('CHAR=','COMMON-LISP');
var l63=internals.make_lisp_string('span');
var l64=internals.make_lisp_string(' ');
var l65=internals.intern('APPEND-CHILDREN','IIIIKA/WEB');
var l66=internals.make_lisp_string('~C');
var l67=internals.intern('FORMAT','COMMON-LISP');
var l68=internals.make_lisp_string('span');
var l69=internals.make_lisp_string('unknown');
var l70=internals.intern('ADD-CSS-CLASS','IIIIKA/WEB');
var l71=internals.intern('ATTACH-TOOLTIP','IIIIKA/WEB');
var l72=internals.intern('IKASU-CHAR','IIIIKA');
var l73=internals.make_lisp_string('value');
var l74=internals.make_lisp_string('mask');
var l75=internals.make_lisp_string('query-name');
l40.fvalue=(function(){var FUNC=(function JSCL_USER_QUERYNAME(values){internals.checkArgsAtMost(arguments.length-1,0);
var v33=this;
return (function(){(function(){var v36=l6.fvalue(internals.pv,l41);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v38){switch(arguments.length-1){case 0:v38=l7.value;
;
default:break;
}var v37=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v37=new internals.Cons(arguments[I+1],v37);
var v39=this;
return l8.fvalue(values,v38,l6.fvalue(internals.pv,l41));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l42.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(v40,v41,v42,v43){(function(){var v45=v41;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v47){switch(arguments.length-1){case 0:v47=l7.value;
;
default:break;
}var v46=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v46=new internals.Cons(arguments[I+1],v46);
var v48=this;
return l17.fvalue(values,v47,v41);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v50=v40;
var v51=l47;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v53){switch(arguments.length-1){case 0:v53=l7.value;
;
default:break;
}var v52=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v52=new internals.Cons(arguments[I+1],v52);
var v54=this;
return (function(){var OBJ=v50;
var TMP=OBJ[internals.xstring(v51)]=internals.lisp_to_js(v53);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v56=v40;
var v57=l48;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v59){switch(arguments.length-1){case 0:v59=l7.value;
;
default:break;
}var v58=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v58=new internals.Cons(arguments[I+1],v58);
var v60=this;
return (function(){var OBJ=v56;
var TMP=OBJ[internals.xstring(v57)]=internals.lisp_to_js(v59);
return TMP===undefined?l7.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l49.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v62=v42;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v64){switch(arguments.length-1){case 0:v64=l7.value;
;
default:break;
}var v63=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v63=new internals.Cons(arguments[I+1],v63);
var v65=this;
return l8.fvalue(values,v64,v42);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l50.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v67=v43;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v69){switch(arguments.length-1){case 0:v69=l7.value;
;
default:break;
}var v68=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v68=new internals.Cons(arguments[I+1],v68);
var v70=this;
return l8.fvalue(values,v69,v43);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l11.fvalue(values,l51.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v71=[];
try{var v72=v43;
var v73=v72;
l21.stack.push(l21.value);
v71.push(l21);
l21.value=v73;
return l30.fvalue(internals.pv,v72,l52,(function JSCL_USER_NIL(values,v74){internals.checkArgs(arguments.length-1,1);
var v75=this;
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l53));
return l28.fvalue(values,l6.fvalue(internals.pv,l54));
}));
}finally{v71.forEach((function(S){S.value=S.stack.pop();
}));
}})();
(function(){var v76=[];
try{var v77=v42;
var v78=v77;
l21.stack.push(l21.value);
v76.push(l21);
l21.value=v78;
return l30.fvalue(internals.pv,v77,l55,(function JSCL_USER_NIL(values,v79){internals.checkArgs(arguments.length-1,1);
var v80=this;
(function(){var v82=l6.fvalue(internals.pv,l56);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v84){switch(arguments.length-1){case 0:v84=l7.value;
;
default:break;
}var v83=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v83=new internals.Cons(arguments[I+1],v83);
var v85=this;
return l8.fvalue(values,v84,l6.fvalue(internals.pv,l56));
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l58.fvalue(values,internals.js_to_lisp((function(){var TMP=v40[internals.xstring(l57)];
return TMP===undefined?l7.value:TMP;
})()));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l59));
return l28.fvalue(values,l6.fvalue(internals.pv,l60));
}));
}finally{v76.forEach((function(S){S.value=S.stack.pop();
}));
}})();
return (function(){var v86=[];
try{var v87=v40;
var v88=v87;
l21.stack.push(l21.value);
v86.push(l21);
l21.value=v88;
return l30.fvalue(internals.pv,v87,l61,(function JSCL_USER_NIL(values,v89){internals.checkArgs(arguments.length-1,1);
var v90=this;
(function(){var v92=v41;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v94){switch(arguments.length-1){case 0:v94=l7.value;
;
default:break;
}var v93=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v93=new internals.Cons(arguments[I+1],v93);
var v95=this;
return l17.fvalue(values,v94,v41);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l18;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return (function(v96){return l36.fvalue(values,l7.value,(function JSCL_USER_NIL(values,v97){internals.checkArgs(arguments.length-1,1);
var v98=this;
return (function(v99){return v99!==l7.value?v99:l62.fvalue(internals.pv,v97,' ');
})(l62.fvalue(internals.pv,v97,'\n'))!==l7.value?v96!==l7.value?l7.value:((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v102){switch(arguments.length-1){case 0:v102=l7.value;
;
default:break;
}var v101=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v101=new internals.Cons(arguments[I+1],v101);
var v103=this;
return v96=v102;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l24.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l65.fvalue(values,v41,l20.fvalue(internals.pv,l63,l64))):((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v106){switch(arguments.length-1){case 0:v106=l7.value;
;
default:break;
}var v105=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v105=new internals.Cons(arguments[I+1],v105);
var v107=this;
return v96=v106;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l7.value;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),(function(){var FUNC=(function JSCL_USER_NIL(values,v109,v110){switch(arguments.length-1){case 0:v109=l7.value;
;
case 1:v110=l7.value;
;
default:break;
}var v108=l7.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v108=new internals.Cons(arguments[I+1],v108);
var v111=this;
return (function(){var v113=v110!==l7.value?l67.fvalue(internals.pv,l7.value,l66,v97):v109;
var v114=l20.fvalue(internals.pv,l68,v113);
if (v110!==l7.value) {l70.fvalue(internals.pv,v114,l69);
l71.fvalue(internals.pv,v114,l11.fvalue(internals.pv,v110));
} else l7.value;
return l65.fvalue(values,v41,v114);
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l72.fvalue(values,v97);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})());
}),internals.js_to_lisp((function(){var TMP=v40[internals.xstring(l73)];
return TMP===undefined?l7.value:TMP;
})()));
})(l7.value);
}));
}finally{v86.forEach((function(S){S.value=S.stack.pop();
}));
}})();
})(l6.fvalue(internals.pv,l43),l6.fvalue(internals.pv,l44),l6.fvalue(internals.pv,l45),l6.fvalue(internals.pv,l46));
l38.fvalue(internals.pv,l6.fvalue(internals.pv,l74));
return l38.fvalue(values,l6.fvalue(internals.pv,l75));
})();
});
FUNC.fname='QUERY-NAME';
FUNC.docstring="Like `query' but popup `query-name' widget.\n\nThe input name will be checked and goes to `query-name-message'\nwhile input, if fails, will goes like color red. ";
return FUNC;
})();
l40;
var l76=internals.intern('MAIN','IIIIKA/WEB');
var l77=internals.make_lisp_string('name');
var l78=internals.make_lisp_string('click');
var l79=internals.make_lisp_string('detail');
var l80=internals.make_lisp_string('byname-adj');
var l81=internals.intern('CN-ZH','KEYWORD');
l81.value=l81;
var l82=internals.intern('GET-BYNAME--AREF','IIIIKA/WEB');
var l83=internals.make_lisp_string('detail');
var l84=internals.intern('NOUN','KEYWORD');
l84.value=l84;
var l85=internals.make_lisp_string('byname-noun');
var l86=internals.make_lisp_string('byname-adj');
var l87=internals.make_lisp_string('click');
var l88=internals.make_lisp_string('byname-noun');
var l89=internals.make_lisp_string('click');
var l90=internals.intern('SORRY','KEYWORD');
l90.value=l90;
var l91=internals.intern('BADGE','KEYWORD');
l91.value=l91;
var l92=internals.intern('*-IS-WORKING','KEYWORD');
l92.value=l92;
var l93=internals.QIList(l90,l91,l92,l7);
var l94=internals.intern('ALERT','IIIIKA/WEB');
var l95=internals.make_lisp_string('badge-1');
var l96=internals.make_lisp_string('click');
var l97=internals.make_lisp_string('badge-2');
var l98=internals.make_lisp_string('click');
var l99=internals.make_lisp_string('badge-3');
var l100=internals.make_lisp_string('click');
var l101=internals.make_lisp_string('alert-button');
var l102=internals.make_lisp_string('click');
var l103=internals.make_lisp_string('alert');
var l104=internals.make_lisp_string('mask');
var l105=internals.make_lisp_string('byname-select-cancel');
var l106=internals.make_lisp_string('click');
var l107=internals.make_lisp_string('byname-select');
var l108=internals.make_lisp_string('mask');
var l109=internals.make_lisp_string('iiiika');
var l110=internals.make_lisp_string('click');
l76.fvalue=(function(){var FUNC=(function JSCL_USER_MAIN(values){internals.checkArgsAtMost(arguments.length-1,0);
var v115=this;
return (function(){(function(v120){return l30.fvalue(internals.pv,l6.fvalue(internals.pv,l77),l78,v120);
})((function JSCL_USER_NIL(values,v117){internals.checkArgs(arguments.length-1,1);
var v118=this;
return (function(){return l40.fvalue(values);
})();
}));
(function(v137,v138){l30.fvalue(internals.pv,l6.fvalue(internals.pv,l86),l87,v137);
l30.fvalue(internals.pv,l6.fvalue(internals.pv,l88),l89,v138);
v137(internals.pv);
return v138(internals.pv);
})((function JSCL_USER_NIL(values,v121){internals.checkArgsAtMost(arguments.length-1,1);
switch(arguments.length-1){case 0:v121=l7.value;
;
default:break;
}var v122=this;
return (function(){return (v121!==l7.value?(function(){var x1=internals.js_to_lisp((function(){var TMP=v121[internals.xstring(l79)];
return TMP===undefined?l7.value:TMP;
})());
if (typeof x1!='number') throw 'Not a number!';
return x1==2?l24.value:l7.value;
})():l7.value)!==l7.value?l4.fvalue(values,l23.value):(function(){var v125=l6.fvalue(internals.pv,l80);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v127){switch(arguments.length-1){case 0:v127=l7.value;
;
default:break;
}var v126=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v126=new internals.Cons(arguments[I+1],v126);
var v128=this;
return l8.fvalue(values,v127,l6.fvalue(internals.pv,l80));
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l82.fvalue(values,0,l7.value,l81.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
}),(function JSCL_USER_NIL(values,v129){internals.checkArgsAtMost(arguments.length-1,1);
switch(arguments.length-1){case 0:v129=l7.value;
;
default:break;
}var v130=this;
return (function(){return (v129!==l7.value?(function(){var x1=internals.js_to_lisp((function(){var TMP=v129[internals.xstring(l83)];
return TMP===undefined?l7.value:TMP;
})());
if (typeof x1!='number') throw 'Not a number!';
return x1==2?l24.value:l7.value;
})():l7.value)!==l7.value?l4.fvalue(values,l84.value):(function(){var v133=l6.fvalue(internals.pv,l85);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v135){switch(arguments.length-1){case 0:v135=l7.value;
;
default:break;
}var v134=l7.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v134=new internals.Cons(arguments[I+1],v134);
var v136=this;
return l8.fvalue(values,v135,l6.fvalue(internals.pv,l85));
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l82.fvalue(values,1,l7.value,l81.value);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
}));
(function(v142){l30.fvalue(internals.pv,l6.fvalue(internals.pv,l95),l96,v142);
l30.fvalue(internals.pv,l6.fvalue(internals.pv,l97),l98,v142);
return l30.fvalue(internals.pv,l6.fvalue(internals.pv,l99),l100,v142);
})((function JSCL_USER_NIL(values,v139){internals.checkArgs(arguments.length-1,1);
var v140=this;
return (function(){return l94.fvalue(values,l11.fvalue(internals.pv,l93));
})();
}));
(function(){var v143=[];
try{var v144=l6.fvalue(internals.pv,l101);
var v145=v144;
l21.stack.push(l21.value);
v143.push(l21);
l21.value=v145;
return l30.fvalue(internals.pv,v144,l102,(function JSCL_USER_NIL(values,v146){internals.checkArgs(arguments.length-1,1);
var v147=this;
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l103));
return l28.fvalue(values,l6.fvalue(internals.pv,l104));
}));
}finally{v143.forEach((function(S){S.value=S.stack.pop();
}));
}})();
(function(){var v148=[];
try{var v149=l6.fvalue(internals.pv,l105);
var v150=v149;
l21.stack.push(l21.value);
v148.push(l21);
l21.value=v150;
return l30.fvalue(internals.pv,v149,l106,(function JSCL_USER_NIL(values,v151){internals.checkArgs(arguments.length-1,1);
var v152=this;
l28.fvalue(internals.pv,l6.fvalue(internals.pv,l107));
return l28.fvalue(values,l6.fvalue(internals.pv,l108));
}));
}finally{v148.forEach((function(S){S.value=S.stack.pop();
}));
}})();
return (function(){var v153=[];
try{var v154=l6.fvalue(internals.pv,l109);
var v155=v154;
l21.stack.push(l21.value);
v153.push(l21);
l21.value=v155;
return l30.fvalue(values,v154,l110,(function JSCL_USER_NIL(values,v156){internals.checkArgs(arguments.length-1,1);
var v157=this;
return l7.value;
}));
}finally{v153.forEach((function(S){S.value=S.stack.pop();
}));
}})();
})();
});
FUNC.fname='MAIN';
FUNC.docstring='Binds all the events to front-end UI. ';
return FUNC;
})();
l76;
l76.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
